### ISSUE TITLE
外链路径错误，少个‘/’，http的链接无法正常打开

### ISSUE THREAD

**Issue by yundouguai** [xiaoxian521/vue-pure-admin#100]
**Describe the bug**
外链路径错误，少个‘/’，使用https可以正常打开，但http的链接会加到路由上导致打开错误

**To Reproduce**
把外链改成http

**Screenshots**
![image](https://user-images.githubusercontent.com/45409852/141249514-1a5c3072-fbea-4e71-bc44-d5f1ec452385.png)
![image](https://user-images.githubusercontent.com/45409852/141249671-b31b3a79-e157-4a1d-ace2-6d92c8e80b81.png)

**Comment by hb0730** [comment]
原因： https://github.com/xiaoxian521/vue-pure-admin/blob/main/src/layout/components/sidebar/sidebarItem.vue#L71

**Comment by xiaoxian521** [comment]
@yundouguai 并未发现你说的问题，下图使用http正常打开
![image](https://user-images.githubusercontent.com/44761321/141309541-111b6254-9505-4481-acf1-ce0528638e53.png)
