### ISSUE TITLE
拉取更新后 样式乱了

### ISSUE THREAD

**Issue by pawelen** [xiaoxian521/vue-pure-admin#101]
控制台没有报错信息
[
![251636621770_ pic_hd](https://user-images.githubusercontent.com/18901773/141270737-8ce0e357-086a-4f06-b548-90437c7486ec.jpg)
](url)

**Comment by hb0730** [comment]
这个重新更改风格好像就好了

**Comment by hb0730** [comment]
#72

**Comment by xiaoxian521** [comment]
@pawelen 重构了storage请清除浏览器缓存
