### ISSUE TITLE
利用docker构建时，pnpm无法引入包

### ISSUE THREAD

**Issue by MorphyR** [xiaoxian521/vue-pure-admin#105]
尝试利用docker构建开发环境时，总是提示包无法引入

```
scanner-web | 
scanner-web | > vue-pure-admin@2.6.0 serve /project
scanner-web | > pnpm dev
scanner-web | 
scanner-web | 
scanner-web | > vue-pure-admin@2.6.0 dev /project
scanner-web | > vite
scanner-web | 
scanner-web | failed to load config from /project/vite.config.ts
scanner-web | error when starting dev server:
scanner-web | Error: Cannot find module '@vitejs/plugin-vue-jsx'
scanner-web | Require stack:
scanner-web | - /project/vite.config.ts
scanner-web | - /project/node_modules/vite/dist/node/chunks/dep-efe32886.js
scanner-web | - /project/node_modules/vite/dist/node/cli.js
scanner-web | - /project/node_modules/vite/bin/vite.js
scanner-web |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
scanner-web |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
scanner-web |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scanner-web |     at require (node:internal/modules/cjs/helpers:102:18)
scanner-web |     at Object.<anonymous> (/project/vite.config.ts:32:40)
scanner-web |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
scanner-web |     at Object.require.extensions.<computed> [as .ts] (/project/node_modules/vite/dist/node/chunks/dep-efe32886.js:46235:20)
scanner-web |     at Module.load (node:internal/modules/cjs/loader:981:32)
scanner-web |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
scanner-web |     at Module.require (node:internal/modules/cjs/loader:1005:19)
scanner-web |  ELIFECYCLE  Command failed with exit code 1.
scanner-web |  ELIFECYCLE  Command failed with exit code 1.
```

docker 的配置如下
```
FROM node:16.11.0-slim

RUN mkdir /project
WORKDIR /project

COPY . .

RUN npm install -g pnpm 
RUN pnpm add -g pnpm
RUN pnpm i
RUN pnpm add -D @vitejs/plugin-vue-jsx

CMD [ "pnpm", "serve"]
```

**Comment by xiaoxian521** [comment]
> 尝试利用docker构建开发环境时，总是提示包无法引入
> 
> ```
> scanner-web | 
> scanner-web | > vue-pure-admin@2.6.0 serve /project
> scanner-web | > pnpm dev
> scanner-web | 
> scanner-web | 
> scanner-web | > vue-pure-admin@2.6.0 dev /project
> scanner-web | > vite
> scanner-web | 
> scanner-web | failed to load config from /project/vite.config.ts
> scanner-web | error when starting dev server:
> scanner-web | Error: Cannot find module '@vitejs/plugin-vue-jsx'
> scanner-web | Require stack:
> scanner-web | - /project/vite.config.ts
> scanner-web | - /project/node_modules/vite/dist/node/chunks/dep-efe32886.js
> scanner-web | - /project/node_modules/vite/dist/node/cli.js
> scanner-web | - /project/node_modules/vite/bin/vite.js
> scanner-web |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
> scanner-web |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
> scanner-web |     at Module.require (node:internal/modules/cjs/loader:1005:19)
> scanner-web |     at require (node:internal/modules/cjs/helpers:102:18)
> scanner-web |     at Object.<anonymous> (/project/vite.config.ts:32:40)
> scanner-web |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
> scanner-web |     at Object.require.extensions.<computed> [as .ts] (/project/node_modules/vite/dist/node/chunks/dep-efe32886.js:46235:20)
> scanner-web |     at Module.load (node:internal/modules/cjs/loader:981:32)
> scanner-web |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> scanner-web |     at Module.require (node:internal/modules/cjs/loader:1005:19)
> scanner-web |  ELIFECYCLE  Command failed with exit code 1.
> scanner-web |  ELIFECYCLE  Command failed with exit code 1.
> ```
> 
> docker 的配置如下
> 
> ```
> FROM node:16.11.0-slim
> 
> RUN mkdir /project
> WORKDIR /project
> 
> COPY . .
> 
> RUN npm install -g pnpm 
> RUN pnpm add -g pnpm
> RUN pnpm i
> RUN pnpm add -D @vitejs/plugin-vue-jsx
> 
> CMD [ "pnpm", "serve"]
> ```

FROM node:16.11.0-slim

RUN mkdir /project
WORKDIR /project

COPY . .

RUN npm install -g pnpm 
RUN pnpm install
RUN pnpm serve

CMD [ "pnpm", "serve"]

**Comment by MorphyR** [comment]
> > 尝试利用docker构建开发环境时，总是提示包无法引入
> > ```
> > scanner-web | 
> > scanner-web | > vue-pure-admin@2.6.0 serve /project
> > scanner-web | > pnpm dev
> > scanner-web | 
> > scanner-web | 
> > scanner-web | > vue-pure-admin@2.6.0 dev /project
> > scanner-web | > vite
> > scanner-web | 
> > scanner-web | failed to load config from /project/vite.config.ts
> > scanner-web | error when starting dev server:
> > scanner-web | Error: Cannot find module '@vitejs/plugin-vue-jsx'
> > scanner-web | Require stack:
> > scanner-web | - /project/vite.config.ts
> > scanner-web | - /project/node_modules/vite/dist/node/chunks/dep-efe32886.js
> > scanner-web | - /project/node_modules/vite/dist/node/cli.js
> > scanner-web | - /project/node_modules/vite/bin/vite.js
> > scanner-web |     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
> > scanner-web |     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
> > scanner-web |     at Module.require (node:internal/modules/cjs/loader:1005:19)
> > scanner-web |     at require (node:internal/modules/cjs/helpers:102:18)
> > scanner-web |     at Object.<anonymous> (/project/vite.config.ts:32:40)
> > scanner-web |     at Module._compile (node:internal/modules/cjs/loader:1101:14)
> > scanner-web |     at Object.require.extensions.<computed> [as .ts] (/project/node_modules/vite/dist/node/chunks/dep-efe32886.js:46235:20)
> > scanner-web |     at Module.load (node:internal/modules/cjs/loader:981:32)
> > scanner-web |     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
> > scanner-web |     at Module.require (node:internal/modules/cjs/loader:1005:19)
> > scanner-web |  ELIFECYCLE  Command failed with exit code 1.
> > scanner-web |  ELIFECYCLE  Command failed with exit code 1.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > docker 的配置如下
> > ```
> > FROM node:16.11.0-slim
> > 
> > RUN mkdir /project
> > WORKDIR /project
> > 
> > COPY . .
> > 
> > RUN npm install -g pnpm 
> > RUN pnpm add -g pnpm
> > RUN pnpm i
> > RUN pnpm add -D @vitejs/plugin-vue-jsx
> > 
> > CMD [ "pnpm", "serve"]
> > ```
> 
> FROM node:16.11.0-slim
> 
> RUN mkdir /project WORKDIR /project
> 
> COPY . .
> 
> RUN npm install -g pnpm RUN pnpm install RUN pnpm serve
> 
> CMD [ "pnpm", "serve"]

**Comment by MorphyR** [comment]
感谢🙏大佬翻牌，

我这里最终用`vs-code`的`Remote - Containers`插件构建了一个默认的`node16+typescript`环境解决了问题。
