### ISSUE TITLE
请教个问题，关于 "/@": src 的使用

### ISSUE THREAD

**Issue by Jesonhu** [xiaoxian521/vue-pure-admin#11]
当前项目为什么要用 `/@` 指向 `src`， 是在开发中遇到有些问题，才这样的吗。因为 vue2.0 默认是 `@` 指向 `src` 目录。

**Comment by xiaoxian521** [comment]
那是因为vue2.0基于webpack打包，默认配置的有别名（@），而改项目使用的是vite，需要自己配置别名

**Comment by Jesonhu** [comment]
大佬您的项目用的是 `/@` 指向 `src` 目录， 我如果改成 `@` 指向 `src` 。少个符号 `/` ，也可以对不对

**Comment by xiaoxian521** [comment]
自定义别名就是比较灵活，你想咋写都支持

**Comment by Jesonhu** [comment]
谢谢解答
