### ISSUE TITLE
关于动态国际化的建议。

### ISSUE THREAD

**Issue by paobai** [xiaoxian521/vue-pure-admin#112]
关于最近路由动态国际化的更新。
我觉得每个地方使用transformI18n(item.meta.title, item.meta.i18n)有点繁杂。
我觉得这个这部分在路由获取载入的时候处理比较好。只需要在initRouter方法里
统一遍历路由源数据。使用transformI18n, 让meta.title根据item.meta.i18n改成正确的meta.title这样使用到的地方，只用{{item.meta.title}}就好了。
以后维护起来也方便，用起来也美观。
因为改动比较大。调整的页面文件比较多。所以我没有进行修改。

**Comment by xiaoxian521** [comment]
欢迎pr 我会查看的

**Comment by hb0730** [comment]
好想法，刚才试了一下好像还OK
```
// 过滤后端传来的动态路由 重新生成规范路由
export const addAsyncRoutes = (arrRoutes: Array<RouteComponent>) => {
  if (!arrRoutes || !arrRoutes.length) return;
  arrRoutes.forEach((v: any) => {
    if (v.redirect) {
      v.component = Layout;
    } else {
      v.component = modulesRoutes[`/src/views${v.path}/index.vue`];
    }
    v.meta.title = transformI18n(v.meta.title, v.meta.i18n);
    if (v.children) {
      addAsyncRoutes(v.children);
    }
  });
  return arrRoutes;
};
const transformI18nRouters = (arrRoutes: []) => {
  if (!arrRoutes || !arrRoutes.length) return;
  arrRoutes.forEach((v: any) => {
    if (v.path === "/redirect/:path(.*)") {
      console.log(v);
    }
    if (v.meta) {
      v.meta.title = transformI18n(v.meta?.title, v.meta?.i18n);
    }

    if (v.children) {
      transformI18nRouters(v.children);
    }
  });
  return arrRoutes;
};
```

这样感觉很好维护了 👍

**Comment by laizuan** [comment]
我理解的动态国际化是可以通过后端来获取的。比如我切换语言的时候。[vben 国际化](https://github.com/anncwb/vue-vben-admin/blob/3b3f6c903a5070ec225c9ec9ab20f16d1bdc3caa/src/locales/setupI18n.ts#L40)

**Comment by xiaoxian521** [comment]
> 我理解的动态国际化是可以通过后端来获取的。比如我切换语言的时候。[vben 国际化](https://github.com/anncwb/vue-vben-admin/blob/3b3f6c903a5070ec225c9ec9ab20f16d1bdc3caa/src/locales/setupI18n.ts#L40)
目前已经支持
