### ISSUE TITLE
建议增加全局字典

### ISSUE THREAD

**Issue by ChartWay** [xiaoxian521/vue-pure-admin#121]
HeyUI组件库中有一个很好用的功能——全局字典（ https://www.heyui.top/component/config ），这个功能可以让你在任何需要使用字典的位置用{{value | dictMapping(key)}}取值，非常方便，建议借鉴过来。

**Comment by xiaoxian521** [comment]
本项目只使用element-plus不会添加别的ui库，字典属于业务层面，平台不会添加
