### ISSUE TITLE
keep alive 正确生效了吗？

### ISSUE THREAD

**Issue by chuangyi110** [xiaoxian521/vue-pure-admin#123]
除了keepAlive 还需要其他什么配置吗？store中可以查看到name ,setup语法糖页面好像无法缓存

**Comment by xiaoxian521** [comment]
请参考多级菜单页面点写法

**Comment by chuangyi110** [comment]
解决了  还是需要name 多级菜单页面是老写法 <script setup>还是要在弄一个<script>专门声明一个名字

**Comment by wyfweb1** [comment]
> 解决了 还是需要name 多级菜单页面是老写法 <script setup>还是要在弄一个<script>专门声明一个名字

这种写法不行嘛？
defineOptions({
  name: "xxx"
});
