### ISSUE TITLE
menu菜单卡顿问题

### ISSUE THREAD

**Issue by hb0730** [xiaoxian521/vue-pure-admin#128]
参照：https://vue-admin-beautiful.com/vue-admin-beautiful-element-plus/#/login 不存在卡顿

**Comment by xiaoxian521** [comment]
几率很小 复现不了 欢迎pr

**Comment by xiaoxian521** [comment]
下个element-plus版本会解决此问题

**Comment by xiaoxian521** [comment]
这种情况只会出现在副屏上
解决办法：减少动画效果换取性能
https://github.com/element-plus/element-plus/issues/4509
