### ISSUE TITLE
mock请求是不是没有生效呀？

### ISSUE THREAD

**Issue by robynluo** [xiaoxian521/vue-pure-admin#14]
![image](https://user-images.githubusercontent.com/8199379/120980523-48d12a80-c7a9-11eb-9a8e-9f1813750628.png)

**Comment by xiaoxian521** [comment]
mock线上在network下是看不到请求的
你可以在本地调试

**Comment by robynluo** [comment]
> mock线上在network下是看不到请求的
> 你可以在本地调试

你好，我是在本地启动项目呢？而且我特意加了环境变量，这是什么原因呢?

![image](https://user-images.githubusercontent.com/8199379/120981569-5e931f80-c7aa-11eb-9ba3-23127778cd75.png)

**Comment by xiaoxian521** [comment]
提供下代码仓库地址 我帮你调试

**Comment by robynluo** [comment]
> 提供下代码仓库地址 我帮你调试

我就是直接clone vue-pure-admin 的仓库代码呀，直接跑起来就不生效

**Comment by xiaoxian521** [comment]
我的是mac系统
估计是https://github.com/anncwb/vite-plugin-mock的问题，你可以尝试升级vite-plugin-mock到最新版本再试试

**Comment by robynluo** [comment]
还是不得行，我已经升级了，并且查看对照了vite-plugin-mock  示例，我空了再研究一下
![Uploading image.png…]()

**Comment by robynluo** [comment]
今天试了，mock没有问题，有可能是我电脑 ，关闭该Issue
