### ISSUE TITLE
建议加强权限模块

### ISSUE THREAD

**Issue by ChartWay** [xiaoxian521/vue-pure-admin#141]
**问题：**
1、目前的权限模块仅通过v-auth指令做处理，太过简单，稍微复杂的场景就较难满足
2、目前的权限是通过在路由中的meta.authority来标识，但是不同路由的相同标识是无差别的，比如a页面meta.authority = ['a1']，b页面没有标识a1，而b页面的a-auth="'a'"也通过验证，说明authority代表的是角色，那角色从哪里来没有明确说明。
**解决方案：**
目前比较通用的方案是：
1、用户登录后，获取用户信息、角色（多）、权限（多），并将角色、权限存入store
2、路由的meta中增加roles、permissions属性，用户判断当前用户是否具有权限
3、提供v-roles、v-permissions指令用于template，**这个无法用于v-if判断**
4、提供 hasPermissions(args:string[])用于script，**这个可以用于v-if判断**，比如审核状态，我可以对有权限的用户提供带操作功能，无权限的用户仅显示状态名称，单独v-auth是无法实现的
5、题外话：v-auth是隐藏无权限节点，不是应该移除节点比较安全吗？

**Comment by xiaoxian521** [comment]
https://github.com/xiaoxian521/vue-pure-admin/issues/106
加入第10条

**Comment by Ymonkey11** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已收到您的来信，查看后将尽快恢复，谢谢。
