### ISSUE TITLE
pure-admin-thin 安装vite-plugin-svg-icons导致项目报错isFunction is not a function

### ISSUE THREAD

**Issue by Ordinarys** [xiaoxian521/vue-pure-admin#144]
git了精简版，尝试对其进行修改，在修改的过程中并未发现错误，但是当下次重启的时候便出现了这个错误，我以为是我改的代码出现了问题，于是我重新git了新的代码，然后排查发现是vite-plugin-svg-icons依赖导致，不知道其他依赖是否会导致这个问题的出现，我曾降低vue的版本到3.2.1似乎能解决这个问题，但是大部分的样式会出现错乱并且还会有其他问题。

复现步骤
git clone xxx
npm i pnpm -g
pnpm i
pnpm add vite-plugin-svg-icons -D
pnpm run dev
然后出现这样的加载
![image](https://user-images.githubusercontent.com/54786937/145660718-78e1d0e2-a103-4cf1-8194-1492d556cc89.png)
![image](https://user-images.githubusercontent.com/54786937/145660730-6bdf6fbf-18be-41e3-bdef-066ad6ed8329.png)
最后浏览器中出现
![image](https://user-images.githubusercontent.com/54786937/145660742-6cfd6735-1464-457b-8d5e-7c9e18ef371e.png)
![image](https://user-images.githubusercontent.com/54786937/145660767-63e7571e-47b1-4f4c-99dd-806192c5c986.png)

并且我发现第一次项目启动打开页面，似乎会加载很长一段时间，这是什么原因导致的呢？

**Comment by xiaoxian521** [comment]
vite版本固定2.6.4不要往上升级

**Comment by Ordinarys** [comment]
> vite版本固定2.6.4不要往上升级

谢谢，已解决

**Comment by Ordinarys** [comment]
> > vite版本固定2.6.4不要往上升级
> 
> 谢谢，已解决

再回复一下这个问题主要原因：element-plus/icons依赖的问题，其实使用element-plus/icons-vue 即可
