### ISSUE TITLE
切换页面和展开菜单卡顿

### ISSUE THREAD

**Issue by laizuan** [xiaoxian521/vue-pure-admin#147]
**Describe the bug**
仓库演示环境，切换未打开的页面和展开菜单能感觉到很明显的卡顿。

**To Reproduce**
1、清空浏览器缓存（实际清不清空都有这个问题）
2、点系统管理和错误页面一级菜单，展开收起明细卡顿
3、未打开任何选项卡的时候进入401页面或者基础数据卡顿明显，在这些页面切换到首页也卡顿明显
4、快速来回切换系统管理和错误页面一级菜单更为明显

**Expected behavior**
流畅

**Screenshots**
![动画](https://user-images.githubusercontent.com/27326994/145739587-817388f6-8034-4f97-b440-93667dd9743e.gif)

这是使用手机拍摄的。
https://user-images.githubusercontent.com/27326994/145742243-22508c53-07ea-41bb-86c8-2bea7009b6b6.mp4

**Desktop (please complete the following information):**
![image](https://user-images.githubusercontent.com/27326994/145739536-a669882a-eb8c-41f0-969b-5bbc1ad04c81.png)
 - OS: win10
 - Browser chrome 96
 - Version 2.6

**Additional context**
奇怪的是家里的电脑是win10，chrome9XX(忘记版本了)，8G内存，加固态不会有这个问题。只有公司的电脑会（环境见上方描述）

**Comment by hb0730** [comment]
#128
