### ISSUE TITLE
如果能集成iconfont, tailwindCss, styleLint, eslint, prettier, pre-commit 就更完美了

### ISSUE THREAD

**Issue by robynluo** [xiaoxian521/vue-pure-admin#15]

**Comment by xiaoxian521** [comment]
pre-commit今天会集成
iconfont目前已经有使用了可以参考项目代码
tailwindCss前期开发是很容易，但是后期维护非常麻烦
styleLint、eslint、prettier这三个代码校验的东西后期会考虑的

**Comment by robynluo** [comment]
ok，了解了，但是我希望的iconfont， 是通过命令 比如 yarn iconfont -d <iconfont url>
从 [iconfont](https://www.iconfont.cn/) 网站复制到项目的 Font class url， 我也只是有这个想法，但自己还没有做

**Comment by xiaoxian521** [comment]
哈哈 这个想法不错 欢迎提pr

**Comment by robynluo** [comment]
我在网上参考了一下，新建了分支，已经实现了，但是分支没法提交呀？

**Comment by xiaoxian521** [comment]
你不用新建分支 直接fork 然后改完提交到主分支，然后请求合并

**Comment by robynluo** [comment]
![image](https://user-images.githubusercontent.com/8199379/121288796-7c7d9300-c916-11eb-944b-11aa1926e64c.png)
哈哈，我没有权限提交

**Comment by xiaoxian521** [comment]
所有人都可以提pr 你fork到自己项目 提交也提交到自己项目 然后合并到我这里

**Comment by robynluo** [comment]
麻烦你再看下，我这边确实提交不了
![image](https://user-images.githubusercontent.com/8199379/121289929-5d800080-c918-11eb-8f88-fdba96219f7d.png)

**Comment by xiaoxian521** [comment]
参考这个 https://github.com/gnipbao/iblog/issues/19
