### ISSUE TITLE
发布到nginx问题

### ISSUE THREAD

**Issue by zzy904494436** [xiaoxian521/vue-pure-admin#150]
发布到nginx时，env.prod 和 vite.config.ts 应该怎么修改？

**Comment by xiaoxian521** [comment]
下午我会更新文档

**Comment by zzy904494436** [comment]
按照你之前的方式配置的proxy 和 本地没问题 打包到nginx 就有问题 ，我加你技术支持了，也不回复我，我们项目昨晚上线 凌晨两点都没上去，

**Comment by zzy904494436** [comment]
现在已经更新到你现在的版本 你又更新了 兼容浏览器

**Comment by zzy904494436** [comment]
![image](https://user-images.githubusercontent.com/23206251/146131024-068ff13c-47f1-4fd3-baf2-761dfa193bd3.png)
![image](https://user-images.githubusercontent.com/23206251/146131054-0cfb95bd-3067-437d-895a-104e6cd04354.png)
上面配置开发环境 ip是服务器域名 ，
下面部署服务器上把ip换成127.0.0.1 有什么问题吗？
