### ISSUE TITLE
关于解散微信群

### ISSUE THREAD

**Issue by xiaoxian521** [xiaoxian521/vue-pure-admin#153]
本人创群之初是为了方便你们，不是为了让你们半夜@我去看看你的代码错误，也不是为了让你们天天@一下，我讲了多少遍的东西，有些东西多看看文档，多看看视频都会解决，项目持续维护，最新动态请关注github

**Comment by Cleam** [comment]
解散其实没必要，都是pure-admin用户，将群主转让保留一个交流环境还是可以的。

建群可以定一些提问规范，就跟开源项目issue规范一样，提升提问成本和水平，也可以减少没必要的回复而浪费时间。

**Comment by xiaoxian521** [comment]
> 解散其实没必要，都是pure-admin用户，将群主转让保留一个交流环境还是可以的。
> 
> 建群可以定一些提问规范，就跟开源项目issue规范一样，提升提问成本和水平，也可以减少没必要的回复而浪费时间。

所以还不如还github提问
