### ISSUE TITLE
ReChart 单页面，引用相同两个 ReChart 组件无法显示

### ISSUE THREAD

**Issue by NQLoong** [xiaoxian521/vue-pure-admin#158]
如下图，单页面引用两个相同的ReChart组件无法显示

![image](https://user-images.githubusercontent.com/34368864/146943622-cf55373d-1385-485c-b020-9fee1931787c.png)

看了下代码，应该是初始化时，用class，作为选择器，无法初始化
![image](https://user-images.githubusercontent.com/34368864/146943819-f1854cdd-bbfe-48db-b52e-f96d36a795d7.png)
可以稍微改成随机id:
![image](https://user-images.githubusercontent.com/34368864/146946037-531f1f68-5c6e-49f7-8e0c-8baab9d45702.png)
![image](https://user-images.githubusercontent.com/34368864/146946072-e1bc6b70-1a88-45b5-ba51-b7c0ef21511d.png)

**Comment by xiaoxian521** [comment]
https://github.com/xiaoxian521/vue-pure-admin/commit/c86aae7b8b4728d73ccd98c1a368a18132baadf3

**Comment by NQLoong** [comment]
感谢，本来想昨天提交代码解决的，奈何家里网络太水，只能提了下issue😂
