### ISSUE TITLE
偶发性bug：Cannot access 'formatTwoStageRoutes' before initialization

### ISSUE THREAD

**Issue by ChartWay** [xiaoxian521/vue-pure-admin#159]
在调试过程中不定时出现这个bug:Uncaught ReferenceError: Cannot access 'formatTwoStageRoutes' before initialization
![image](https://user-images.githubusercontent.com/44427400/147043893-01b802e8-77f2-4a19-b2ad-844320b9b78a.png)

**Comment by xiaoxian521** [comment]
请先配置好 路由 再去调试别的

**Comment by ChartWay** [comment]
> 请先配置好 路由 再去调试别的

我用的是动态路由，这个现象是偶发的，不是必现，理论上是动态路由未加载完成就调用了这个组件出现的，那问题来了，是不是可以在动态路由加载完成后再调用对应组件呢？

**Comment by xiaoxian521** [comment]
如果可以 请提供复现例子

**Comment by Kimkow** [comment]
我这边也是出现这类的问题。是在layout文件夹下修改里面的文件。例如修改horizontal.vue，在里面加一个代码，然后保存。热更新就会出现这个报错。但是F5刷新，进去后，不会出现。只有在文件里面改东西，热更新就会出现
![image](https://user-images.githubusercontent.com/22110416/148192712-8df321d9-6c28-4ae4-829b-a1e709529d0b.png)
