### ISSUE TITLE
标签清除问题

### ISSUE THREAD

**Issue by yuanguohao45** [xiaoxian521/vue-pure-admin#16]
![image](https://user-images.githubusercontent.com/42180636/121288033-4986cf80-c915-11eb-8a71-0231e7ccf811.png)
![image](https://user-images.githubusercontent.com/42180636/121288100-68856180-c915-11eb-8017-51c16f0556ce.png)
![image](https://user-images.githubusercontent.com/42180636/121288121-6de2ac00-c915-11eb-9bcb-1f13aae3c101.png)

**Comment by xiaoxian521** [comment]
已解决：https://github.com/xiaoxian521/vue-pure-admin/commit/8177de106b3adfcda38f2c7b958a7843a25c68e4
