### ISSUE TITLE
偶发性bug：Cannot access 'Layout' before initialization

### ISSUE THREAD

**Issue by ChartWay** [xiaoxian521/vue-pure-admin#160]
在系统调试过程中偶发性出现
![image](https://user-images.githubusercontent.com/44427400/147045065-4b1b88c9-52f0-45ed-9c3a-176a47d01da4.png)

**Comment by xiaoxian521** [comment]
这个属于你未引入组件 就直接使用

**Comment by ChartWay** [comment]
> 这个属于你未引入组件 就直接使用

我用的是动态路由，在修改组件保存后出现。

补充下截图：

![image](https://user-images.githubusercontent.com/44427400/147086418-9d972b5a-a0b3-4f6f-be0b-c16e65b3d6fe.png)
