### ISSUE TITLE
Invalid prop: type check failed for prop "activeIcon". Expected String | Object, got Function 

### ISSUE THREAD

**Issue by yinor** [xiaoxian521/vue-pure-admin#161]
最新代码支持暗黑模式，升级后REICON组件后，进入到首页就会有这个错误提示

**Comment by yinor** [comment]
Invalid prop: type check failed for prop "inactiveIcon". Expected String | Object, got Function 
Invalid prop: type check failed for prop "activeIcon". Expected String | Object, got Function
{name: 'zh-cn', el: {…}}

**Comment by xiaoxian521** [comment]
下个element-plus版本解决此问题
pr: https://github.com/element-plus/element-plus/commit/fa751a6ae03305415087a9555934d187db8d7eff
