### ISSUE TITLE
Uncaught RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by yinor** [xiaoxian521/vue-pure-admin#162]
import { resetRouter } from "/@/router/utils";
在退出登录方法里调用resetRouter();会出现Uncaught RangeError: Maximum call stack size exceeded

**Comment by xiaoxian521** [comment]
并无报错，你确定是最新代码？
![image](https://user-images.githubusercontent.com/44761321/147066193-4bb2ac43-b9c9-487c-94d8-26e9ef339415.png)

**Comment by yinor** [comment]
退出登录后在次登录就会出现了
<img width="1266" alt="截屏2021-12-22 下午9 35 24" src="https://user-images.githubusercontent.com/5127690/147101449-c68c3faa-7b60-4722-9165-8842c9acbee8.png">

**Comment by yinor** [comment]
> 并无报错，你确定是最新代码？
> ![image](https://user-images.githubusercontent.com/44761321/147066193-4bb2ac43-b9c9-487c-94d8-26e9ef339415.png)
退出登录后在次登录就会出现了

**Comment by wzc11227** [comment]
确实有这个问题，为什么close了

**Comment by xiaoxian521** [comment]
额，这个重置路由的方法已经重写了 好吧，拉最新代码
