### ISSUE TITLE
Unable to deploy in production environment

### ISSUE THREAD

**Issue by dkl78167816** [xiaoxian521/vue-pure-admin#163]
**Describe the bug**

在开发环境中通过配置代理，可以正常访问到后端。设置env.production的`VITE_PROXY_DOMAIN_REAL`后，`preview:build`后，无法访问前端，进入了Whitelabel Error Page。不知道是什么原因导致直接获取不到静态前端。

**Comment by xiaoxian521** [comment]
请提供参考代码
