### ISSUE TITLE
pnpm serve 提示找不到@zougt/some-loader-utils

### ISSUE THREAD

**Issue by zhu-yichao** [xiaoxian521/vue-pure-admin#167]
@zougt/some-loader-utils
![image](https://user-images.githubusercontent.com/40229816/147806358-d3afa9be-3a74-45f9-ad58-a080dc0dd00d.png)
> vue-pure-admin@2.7.0 dev C:\Users\dickl\Desktop\新建文件夹 (3)\vue-pure-admin
> cross-env --max_old_space_size=4096 vite

error when starting dev server:
Error: Cannot find module '@zougt/some-loader-utils'
Require stack:
- C:\Users\dickl\Desktop\新建文件夹 (3)\vue-pure-admin\node_modules\.pnpm\@zougt+some-loader-utils@1.4.1_sass@1.45.0\node_modules\@zougt\some-loader-utils\dist\packPath.js
- C:\Users\dickl\Desktop\新建文件夹 (3)\vue-pure-admin\node_modules\.pnpm\@zougt+some-loader-utils@1.4.1_sass@1.45.0\node_modules\@zougt\some-loader-utils\dist\utils.js
- C:\Users\dickl\Desktop\新建文件夹 (3)\vue-pure-admin\node_modules\.pnpm\@zougt+some-loader-utils@1.4.1_sass@1.45.0\node_modules\@zougt\some-loader-utils\dist\index.js
- C:\Users\dickl\Desktop\新建文件夹 (3)\vue-pure-admin\node_modules\.pnpm\@zougt+vite-plugin-theme-preprocessor@1.4.0_sass@1.45.0\node_modules\@zougt\vite-plugin-theme-preprocessor\dist\index.js
- C:\Users\dickl\Desktop\新建文件夹 (3)\vue-pure-admin\vite.config.ts
- C:\Users\dickl\Desktop\新建文件夹 (3)\vue-pure-admin\node_modules\.pnpm\vite@2.6.14_sass@1.45.0\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js
- C:\Users\dickl\Desktop\新建文件夹 (3)\vue-pure-admin\node_modules\.pnpm\vite@2.6.14_sass@1.45.0\node_modules\vite\dist\node\cli.js
- C:\Users\dickl\Desktop\新建文件夹 (3)\vue-pure-admin\node_modules\.pnpm\vite@2.6.14_sass@1.45.0\node_modules\vite\bin\vite.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at getCurrentPackRequirePath (C:\Users\dickl\Desktop\新建文件夹 (3)\vue-pure-admin\node_modules\.pnpm\@zougt+some-loader-utils@1.4.1_sass@1.45.0\node_modules\@zougt\some-loader-utils\dist\packPath.js:14:34)
    at createPulignParamsFile (C:\Users\dickl\Desktop\新建文件夹 (3)\vue-pure-admin\node_modules\.pnpm\@zougt+some-loader-utils@1.4.1_sass@1.45.0\node_modules\@zougt\some-loader-utils\dist\utils.js:435:66)
    at Object.configResolved (C:\Users\dickl\Desktop\新建文件夹 (3)\vue-pure-admin\node_modules\.pnpm\@zougt+vite-plugin-theme-preprocessor@1.4.0_sass@1.45.0\node_modules\@zougt\vite-plugin-theme-preprocessor\dist\index.js:150:51)
    at C:\Users\dickl\Desktop\新建文件夹 (3)\vue-pure-admin\node_modules\.pnpm\vite@2.6.14_sass@1.45.0\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:68353:127
    at Array.map (<anonymous>)
    at resolveConfig (C:\Users\dickl\Desktop\新建文件夹 (3)\vue-pure-admin\node_modules\.pnpm\vite@2.6.14_sass@1.45.0\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:68353:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async createServer (C:\Users\dickl\Desktop\新建文件夹 (3)\vue-pure-admin\node_modules\.pnpm\vite@2.6.14_sass@1.45.0\node_modules\vite\dist\node\chunks\dep-e0fe87f8.js:66702:20)
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Command failed with exit code 1.

**Comment by zhu-yichao** [comment]
尝试过删除node_module 重新pnpm install还是如此

**Comment by xiaoxian521** [comment]
你做了什么操作？

**Comment by xiaoxian521** [comment]
拉下最新代码 继续你的操作 看看还有问题吗

**Comment by zhu-yichao** [comment]
> 你做了什么操作？

就是git clone 
然后安装pnpm
pnpm install
pnpm serve 
现在更新了还是不行

**Comment by zhu-yichao** [comment]
> 拉下最新代码 继续你的操作 看看还有问题吗

我还去gitee上 clone一份下来同样的报错

**Comment by zhu-yichao** [comment]
![image](https://user-images.githubusercontent.com/40229816/147807181-13a742e3-3a8d-4838-908e-f5345f47d215.png)
完整的报错信息

**Comment by xiaoxian521** [comment]
node npm版本提供下

**Comment by zhu-yichao** [comment]
> node npm版本提供下

![image](https://user-images.githubusercontent.com/40229816/147807204-39489319-7015-4c0b-be7a-9116123dc381.png)

**Comment by xiaoxian521** [comment]
再重新拉取代码试试

**Comment by zhu-yichao** [comment]
![1640932854(1)](https://user-images.githubusercontent.com/40229816/147807869-084b053c-572e-4658-8920-a156d7a9d402.png)
还是不行。。。

**Comment by zhu-yichao** [comment]
> ![1640932854(1)](https://user-images.githubusercontent.com/40229816/147807869-084b053c-572e-4658-8920-a156d7a9d402.png) 还是不行。。。

我还是删掉node_module重新install的

**Comment by xiaoxian521** [comment]
下载这次这个版本的试试行不行
https://github.com/xiaoxian521/vue-pure-admin/tree/v2.6.0

**Comment by xiaoxian521** [comment]
或者执行命令
pnpm add @zougt/some-loader-utils -D

**Comment by zhu-yichao** [comment]
跑起来了

**Comment by xiaoxian521** [comment]
> 跑起来了
哪个版本？

**Comment by xiaoxian521** [comment]
> 跑起来了

哪个版本？

**Comment by zhu-yichao** [comment]
> > 跑起来了
> 
> 哪个版本？

v2.6.0

**Comment by xiaoxian521** [comment]
你用最新版本的执行下这个命令试试
pnpm add @zougt/some-loader-utils -D

**Comment by zhu-yichao** [comment]
![image](https://user-images.githubusercontent.com/40229816/147808773-d8134e17-1b70-4a20-a76e-63928726e0e4.png)

**Comment by xiaoxian521** [comment]
用2.7.0试试

**Comment by xiaoxian521** [comment]
估计是这个主题插件兼容性问题

**Comment by zhu-yichao** [comment]
> 

我试试

**Comment by zhu-yichao** [comment]
![image](https://user-images.githubusercontent.com/40229816/147808902-b914808b-a934-405a-88a2-341ef98ec011.png)
能跑起来， 打开太慢了

**Comment by xiaoxian521** [comment]
第一次慢正常 vite的预编译

**Comment by zhu-yichao** [comment]
> 正常 vite的预编译

打包后丢服务器第一次打开也会如此么

**Comment by xiaoxian521** [comment]
我说的是dev环境
这个属于打包优化 自己去了解哈
还有如果项目用这个请去精简版

**Comment by zhu-yichao** [comment]
![image](https://user-images.githubusercontent.com/40229816/147809182-50d678a2-299d-4acd-a522-c6f661345581.png)
跑起来提示sass不存在

**Comment by zhu-yichao** [comment]
> 

2.7版本按照你的命令pnpm add @zougt/some-loader-utils -D
可以跑起来，但是
![image](https://user-images.githubusercontent.com/40229816/147809643-d2402ee8-ae6d-4edd-8975-1b0d6a136c71.png)
提示sass找不到了。。。。

**Comment by xiaoxian521** [comment]
降低sass版本

**Comment by xiaoxian521** [comment]
这个问题属性兼容性问题出现在个别电脑上 目前我这边是没有问题的
你可以去这里提个issues：https://github.com/GitOfZGT/vite-plugin-theme-preprocessor

**Comment by zhu-yichao** [comment]
> 

确实降了版本就好了。。 开发项目要用精简版是吧

**Comment by xiaoxian521** [comment]
> 

是的 今晚会同步一版去精简版

**Comment by zhu-yichao** [comment]
> 等你同步一版我就用新版开发了

**Comment by GitOfZGT** [comment]
我无法复现这类问题，用的macOS，node 版本也是 v16.13.1 ， 通常删除node_modules、pnpm-lock.yaml、yarn.lock、package-loack.json 此类文件，再重新安装依赖。

可以用你目前的环境，试试这里选一个elment-plus 的demo，也是用的sass , 看看会不会出现同样的情况 ：https://github.com/GitOfZGT/dynamic-theme-demos

**Comment by zhu-yichao** [comment]
> 我无法复现这类问题，用的macOS，node 版本也是 v16.13.1 ， 通常删除node_modules、pnpm-lock.yaml、yarn.lock、package-loack.json 此类文件，再重新安装依赖是最新的。
> 
> 可以用你目前的环境，试试这里选一个elment-plus 的demo，也是用的sass , 看看会不会出现同样的情况 ：https://github.com/GitOfZGT/dynamic-theme-demos

![image](https://user-images.githubusercontent.com/40229816/147813481-a6813ff3-e8e4-4dca-82ab-807ea7647c43.png)
vite-element-plus-preset-theme 复现了

**Comment by zhu-yichao** [comment]
> 我无法复现这类问题，用的macOS，node 版本也是 v16.13.1 ， 通常删除node_modules、pnpm-lock.yaml、yarn.lock、package-loack.json 此类文件，再重新安装依赖是最新的。
> 
> 可以用你目前的环境，试试这里选一个elment-plus 的demo，也是用的sass , 看看会不会出现同样的情况 ：https://github.com/GitOfZGT/dynamic-theme-demos

应该是pnpm 的问题

**Comment by GitOfZGT** [comment]
开始我用windows测试同样也未重现问题，我仔细重复的看看你上面的报错截图，发现区别在于你的路径中存在中文“新建文件夹”，我设想可能是这个中文路径的问题，于是我把我的目录也改成一个“新建文件夹”，果然它报了错
![image](https://user-images.githubusercontent.com/21262000/147850195-b1d65581-56ee-4fd6-90f3-3f772f94d9d7.png)
报错的地方是我使用require.resolve()获取包的路径：
![image](https://user-images.githubusercontent.com/21262000/147850251-21dfbe5b-1aab-47b8-a57b-23241dbdb590.png)
为什么有中文路径就不行，我猜想是不是使用了{paths:[process.cwd()]}，于是我删掉这个参数：
![image](https://user-images.githubusercontent.com/21262000/147850316-bbcd0589-2b81-4804-ac68-0d883bf1b235.png)
果然不会再报这个 Error: Cannot find module '@zougt/some-loader-utils' ，但是它报另外一个：
![image](https://user-images.githubusercontent.com/21262000/147850360-cad6c77f-e7fb-4460-875d-b30c84489809.png)
这是vite的内置css插件报的错，我找到了对应的源码，也是用了require.resolve()，
![image](https://user-images.githubusercontent.com/21262000/147850418-f5e1c673-4c93-4786-b8d5-17e173e2d44c.png)
这个就不是我插件的范围内了，我随意写了 console.log(require.resolve.paths(pack.name))，打印发现存在中文乱码的路径：
![image](https://user-images.githubusercontent.com/21262000/147850459-dcc6f3a8-b8c7-45f4-b60e-d80ccd718983.png)

结论：
带有中文的目录，使用pnpm install 后，require.resolve() 带上参数{paths:[process.cwd()]} 去解析路径，会出现中文乱码导致 Error: Cannot find module

解决建议：
目录/文件名称不使用中文，或者改用npm 、 yarn安装依赖包。

**Comment by zhu-yichao** [comment]
> 

感谢大佬解惑，辛苦了

**Comment by zhu-yichao** [comment]
以后还是正儿八经命名了，以前踩过类似的坑，这次又踩了一次，长记性了

**Comment by ZedCoding** [comment]
"sass": "^1.43.4" 又是这个报错  感觉还是less好用呀
![image](https://user-images.githubusercontent.com/24578758/160970691-c09218e4-45ba-4cc4-8ec3-dbf71e45a286.png)

**Comment by xiaoxian521** [comment]
> "sass": "^1.43.4" 又是这个报错 感觉还是less好用呀
> ![image](https://user-images.githubusercontent.com/24578758/160970691-c09218e4-45ba-4cc4-8ec3-dbf71e45a286.png)

能不能好好看看文档啊 路径不要用中文 我文档强调三遍

**Comment by ZedCoding** [comment]
> 

这样的嘛  抱歉哈
