### ISSUE TITLE
SeamlessScroll.vue 组件多处使用时，只有一个能自动滚动！

### ISSUE THREAD

**Issue by xsdream** [xiaoxian521/vue-pure-admin#17]
SeamlessScroll.vue 组件在多处使用时，只有一个能自动滚动！

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/commit/808240f91b02409e371a69b51747c762a2161c5f

**Comment by xsdream** [comment]
@xiaoxian521  上周换实现了，今天看到你fixed。。。

**Comment by xiaoxian521** [comment]
实现了 可以提pr的

**Comment by xsdream** [comment]
我运用了你的组件，还是存在问题，虽然刚开始可以同时滚动，但是鼠标悬停其中一个，其他的都停止了

**Comment by xsdream** [comment]
@xiaoxian521 help

**Comment by xiaoxian521** [comment]
给每个组件一个key

**Comment by xsdream** [comment]
key给了，还是没用，你可以试试

**Comment by xiaoxian521** [comment]
代码提供一下

**Comment by xsdream** [comment]
后端在内网，你可能跑不起来，我今晚先自己看看吧

**Comment by xsdream** [comment]
![image](https://user-images.githubusercontent.com/31870384/123074421-d9666680-d449-11eb-8bdd-459d5482486c.png)

**Comment by xsdream** [comment]
我找到原因了，定时器的变量不能放到setup外面，不然他就属于全局了，那个各个组件中的定时器就会被覆盖出问题。

**Comment by xiaoxian521** [comment]
嗯嗯 你可以提供pr 哈哈

**Comment by xsdream** [comment]
不好意思，还不会提pr，我等手上忙完研究下

**Comment by xiaoxian521** [comment]
哈哈 欢迎

**Comment by xiaoxian521** [comment]
我已经改过了😊

**Comment by xsdream** [comment]
还有个问题，data数据如果是响应式的，滚动就失效了，需要监听 props.data 调用reset()

**Comment by xsdream** [comment]
开发中滚动的数据不可避免是要变化的，不可能写死在页面上
