### ISSUE TITLE
我这边也是出现这类的问题。是在layout文件夹下修改里面的文件。例如修改horizontal.vue，在里面加一个代码，然后保存。热更新就会出现这个报错。但是F5刷新，进去后，不会出现。只有在文件里面改东西，热更新就会出现

### ISSUE THREAD

**Issue by Kimkow** [xiaoxian521/vue-pure-admin#170]
我这边也是出现这类的问题。是在layout文件夹下修改里面的文件。例如修改horizontal.vue，在里面加一个代码，然后保存。热更新就会出现这个报错。但是F5刷新，进去后，不会出现。只有在文件里面改东西，热更新就会出现
![image](https://user-images.githubusercontent.com/22110416/148192712-8df321d9-6c28-4ae4-829b-a1e709529d0b.png)

_Originally posted by @Kimkow in https://github.com/xiaoxian521/vue-pure-admin/issues/159#issuecomment-1005511240_

**Comment by xiaoxian521** [comment]
提供具体代码

**Comment by Kimkow** [comment]
没有做修改。拉的是最新版本的代码。直接在文件里面加个console.log(),保存就报错了。F5刷新是没问题。热更新修改保存就出错了。在src\layout\components\sidebar\horizontal.vue这个文件
`<script setup lang="ts">
import {
  computed,
  unref,
  watch,
  nextTick,
  onMounted,
  getCurrentInstance
} from 'vue'
import { useI18n } from 'vue-i18n'
import { emitter } from '/@/utils/mitt'
import { templateRef } from '@vueuse/core'
import { algorithm } from '/@/utils/algorithm'
import { useRoute, useRouter } from 'vue-router'
import { storageSession } from '/@/utils/storage'
import { usePermissionStoreHook } from '/@/store/modules/permission'
console.log(2123)
// import { deviceDetection } from '/@/utils/deviceDetection'

import SidebarItem from './sidebarItem.vue'
import Icon from '/@/components/ReIcon/src/Icon.vue'
import Notice from '../notice/index.vue'
// import screenfull from '../screenfull/index.vue'

/* import avatars from '/@/assets/avatars.jpg'
import globalization from '/@/assets/svg/globalization.svg' */

/* const instance =
  getCurrentInstance().appContext.config.globalProperties.$storage */

const title =
  getCurrentInstance().appContext.config.globalProperties.$config?.Title

const menuRef = templateRef<ElRef | null>('menu', null)
const route = useRoute()
const router = useRouter()
const routers = useRouter().options.routes
let usename = storageSession.getItem('info')?.username
const { locale, t } = useI18n()

/* const getDropdownItemStyle = computed(() => {
  return t => {
    return {
      background: locale.value === t ? '#1b2a47' : '',
      color: locale.value === t ? '#f4f4f5' : '#000'
    }
  }
}) */

watch(
  () => locale.value,
  () => {
    //@ts-ignore
    // 动态title
    document.title = t(unref(route.meta.title))
  }
)

// 退出登录
const logout = (): void => {
  storageSession.removeItem('info')
  router.push('/login')
}

/* function onPanel() {
  emitter.emit('openPanel')
} */

const activeMenu = computed((): string => {
  const { meta, path } = route
  if (meta.activeMenu) {
    // @ts-ignore
    return meta.activeMenu
  }
  return path
})

const menuSelect = (indexPath: string): void => {
  let parentPath = ''
  let parentPathIndex = indexPath.lastIndexOf('/')
  if (parentPathIndex > 0) {
    parentPath = indexPath.slice(0, parentPathIndex)
  }
  // 找到当前路由的信息
  function findCurrentRoute(routes) {
    return routes.map(item => {
      if (item.path === indexPath) {
        // 切换左侧菜单 通知标签页
        emitter.emit('changLayoutRoute', {
          indexPath,
          parentPath
        })
      } else {
        if (item.children) findCurrentRoute(item.children)
      }
    })
  }
  findCurrentRoute(algorithm.increaseIndexes(routers))
}

function backHome() {
  router.push('/welcome')
}

function handleResize() {
  // @ts-ignore
  menuRef.value.handleResize()
}

/* // 简体中文
function translationCh() {
  instance.locale = { locale: 'zh' }
  locale.value = 'zh'
  handleResize()
}

// English
function translationEn() {
  instance.locale = { locale: 'en' }
  locale.value = 'en'
  handleResize()
} */

onMounted(() => {
  nextTick(() => {
    handleResize()
  })
})
</script>

<template>
  <div class="horizontal-header">
    <div class="horizontal-header-left" @click="backHome">
      <Icon svg :width="35" :height="35" content="team-iconlogo" />
      <h4>{{ title }}</h4>
    </div>
    <el-menu
      ref="menu"
      :default-active="activeMenu"
      unique-opened
      router
      class="horizontal-header-menu"
      mode="horizontal"
      @select="menuSelect"
    >
      <sidebar-item
        v-for="route in usePermissionStoreHook().wholeMenus"
        :key="route.path"
        :item="route"
        :base-path="route.path"
      />
    </el-menu>
    <div class="horizontal-header-right">
      
      <Notice id="header-notice" />
      
      
      
      
      
      <el-dropdown trigger="click">
        <span class="el-dropdown-link">
          
          <p>{{ usename }}</p>
        </span>
        <template #dropdown>
          <el-dropdown-menu class="logout">
            <el-dropdown-item @click="logout">
              <i class="ri-logout-circle-r-line"></i
              >{{ $t('buttons.hsLoginOut') }}</el-dropdown-item
            >
          </el-dropdown-menu>
        </template>
      </el-dropdown>
      
      <div style="padding: 10px"></div>
    </div>
  </div>
</template>

<style lang="scss" scoped>
.translation {
  .el-dropdown-menu__item {
    padding: 5px 40px !important;
  }

  .el-dropdown-menu__item:focus,
  .el-dropdown-menu__item:not(.is-disabled):hover {
    color: #606266;
    background: #f0f0f0;
  }

  .check-zh {
    position: absolute;
    left: 20px;
  }

  .check-en {
    position: absolute;
    left: 20px;
  }
}

.logout {
  max-width: 120px;

  .el-dropdown-menu__item {
    min-width: 100%;
    display: inline-flex;
    flex-wrap: wrap;
  }

  .el-dropdown-menu__item:focus,
  .el-dropdown-menu__item:not(.is-disabled):hover {
    color: #606266;
    background: #f0f0f0;
  }
}
</style>
`

**Comment by xiaoxian521** [comment]
我复现了 这可能是vite的问题 下午我升级最新的vite试试

**Comment by xiaoxian521** [comment]
solve: https://github.com/xiaoxian521/vue-pure-admin/blob/main/vite.config.ts#L95

**Comment by Kimkow** [comment]
> solve: https://github.com/xiaoxian521/vue-pure-admin/blob/main/vite.config.ts#L95

vite-plugin-full-reload这个插件，试过了，还是没啥效果，还是报错。后面更换成vite-plugin-live-reload这个插件，才实现效果。具体用法如下图
![image](https://user-images.githubusercontent.com/22110416/148581567-7a76f1e1-316c-44a5-b59c-93b0dd0be94c.png)

**Comment by xiaoxian521** [comment]
啊 我mac上没问题啊

**Comment by Kimkow** [comment]
> 啊 我mac上没问题啊

可能window才出现这问题。不管怎么说，总体上解决了。感谢！

**Comment by xiaoxian521** [comment]
该问题已经解决 fix: https://github.com/xiaoxian521/vue-pure-admin/commit/5efeb28eb31be85233b43fec49262db4330ee6da
