### ISSUE TITLE
关于项目打包清除console.log

### ISSUE THREAD

**Issue by welove42** [xiaoxian521/vue-pure-admin#171]
**Describe the bug**
项目打包清除console的插件未生效

**To Reproduce**
我这边直接拷贝精简版，在login.vue下console.log，打包之后console还在

**Expected behavior**
预期打包之后console能清除

**Screenshots**
![Uploading image.png…]()

**Comment by xiaoxian521** [comment]
目前并没有内置打包清除console的插件，不过这是个不错的需求 有空我会加上

**Comment by xiaoxian521** [comment]
我调查了一下发现babel-plugin-transform-remove-console不支持vite版本

**Comment by xiaoxian521** [comment]
你可以在精简版安装插件`pnpm add vite-plugin-remove-console -D`，即可解决你的问题
插件地址：https://github.com/xiaoxian521/vite-plugin-remove-console
![image](https://user-images.githubusercontent.com/44761321/148484884-e7b48666-2cbb-4d09-aa3c-ff0489586e7e.png)

**Comment by welove42** [comment]
感谢老哥
