### ISSUE TITLE
Hamburger 開闔卡頓

### ISSUE THREAD

**Issue by alanyulun** [xiaoxian521/vue-pure-admin#173]
**Describe the bug**
Hamburger 於chrome瀏覽器上開闔卡頓，sidebar資料量越多狀況越明顯。

**Screenshots**
![lag_chrome](https://user-images.githubusercontent.com/42028672/148487372-489b7762-fd70-43ed-954e-3c397aedce05.gif)

**Desktop (please complete the following information):**
 - Browser chrome

**Comment by xiaoxian521** [comment]
https://github.com/xiaoxian521/vue-pure-admin/issues/147
