### ISSUE TITLE
1.vxe-table筛选图标不能变色 2. 路由扫描vue文件问题

### ISSUE THREAD

**Issue by habaoyf** [xiaoxian521/vue-pure-admin#175]
**Describe the bug**
1.vxe-table筛选图标不能变色
2. 路由扫描vue文件问题

**To Reproduce**
1.vxe-table列头筛选，图标不能变颜色,如图里面的类别1
2. 路由扫描vue文件问题：router/utils.js里面的扫描应该改成筛选Index
const modulesRoutes = import.meta.glob("/src/sage/views/*/*/index.{vue,tsx}");
如果不限定，会把目录里面的其他组件也扫描进来，造成混乱
![image](https://user-images.githubusercontent.com/45748106/148710165-00e2a94b-03c0-4e8d-8d31-03a51b365f8e.png)

**Comment by xiaoxian521** [comment]
对于问题1 主题改变的时候我并没有改变vxe的主题
对于问题2 扫描肯定是扫描全部啊 你路由对应指定啊
