### ISSUE TITLE
子菜单内容项较少时，展开/收起动画有明显卡顿

### ISSUE THREAD

**Issue by yatoku** [xiaoxian521/vue-pure-admin#176]
如题

**Comment by xiaoxian521** [comment]
https://pure-admin-doc.vercel.app/pages/f8dc77/#%E5%88%87%E6%8D%A2%E9%A1%B5%E9%9D%A2%E5%92%8C%E5%B1%95%E5%BC%80%E8%8F%9C%E5%8D%95%E5%8D%A1%E9%A1%BF

**Comment by xiaoxian521** [comment]
"element-plus": "1.3.0-beta.2"版本menu做了优化 让我们等ep正式版吧
