### ISSUE TITLE
在QQ浏览器上访问演示地址报错

### ISSUE THREAD

**Issue by uoyoCsharp** [xiaoxian521/vue-pure-admin#177]
**Describe the bug**

在最新版本的QQ浏览器上访问演示地址 ( http://yiming_chang.gitee.io/manages )，停留在Loading界面。

控制台报错：

```
Uncaught ReferenceError: globalThis is not defined
    at vendor.df34978e.js:5
```

QQ浏览器版本：

```
QQ浏览器10.8.4 (4554)
Chromium70.0.3538.25 \IE11.789.19041.0
```

**Comment by xiaoxian521** [comment]
https://github.com/vueuse/vueuse/pull/1133
让我们等ep稳定版本 不推荐qq浏览器等国产浏览器
