### ISSUE TITLE
平台每次刷新都加载好慢

### ISSUE THREAD

**Issue by shystartree** [xiaoxian521/vue-pure-admin#178]
Describe the bug

刚刚下载的v2.8.0，代码还没改过，每次重新打开页面都要等几分钟，请问是什么原因呢？
![image](https://user-images.githubusercontent.com/14055622/150747395-d4dc8e44-beb0-448f-8b78-57a26588be5d.png)
估计是每次打开都要重新请求这些资源文件导致的
![image](https://user-images.githubusercontent.com/14055622/150748396-ccaab8dd-f890-4e1b-a47a-56846c97e43a.png)

之前用的v2.1.0旧版本，也只是第一次加载慢而已，加载好后，每次刷新都挺快的。
是新版本需要设置什么缓存之类的吗？

**Comment by xiaoxian521** [comment]
清理下缓存吧 不能复现你的情况

**Comment by xiaoxian521** [comment]
最新版本是2.8.5 项目用精简版 会少很多包 加载会快

**Comment by xiaoxian521** [comment]
我又分析了一下 发现加载图标资源占很多空间，v2.8.6版本会将一些图标库迁移到`iconify`，比如`remixicon`这个就占了2MB
请关注v2.8.6版本

**Comment by xiaoxian521** [comment]
https://github.com/xiaoxian521/pure-admin-thin/releases/tag/v2.9.0
