### ISSUE TITLE
能建个QQ交流群吗？

### ISSUE THREAD

**Issue by lonerwolf** [xiaoxian521/vue-pure-admin#18]
RT

**Comment by xiaoxian521** [comment]
平时不用qq
已加微信交流群：https://camo.githubusercontent.com/fbb59080d50661ca142e7f414b7ac3a60a37e25d55735ce3ea7245cdd5783763/687474703a2f2f79696d696e675f6368616e672e67697465652e696f2f6d616e616765732f7765636861742e6a7067

**Comment by zhangdaba** [comment]
加不了么？
