### ISSUE TITLE
路由404会被重复push

### ISSUE THREAD

**Issue by qq1063823095** [xiaoxian521/vue-pure-admin#181]
**Describe the bug**

路径 \src\router\utils.ts 中的以下代码
```
      router.addRoute({
        path: "/:pathMatch(.*)",
        redirect: "/error/404"
      });
```
会被重复添加。

**To Reproduce**
登录后退出，再次登录（反复循环此操作即可复现）

**Expected behavior**
路由可以去重

**Screenshots**
![无标题](https://user-images.githubusercontent.com/39073123/152482057-f5057820-e86e-40a5-83e8-87e61d8f44d4.png)

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome
 - Version 最新版

**Smartphone (please complete the following information):**
nothing

**Additional context**
nothing

**Comment by xiaoxian521** [comment]
无法复现
<img width="842" alt="image" src="https://user-images.githubusercontent.com/44761321/152629380-b704a463-d4fc-4134-b9bf-f3a27e902085.png">

温馨提示：退出登陆一般需要[重置路由](https://pure-admin-doc.vercel.app/pages/782b6e/#%E9%87%8D%E7%BD%AE%E8%B7%AF%E7%94%B1-%E4%B8%BB%E8%A6%81%E7%94%A8%E4%BA%8E%E7%94%A8%E6%88%B7%E8%A7%92%E8%89%B2%E5%88%87%E6%8D%A2)

**Comment by qq1063823095** [comment]
您的截图中，获取routes的方式貌似不太一样，请看以下截图
![image](https://user-images.githubusercontent.com/39073123/152641387-ccb531de-684a-4fee-a83b-e2975594bee4.png)
![image](https://user-images.githubusercontent.com/39073123/152641397-e56122e7-075b-437d-a959-47ce8dd4babf.png)

**Comment by qq1063823095** [comment]
并且在退出登录时，对路由进行重置，出现了致命的错误

![image](https://user-images.githubusercontent.com/39073123/152641899-5c622f0a-633c-4b5c-8b72-e0b277c25540.png)
![image](https://user-images.githubusercontent.com/39073123/152641919-0a46b0a8-79dc-48bf-a7e8-9afd5f9d18c9.png)
