### ISSUE TITLE
Unable to parse color from string "409EFF"

### ISSUE THREAD

**Issue by rich1e** [xiaoxian521/vue-pure-admin#183]
报错截图：
![image](https://user-images.githubusercontent.com/29914689/153183211-4d891606-201b-48be-9787-717fad67f7a1.png)

报错代码：
![image](https://user-images.githubusercontent.com/29914689/153183442-92e975dd-de2b-4447-9449-959276fcfc47.png)

修复方法：

![image](https://user-images.githubusercontent.com/29914689/153183731-325dbb18-23ac-4633-ae99-7a26b18a126c.png)

**Comment by xiaoxian521** [comment]
方便来个pr吗

**Comment by rich1e** [comment]
> 方便来个pr吗

ok，回家用自己的电脑。
