### ISSUE TITLE
页面动画卡顿

### ISSUE THREAD

**Issue by leecervan** [xiaoxian521/vue-pure-admin#186]
在demo页面阅览以及本地服务启动，都感到明显的卡顿，请问是什么原因？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by xiaoxian521** [comment]
> 在demo页面阅览以及本地服务启动，都感到明显的卡顿，请问是什么原因？
> 
> Sent from [PPHub](https://apps.apple.com/cn/app/id1314212521)

用精简版就行 https://github.com/xiaoxian521/pure-admin-thin

**Comment by xiaoxian521** [comment]
https://github.com/xiaoxian521/vue-pure-admin/issues/128
