### ISSUE TITLE
Vxe-table图标不显示

### ISSUE THREAD

**Issue by habaoyf** [xiaoxian521/vue-pure-admin#188]
**Describe the bug**
Vxe-table图标不显示
**To Reproduce**
![捕获](https://user-images.githubusercontent.com/45748106/154180275-990f2e72-9d47-4a1a-98fd-b5c266c1af23.PNG)

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/commit/52910602ff9351ab8ae77072cbe550b1f88e945f
经过调研vxe-table源码 发现例如下图的`iconOpen `、`iconClose `等属性只支持string图标，所以就造成vxe-table使用图标必须是string类型的，那么就需要完全引入`font-awesome`了，[完全引入代码](https://github.com/xiaoxian521/vue-pure-admin/blob/main/src/plugins/vxe-table/index.ts#L4)，当然你也可以用别的图标库
<img width="1570" alt="image" src="https://user-images.githubusercontent.com/44761321/154190362-cfa54b42-175d-4ed4-8490-20291675c383.png">
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/44761321/154190556-2d932995-3478-4ebb-9e0a-c3d9127ddebb.png">
