### ISSUE TITLE
富文本功能太有限

### ISSUE THREAD

**Issue by yuanguohao45** [xiaoxian521/vue-pure-admin#19]
![image](https://user-images.githubusercontent.com/42180636/122338971-08c13300-cf73-11eb-8333-87e73a5e7633.png)
很多时候使用富文本都是搞个图文，需要直接上传本地文件，或者直接微信截图，Ctrl+V拷贝进去，这个感觉像个文本框

**Comment by xiaoxian521** [comment]
目前富文本用的是wangeditor这个插件
