### ISSUE TITLE
router.beforeEach 方法执行两次

### ISSUE THREAD

**Issue by zss1004504439** [xiaoxian521/vue-pure-admin#191]
**Describe the bug**
进入首页后手动刷新页面
![image](https://user-images.githubusercontent.com/24915880/154491814-603217f7-7edf-46df-909a-7c7b9bc2deff.png)

**To Reproduce**
1. 登陆成功后
2. 在首页刷新页面
3. router.beforeEach 方法执行两次
4. 如上图

**Comment by zss1004504439** [comment]
所用版本V2.9

**Comment by xiaoxian521** [comment]
调用了`initRouter`方法，确保路由正确添加，不影响使用
