### ISSUE TITLE
asyncRouter在刷新的时候页面丢失

### ISSUE THREAD

**Issue by longwang1995** [xiaoxian521/vue-pure-admin#193]
1. tabs路由中去掉 `refreshRedirect` 配置
```js
{
  path: "/tabs/detail",
  name: "tabDetail",
  meta: {
    title: "",
    showLink: false,
    i18n: false,
    dynamicLevel: 3
    // refreshRedirect: "/tabs/index"
  }
}
```
2. `serverConfig.json` 配置
```json
{
  "Version": "3.0",
  "Title": "PureAdmin",
  "FixedHeader": true,
  "HiddenSideBar": false,
  "MultiTagsCache": true,
...
```

3. 效果：
点击跳转出现效果（示例中的父级出现问题）
![image](https://user-images.githubusercontent.com/33283123/155256109-0a67c6ed-a03e-4378-8b08-ac24f3213919.png)
在此路由下刷新浏览器出现效果
![image](https://user-images.githubusercontent.com/33283123/155256213-ecd4424b-8438-4708-b294-1d80276bea74.png)

**Comment by xiaoxian521** [comment]
refreshRedirect不能去
如果你需要参数的话 必须开启标签页缓存，这样我会从缓存中读取参数
<img width="293" alt="image" src="https://user-images.githubusercontent.com/44761321/155257168-922ff367-98f4-4b86-8372-6547c981a1bb.png">

**Comment by longwang1995** [comment]
```json
{
"Version": "3.0",
  "Title": "PureAdmin",
  "FixedHeader": true,
  "HiddenSideBar": false,
  "MultiTagsCache": true, // 这里有开启标签缓存
 }
```

**Comment by longwang1995** [comment]
在页面中点击开启标签页缓存之后确实刷新没有问题了，但是面包屑父级显示还是问题

**Comment by xiaoxian521** [comment]
不考虑面包屑

**Comment by xiaoxian521** [comment]
> 在页面中点击开启标签页缓存之后确实刷新没有问题了，但是面包屑父级显示还是问题

无法复现，你可以重新拉去代码观察一下，估计是你哪里该动有影响吧
<img width="751" alt="image" src="https://user-images.githubusercontent.com/44761321/155266764-755be567-6724-4aa9-9e06-f5b1803e374b.png">

**Comment by longwang1995** [comment]
> > 在页面中点击开启标签页缓存之后确实刷新没有问题了，但是面包屑父级显示还是问题
> 
> 无法复现，你可以重新拉去代码观察一下，估计是你哪里该动有影响吧
> <img width="751" alt="image" src="https://user-images.githubusercontent.com/44761321/155266764-755be567-6724-4aa9-9e06-f5b1803e374b.png">
> 

好的，这个问题我先按照规则提供一个刷新回调先，后期开发完成后再来仔细测试一下相关功能，作者大大辛苦了！
