### ISSUE TITLE
el-cascader组件props属性的TS类型报错

### ISSUE THREAD

**Issue by huohuoit** [xiaoxian521/vue-pure-admin#194]
**Describe the bug**
按照ep官方文档使用el-cascader组件时，给props属性传值，会出现ts类型分配错误
参考官方例子：https://element-plus.gitee.io/zh-CN/component/cascader.html#%E5%9F%BA%E7%A1%80%E7%94%A8%E6%B3%95
![image](https://user-images.githubusercontent.com/60650531/155271282-a716558d-24cf-4bb1-a717-09d7277bc00e.png)

**Comment by xiaoxian521** [comment]
大哥，请去element-plus提issues
