### ISSUE TITLE
关于系统优化的几个建议

### ISSUE THREAD

**Issue by lixinliA** [xiaoxian521/vue-pure-admin#197]
首先感谢作者无私的开源精神,让我们有个学习的项目.
1 frame能不能支持动态加载,比如我们的系统有几十个iframe,不可能每一个都写一个页面对应
2 目前系统在谷歌菜单打开页面会卡顿,不知道是个例还是怎么的，菜单打开也会卡顿，这个问题以前遇到过,是elementpplus的问题，只要fontsize不是18px就不会，
3 我发现我先改了主题颜色，切换黑夜模式，在关闭黑夜模式后,主题色就恢复成默认的而不是我设置的主题色了

**Comment by xiaoxian521** [comment]
从你的第三点反馈问题来说 我估计你用的版本很老了，请升级到最新的3.0，估计2、3就解决了

**Comment by xiaoxian521** [comment]
需求1已转移：https://github.com/xiaoxian521/vue-pure-admin/issues/195#issuecomment-1050418948

**Comment by lixinliA** [comment]
我用的是最新的啊，在线版的我运行也会卡顿
