### ISSUE TITLE
clone项目后运行发现element的图标未显示

### ISSUE THREAD

**Issue by zetanvi** [xiaoxian521/vue-pure-admin#20]
![image](https://user-images.githubusercontent.com/30707367/122739017-1fd68c80-d2b5-11eb-878a-f06aa851c7bc.png)

**Comment by xiaoxian521** [comment]
我这边没这个问题 可能是你那边网络比较慢 加载的慢的原因

**Comment by xiaoxian521** [comment]
问题已经修复 谢谢你的issues
