### ISSUE TITLE
路由传参 + 详情页面

### ISSUE THREAD

**Issue by Ordinarys** [xiaoxian521/vue-pure-admin#204]
路由传参似乎不支持  /index/:id 这种的传参方式吧，因为在加载路由的时候，将整个path识别成组件的路径了。

标签打开详情页，刷新就会消失，但实际项目开发中，这样的详情页应该是持久保存且路由中的参数也应该是保持的，我正在尝试解决这个问题，感觉很不友好。

**Comment by xiaoxian521** [comment]
> 路由传参似乎不支持 /index/:id 这种的传参方式吧，因为在加载路由的时候，将整个path识别成组件的路径了。
> 
> 标签打开详情页，刷新就会消失，但实际项目开发中，这样的详情页应该是持久保存且路由中的参数也应该是保持的，我正在尝试解决这个问题，感觉很不友好。

请严格按照平台规范来 使用query传参数

**Comment by Ordinarys** [comment]
@xiaoxian521 我的第二个问题证明我是采用了query传参，可我的参数依旧丢失了

**Comment by xiaoxian521** [comment]
> @xiaoxian521 我的第二个问题证明我是采用了query传参，可我的参数依旧丢失了

刷新肯定会丢失参数呀 开启标签页缓存就好了

**Comment by Ordinarys** [comment]
> > @xiaoxian521 我的第二个问题证明我是采用了query传参，可我的参数依旧丢失了
> 
> 刷新肯定会丢失参数呀 开启标签页缓存就好了
> 
> same issues：[#193 (comment)](https://github.com/xiaoxian521/vue-pure-admin/issues/193#issuecomment-1048418630)

![image](https://user-images.githubusercontent.com/54786937/156116406-50937393-574f-4244-b791-768e75438183.png)
![image](https://user-images.githubusercontent.com/54786937/156116451-1da7fab2-7bc9-4b81-9e09-8d0c8f3590b9.png)
我看了后面的部分issue可这似乎也没有解决我的问题
