### ISSUE TITLE
平台案例收集（后台语言不限、前台使用`pure-admin`）

### ISSUE THREAD

**Issue by xiaoxian521** [xiaoxian521/vue-pure-admin#206]
这里是收集用`pure-admin`平台构建的开源项目，需有配套后台，欢迎留言。会择优放到README
留言格式：项目名称+后台语言+项目地址（前台、后台地址）+预览地址

**Comment by habaoyf** [comment]
项目名称: Gerp-springboot
后台语言: Java(SpringBoot)
预览地址: https://gerp.hzsage.com.cn:8000/gerp/index.html

**Comment by qq1063823095** [comment]
> 项目名称: boot-admin 后台语言: Java(SpringBoot) 项目地址: [boot-admin/v4](https://github.com/hb0730/boot-admin) 预览地址: https://admin-v4.hb0730.com/

大哥，你这个完成度相当高，有没有.netcore版本的？

**Comment by habaoyf** [comment]
企业管理系统
预览地址：https://gerp.hzsage.com.cn:8000/gerp/index.html
用户名:test
密码:123456

**Comment by xiaoxian521** [comment]
> 企业管理系统 预览地址：https://gerp.hzsage.com.cn:8000/gerp/index.html 用户名:test 密码:123456

这里只存放开源项目哈 就是你的代码必须开源。
