### ISSUE TITLE
本地启动之后报错

### ISSUE THREAD

**Issue by mvpyb** [xiaoxian521/vue-pure-admin#21]
![image](https://user-images.githubusercontent.com/34262867/123022152-f0846480-d407-11eb-84bd-d4b96f5e8156.png)

**Comment by xiaoxian521** [comment]
打开浏览器隐私模式 再试试 可能是缓存问题

**Comment by mvpyb** [comment]
不行哦

**Comment by xiaoxian521** [comment]
你拉的是最新的代码吗 如果是 清下缓存吧

**Comment by mvpyb** [comment]
本地清除缓存之后，我用360、firefox浏览器 可以， 谷歌、qq、UC不行

**Comment by xiaoxian521** [comment]
谷歌浏览器是最新版本吗
建议的浏览器：谷歌、火狐

**Comment by xiaoxian521** [comment]
我本地和线上都没问题

**Comment by mvpyb** [comment]
版本 79.0.3945.79（正式版本） （64 位）

**Comment by mvpyb** [comment]
我访问你的线上是可以的

**Comment by xiaoxian521** [comment]
你可以定位到报错代码 截图我看看

**Comment by mvpyb** [comment]
![image](https://user-images.githubusercontent.com/34262867/123023236-a308f700-d409-11eb-9f91-37d32c3d349a.png)

**Comment by xiaoxian521** [comment]
OK 可能你那边不支持这种语法 我修改一下

**Comment by xiaoxian521** [comment]
OK 可能你那边不支持这种语法 我修改一下 12点多 发布一下

**Comment by mvpyb** [comment]
![image](https://user-images.githubusercontent.com/34262867/123023727-76a1aa80-d40a-11eb-94b3-53b57ff38f02.png)
这儿也不支持

**Comment by mvpyb** [comment]
babel 没配置es2020的语法编译支持吗

**Comment by xiaoxian521** [comment]
我这边是都支持的，我看你那边是win7版本的 谷歌浏览器
建议本地调试用火狐吧。我这边也不好做兼容 
如果你有好的意见 可以pr

**Comment by mvpyb** [comment]
好的
