### ISSUE TITLE
关于split pane的意见

### ISSUE THREAD

**Issue by mollerzhu** [xiaoxian521/vue-pure-admin#210]
**希望能够支持px的min max属性，并且支持左右两部分的分别定义**
现在好几个vue的split pane min max属性都是基于percent，并不支持px的绝对定义，这样非常……不好用。如果能支持px定义，并且两个pane都能定义min和max，就完美了。

可以参考arco.deisgn的split pane组件，它实现的也有一些问题，不过能进行px定义。
[https://arco.design/vue/component/split](https://arco.design/vue/component/split)

考虑到左右两边组件同时定义max和min的冲突问题，建议进行优先级判断比如优先判断min属性。
另外，仅支持percent和px二选一定义即可。

**Comment by mollerzhu** [comment]
哦对，arco design的split pane css写的很丑，建议参考vscode的split pane 样式

**Comment by xiaoxian521** [comment]
加入这里 https://github.com/xiaoxian521/vue-pure-admin/issues/195#issuecomment-1050418948
