### ISSUE TITLE
点击水印模块功能的时候会出现闪屏的情况（1536x721）

### ISSUE THREAD

**Issue by LJS123456789** [xiaoxian521/vue-pure-admin#211]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xiaoxian521** [comment]
并无此情况

https://user-images.githubusercontent.com/44761321/157590580-4c27fa80-5929-43df-9762-85f76ea8d3d5.mov

**Comment by LJS123456789** [comment]
1536x721  像素下，笔记本电脑 默认的显示倍率是125%  可以复现这个问题

**Comment by xiaoxian521** [comment]
> 1536x721 像素下，笔记本电脑 默认的显示倍率是125% 可以复现这个问题

不考虑支持显示器倍率缩放
不过你有解决办法很欢迎pr
