### ISSUE TITLE
页签切换路由BUG

### ISSUE THREAD

**Issue by xinuobi** [xiaoxian521/vue-pure-admin#212]
![image](https://user-images.githubusercontent.com/64522508/157608317-c2604a38-ca43-4281-b901-930771bdfce6.png)
![3H )RY)~8H (`9_A191%_K](https://user-images.githubusercontent.com/64522508/157608339-701c75d1-c49e-4a00-9878-17f0f0278c06.png)

**Comment by xiaoxian521** [comment]
请详细描述问题

**Comment by xinuobi** [comment]
由菜单跳转路由没问题，点击多个菜单item,生成页签，重现场景：上面的页签切换的时候，一次切换，router.afterEach会执行多次，并且failure报错，failure正常情况下是undefined；

**Comment by xiaoxian521** [comment]
是这个意思吗
<img width="1166" alt="image" src="https://user-images.githubusercontent.com/44761321/157610226-9b3c5b5d-b105-4cd8-91ed-659ea12fd89b.png">

**Comment by xinuobi** [comment]
是

**Comment by xinuobi** [comment]
你一两次切换可能不会出问题，但是你多点两下，问题很奇怪；如果隔几分钟不点，会有几率不会有问题，再点几次就会出问题，不稳定

**Comment by xiaoxian521** [comment]
嗯嗯 加个防抖就好了。谢谢反馈

**Comment by xiaoxian521** [comment]
这个应该是vue-router的问题了
你可以用最小仓库复现https://github.com/antfu/vitesse，切换路由它也会执行多次
提醒一点没有必要在单页面写beforeEach和afterEach，直接用vue的生命周期函数就行了
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/44761321/158096611-0149621a-adc1-4bb1-ab54-3163820e0b39.png">
