### ISSUE TITLE
是否可以导出关闭某个标签的hooks

### ISSUE THREAD

**Issue by YaoXiangMei** [xiaoxian521/vue-pure-admin#215]
**Describe the bug**
如题

**To Reproduce**
1. 打开列表页
2. 从列表页跳转到创建页，创建成功后关闭创建页，返回列表页

**Comment by xiaoxian521** [comment]
安排👀

**Comment by YaoXiangMei** [comment]
来信已经收到！！！谢谢

**Comment by zss1004504439** [comment]
`
// tag/useMultiTags.ts
import { RouteConfigs } from "../../types";
import { computed, ComputedRef, nextTick } from "vue";
import { useMultiTagsStoreHook } from "/@/store/modules/multiTags";
import { delAliveRoutes, handleAliveRoute } from "/@/router/utils";
import { useRoute, useRouter } from "vue-router";

export function useMultiTags() {
  const multiTags: ComputedRef<Array<RouteConfigs>> = computed(() => {
    return useMultiTagsStoreHook()?.multiTags;
  });
  const router = useRouter();
  const route = useRoute();

  function deleteDynamicTag(obj: any, current: any, tag?: string) {
    // 存放被删除的缓存路由
    let delAliveRouteList = [];
    const valueIndex: number = multiTags.value.findIndex((item: any) => {
      if (item.query) {
        if (item.path === obj.path) {
          return item.query === obj.query;
        }
      } else {
        return item.path === obj.path;
      }
    });

    const spliceRoute = (
      startIndex?: number,
      length?: number,
      other?: boolean
    ): void => {
      if (other) {
        useMultiTagsStoreHook().handleTags("equal", [
          {
            path: "/welcome",
            parentPath: "/",
            meta: {
              title: "menus.hshome",
              i18n: true,
              icon: "home-filled"
            }
          },
          obj
        ]);
      } else {
        // @ts-ignore
        delAliveRouteList = useMultiTagsStoreHook().handleTags("splice", "", {
          startIndex,
          length
        });
      }
    };

    if (tag === "other") {
      spliceRoute(1, 1, true);
    } else if (tag === "left") {
      spliceRoute(1, valueIndex - 1);
    } else if (tag === "right") {
      spliceRoute(valueIndex + 1, multiTags.value.length);
    } else {
      // 从当前匹配到的路径中删除
      spliceRoute(valueIndex, 1);
    }
    const newRoute = useMultiTagsStoreHook().handleTags("slice");
    if (current === route.path) {
      // 删除缓存路由
      tag
        ? delAliveRoutes(delAliveRouteList)
        : handleAliveRoute(route.matched, "delete");
      // 如果删除当前激活tag就自动切换到最后一个tag
      if (tag === "left") return;
      nextTick(() => {
        router.push({
          path: newRoute[0].path,
          query: newRoute[0].query
        });
      });
    } else {
      // 删除缓存路由
      tag ? delAliveRoutes(delAliveRouteList) : delAliveRoutes([obj]);
      if (!multiTags.value.length) return;
      const isHasActiveTag = multiTags.value.some(item => {
        return item.path === route.path;
      });
      !isHasActiveTag &&
        router.push({
          path: newRoute[0].path,
          query: newRoute[0].query
        });
    }
  }
  return { deleteDynamicTag };
}

`

**Comment by xiaoxian521** [comment]
已添加：https://github.com/xiaoxian521/vue-pure-admin/commit/5e8723a031923e79f507e5a17151d3bd88a51523
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/44761321/161416935-4623e33e-e1b7-484c-af06-b5e8b4309430.png">

**Comment by YaoXiangMei** [comment]
来信已经收到！！！谢谢

**Comment by YaoXiangMei** [comment]
来信已经收到！！！谢谢
