### ISSUE TITLE
标签页操作不能使用keepAlive

### ISSUE THREAD

**Issue by KwokBy** [xiaoxian521/vue-pure-admin#218]
能否支持在路由切换使用路由缓存

**Comment by KwokBy** [comment]
在tabs/detail加了keepAlive：true，但是切换标签页不会触发onActivated，onDeactivated依旧触发的是onMounted和onUnmounted

**Comment by xiaoxian521** [comment]
好好看文档

**Comment by xiaoxian521** [comment]
<img width="948" alt="image" src="https://user-images.githubusercontent.com/44761321/159104040-83fdd9d3-6885-48b7-9a0a-d3d5a571ceb8.png">
