### ISSUE TITLE
导航菜单性能问题

### ISSUE THREAD

**Issue by wangyuechang** [xiaoxian521/vue-pure-admin#219]
点击hamburger时，由于导航菜单数据过多(我试过数据量变少时很丝滑)，使得transition: width 0.28s;消耗性能过多，导致导航菜单折叠展开太过卡顿(大大目前的导航数据就比较卡顿了)。
是否使用let fragment = document.createDocumentFragment()重新写一下el-menu组件，达到点击hamburger时导航菜单的展开折叠丝滑一些

**Comment by xiaoxian521** [comment]
不会重构el-menu

**Comment by wangyuechang** [comment]
这个卡顿有办法解决嘛

**Comment by xiaoxian521** [comment]
对于卡顿只会出现在副屏和性能差的电脑 https://github.com/xiaoxian521/vue-pure-admin/issues/128

**Comment by wangyuechang** [comment]
> 对于卡顿只会出现在副屏和性能差的电脑 #128

![image](https://user-images.githubusercontent.com/75410227/159210383-a251b9a3-9ce8-4af6-97c4-d43d88ea4e11.png)

**Comment by xiaoxian521** [comment]
那就没办法了 并不是我平台的问题

**Comment by wangyuechang** [comment]
> 那就没办法了 并不是我平台的问题

那只能我自己重写一个了，因为现在在我电脑上确实很卡，但是我电脑配置还是不错的

**Comment by wangyuechang** [comment]
[

https://user-images.githubusercontent.com/75410227/159210970-6dafafee-8c8b-43fa-aad2-6ed6fc3598bb.mp4

](url)

**Comment by xiaoxian521** [comment]
> > 那就没办法了 并不是我平台的问题
> 
> 那只能我自己重写一个了，因为现在在我电脑上确实很卡，但是我电脑配置还是不错的

说实话，这个问题我们调查过。之前卡顿情况比现在还严重，只从我把菜单的图标不在使用ep的图标后，而换成`@iconify/vue`后，卡顿现象明显减少。但是ep的menu本身还是自带那个展开、折叠的图标的，如果你要重写，可以把ep的menu图标全部删除，看看到底是不是图标问题。ep的menu写法在性能上我们对比过ant-design，其实都一样，所以原因可能出现在ep的图标那里，这是最后一种猜测

**Comment by wangyuechang** [comment]
好的，我试试，感谢大佬！！！

**Comment by xiaoxian521** [comment]
请看下这个问题
<img width="854" alt="image" src="https://user-images.githubusercontent.com/44761321/159211574-e0e5e578-a9f5-4354-91e1-e134762d5dc1.png">

**Comment by wangyuechang** [comment]
> 请看下这个问题 <img alt="image" width="854" src="https://user-images.githubusercontent.com/44761321/159211574-e0e5e578-a9f5-4354-91e1-e134762d5dc1.png">

不会卡

**Comment by wangyuechang** [comment]
我刚刚试了，把图标的代码注释掉，确实变流畅了，我原来还以为是导航数据过多的问题

**Comment by xiaoxian521** [comment]
> 

你是把我代码里面的图标注释了，还是把ep源码的图标注释了啊

**Comment by wangyuechang** [comment]
> > 
> 
> 你是把我代码里面的图标注释了，还是把ep源码的图标注释了啊

把你代码里的图标注释了
![image](https://user-images.githubusercontent.com/75410227/159212128-d2cd209f-db1f-4b25-a88e-da64aed5f26a.png)

**Comment by xiaoxian521** [comment]
你这么改试试
<img width="858" alt="image" src="https://user-images.githubusercontent.com/44761321/159212376-0a8a80f4-de35-4f64-8eb9-4d3820d33c7c.png">

**Comment by wangyuechang** [comment]
> 请看下这个问题 <img alt="image" width="854" src="https://user-images.githubusercontent.com/44761321/159211574-e0e5e578-a9f5-4354-91e1-e134762d5dc1.png">

![159211574-e0e5e578-a9f5-4354-91e1-e134762d5dc1_极速看图](https://user-images.githubusercontent.com/75410227/159212561-1905a4f9-662c-49ca-8460-8c3bde1dff71.png)

**Comment by xiaoxian521** [comment]
> 你这么改试试 <img alt="image" width="858" src="https://user-images.githubusercontent.com/44761321/159212376-0a8a80f4-de35-4f64-8eb9-4d3820d33c7c.png">

你按照这个改一下试试

**Comment by wangyuechang** [comment]
> > 你这么改试试 <img alt="image" width="858" src="https://user-images.githubusercontent.com/44761321/159212376-0a8a80f4-de35-4f64-8eb9-4d3820d33c7c.png">
> 
> 因为我电脑复现不了，你按照这个改一下试试

换了确实不卡了

**Comment by xiaoxian521** [comment]
> > > 你这么改试试 <img alt="image" width="858" src="https://user-images.githubusercontent.com/44761321/159212376-0a8a80f4-de35-4f64-8eb9-4d3820d33c7c.png">
> > 
> > 
> > 因为我电脑复现不了，你按照这个改一下试试
> 
> 换了确实不卡了

ok，我今晚看看把el-icon这个都去了，发个版本。

**Comment by wangyuechang** [comment]
这是效果，你看一下

Uploading QQ录屏20220321141425.mp4…

**Comment by xiaoxian521** [comment]
> 

你好像没传上来 直接把视频拖到框里就行了

**Comment by wangyuechang** [comment]
这是效果，你看一下

https://user-images.githubusercontent.com/75410227/159213054-008a76a1-6026-4fae-8938-9ec8d7524839.mp4

**Comment by wangyuechang** [comment]
@xiaoxian521 效果可以吧

**Comment by xiaoxian521** [comment]
> 这是效果，你看一下
> 
>  QQ.20220321141425.mp4

OK，的确是el-icon组件的问题。谢谢帮我们定位到问题❤️

**Comment by wangyuechang** [comment]
> > 这是效果，你看一下
> > QQ.20220321141425.mp4
> 
> OK，的确是el-icon组件的问题。谢谢帮我们定位到问题❤️

我收获也很大，互帮互助，共同进步！

**Comment by xiaoxian521** [comment]
@wangyuechang 嗨，我修改了menu，可以帮我试试还卡不卡呢
代码在这个分支https://github.com/xiaoxian521/vue-pure-admin/tree/perf/menu

**Comment by wangyuechang** [comment]
> @wangyuechang 嗨，我修改了menu，可以帮我试试还卡不卡呢 代码在这个分支https://github.com/xiaoxian521/vue-pure-admin/tree/perf/menu

好的，稍等

**Comment by wangyuechang** [comment]
还是卡的，我看了一下，代码并没有改
![image](https://user-images.githubusercontent.com/75410227/159224506-77cd179f-24a9-4a9d-910d-bcffb85a4c4d.png)

**Comment by xiaoxian521** [comment]
改了呀 你要拉perf/menu分支的代码哦
https://github.com/xiaoxian521/vue-pure-admin/blob/perf/menu/src/layout/components/sidebar/sidebarItem.vue#L151

**Comment by wangyuechang** [comment]
> 改了呀 你要拉perf/menu分支的代码哦 https://github.com/xiaoxian521/vue-pure-admin/blob/perf/menu/src/layout/components/sidebar/sidebarItem.vue#L151

哦哦，我拉错了

**Comment by wangyuechang** [comment]
我拉不下来
![image](https://user-images.githubusercontent.com/75410227/159225976-70df12dd-4acc-4476-ad89-c0d96e3a8f57.png)

**Comment by xiaoxian521** [comment]
直接下载吧
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/44761321/159226089-a0a817f4-fd63-4e72-adb4-89452413c850.png">

**Comment by xiaoxian521** [comment]
> 我拉不下来 ![image](https://user-images.githubusercontent.com/75410227/159225976-70df12dd-4acc-4476-ad89-c0d96e3a8f57.png)

建议路径不要用中文哦 可能造成乱码问题

**Comment by wangyuechang** [comment]
比之前好，但感觉还是不够丝滑

https://user-images.githubusercontent.com/75410227/159227602-adf406bc-2438-4ceb-b3c9-a7b46ac74077.mp4

**Comment by xiaoxian521** [comment]
你加下我微信吧 拉你进群聊

**Comment by xiaoxian521** [comment]
菜单本来收起就有加动画了 改完后看起来不卡了
https://github.com/xiaoxian521/vue-pure-admin/blob/main/src/style/sidebar.scss#L22
