### ISSUE TITLE
element css被多次导入

### ISSUE THREAD

**Issue by fire17643** [xiaoxian521/vue-pure-admin#222]
![image](https://user-images.githubusercontent.com/10335328/159836641-cbec1b06-32de-4f9b-9a43-8a9b7cdc1933.png)
几乎所有的element样式都被多次（2-3次）导入到多个不同文件；
开始以为自己写法有问题，看了下pure官网demo也是有这个问题

**Comment by xiaoxian521** [comment]
因为平台有多种主题模式，所以样式会被覆盖，这无任何影响

**Comment by fire17643** [comment]
和主题配置没关系啊，你看下打包后的文件就知道了，不要太草率了事

**Comment by fire17643** [comment]
有2个css文件和一个style里的样式一模一样，就是一堆相同的样式代码
