### ISSUE TITLE
本地运行的时候,加载会很慢,我电脑配置不低的![image](https://user-images.githubusercontent.com/26704146/157613817-9c2b8051-1b7c-4a65-b889-b18ba900b4c5.png)

### ISSUE THREAD

**Issue by Anco-ha** [xiaoxian521/vue-pure-admin#223]
![image](https://user-images.githubusercontent.com/26704146/157613817-9c2b8051-1b7c-4a65-b889-b18ba900b4c5.png)
启动后，打开页面会出现大量[vite] Failed to load source map for xxxx，此时页面一直在加载状态

_Originally posted by @WebRookieSyb in https://github.com/xiaoxian521/vue-pure-admin/issues/195#issuecomment-1063759863_

**Comment by xiaoxian521** [comment]
等vite2.9.0正式版
