### ISSUE TITLE
【需求】登录界面-登录方式优化

### ISSUE THREAD

**Issue by juukee** [xiaoxian521/vue-pure-admin#224]
在实际项目中，大部分会用到多种方式登录，比如微信登录 qq登录，是否可以优化一下登录界面？

**Comment by xiaoxian521** [comment]
我只是提供个参考 并不会考虑那么多业务逻辑

**Comment by xiaoxian521** [comment]
加入需求

**Comment by xiaoxian521** [comment]
已重构，https://github.com/xiaoxian521/vue-pure-admin/commit/bedbf8077b06f6393535fee36f4f639a4bcf87cf
