### ISSUE TITLE
路由beforeEach中，initRouter从后台返回结果存在响应间隔，会导致前端空白页

### ISSUE THREAD

**Issue by qq1063823095** [xiaoxian521/vue-pure-admin#227]
![image](https://user-images.githubusercontent.com/39073123/160751769-65bfe1e6-52e2-4354-90e0-25d5bc43b35e.png)

### 如图标注的4个地方，其执行顺序如下：
![image](https://user-images.githubusercontent.com/39073123/160751833-c936b7d7-cd48-44b9-8d84-f683e8fdb36b.png)

### 原因
可以看到initRouter的then函数是在next之后执行的(因为initRouter走的后台异步，会存在响应间隔)，由于initRouter的then是在next后面执行的，所以此时路由还没有获取到，会有短暂的白屏；但是，当initRouter的then执行中会从后台返回的路由信息中找与之匹配的地址，如果匹配到会push过去，如果没有匹配到，则return了（此时就会一直保持在空白页面）

### 复现步骤：
1. initRouter内部设置一个sleep
2. 访问一个不存在的地址

### 在线复现：
https://admin-v4.hb0730.com/#/system/user2
（这个项目是你的平台收集案例里面的：https://github.com/hb0730/boot-admin）

### 由此引发的建议
1. 可以在每个mock api中都加一个sleep来模拟后台响应的真实情况
2. 在每个mock api中模拟后台产生异常的情况(例如500,408等)，以便更加真实的反映出实际项目中存在的问题，以及针对这些问题的异常捕获和处理

**Comment by xiaoxian521** [comment]
关于你的提议很好，但是我认为这很简单，可以按照情况自行修改哦。
initRouter从后台返回结果存在响应间隔，这是肯定的，如果后台没有返回路由，页面肯定会一直处理等待空白状态，此时可以加loading动画来解决，一般是不会出现后台路由问题的，出了问题我估计测试也会及时发现让开发去修。 所以最终我的看法是加入动画loading和请求超时来解决这个问题。

**Comment by qq1063823095** [comment]
> 

重点是访问一个不存在的地址，这会导致一直空白，再怎么刷新也是空白（参考复现步骤的第2点）

**Comment by qq1063823095** [comment]
> 关于你的提议很好，但是我认为这很简单，可以按照情况自行修改哦。 initRouter从后台返回结果存在响应间隔，这是肯定的，如果后台没有返回路由，页面肯定会一直处理等待空白状态，此时可以加loading动画来解决，一般是不会出现后台路由问题的，出了问题我估计测试也会及时发现让开发去修。 所以最终我的看法是加入动画loading和请求超时来解决这个问题。

重点是访问一个不存在的地址，这会导致一直空白，再怎么刷新也是空白（参考复现步骤的第2点）

**Comment by xiaoxian521** [comment]
> > 关于你的提议很好，但是我认为这很简单，可以按照情况自行修改哦。 initRouter从后台返回结果存在响应间隔，这是肯定的，如果后台没有返回路由，页面肯定会一直处理等待空白状态，此时可以加loading动画来解决，一般是不会出现后台路由问题的，出了问题我估计测试也会及时发现让开发去修。 所以最终我的看法是加入动画loading和请求超时来解决这个问题。
> 
> 重点是访问一个不存在的地址，这会导致一直空白，再怎么刷新也是空白（参考复现步骤的第2点）

你访问不存在会跳转404啊

**Comment by qq1063823095** [comment]
> > > 关于你的提议很好，但是我认为这很简单，可以按照情况自行修改哦。 initRouter从后台返回结果存在响应间隔，这是肯定的，如果后台没有返回路由，页面肯定会一直处理等待空白状态，此时可以加loading动画来解决，一般是不会出现后台路由问题的，出了问题我估计测试也会及时发现让开发去修。 所以最终我的看法是加入动画loading和请求超时来解决这个问题。
> > 
> > 
> > 重点是访问一个不存在的地址，这会导致一直空白，再怎么刷新也是空白（参考复现步骤的第2点）
> 
> 你访问不存在会跳转404啊

问题就是不会跳呀，因为api存在响应间隔，所以导致了beforeEach里面的执行逻辑和正常情况不是一样的顺序了

**Comment by xiaoxian521** [comment]
额，你都没进去 掉个啥

**Comment by qq1063823095** [comment]
> > > 关于你的提议很好，但是我认为这很简单，可以按照情况自行修改哦。 initRouter从后台返回结果存在响应间隔，这是肯定的，如果后台没有返回路由，页面肯定会一直处理等待空白状态，此时可以加loading动画来解决，一般是不会出现后台路由问题的，出了问题我估计测试也会及时发现让开发去修。 所以最终我的看法是加入动画loading和请求超时来解决这个问题。
> > 
> > 
> > 重点是访问一个不存在的地址，这会导致一直空白，再怎么刷新也是空白（参考复现步骤的第2点）
> 
> 你访问不存在会跳转404啊

可以访问：https://admin-v4.hb0730.com/#/system/user2  这个地址试试看，或者按照复现步骤试试

**Comment by xiaoxian521** [comment]
这个我不管，你们怎么处理是你们的事情。我考虑的不是这些

**Comment by qq1063823095** [comment]
> 这个我不管，你们怎么处理是你们的事情。我考虑的不是这些

那你考虑的是哪些嘛？我都不知道怎么提BUG了，提一个关一个，也不知道是我没解释清除还是BUG不归你管。。。

**Comment by xiaoxian521** [comment]
> > 这个我不管，你们怎么处理是你们的事情。我考虑的不是这些
> 
> 那你考虑的是哪些嘛？我都不知道怎么提BUG了，提一个关一个，也不知道是我没解释清除还是BUG不归你管。。。

说话前 先想一下我做的是开源 用你的脑子想一次问题 不要总是做个白嫖怪。还有我凭啥为你的需求服务？我欠你啥？
