### ISSUE TITLE
动态路由一些小问题

### ISSUE THREAD

**Issue by baici1** [xiaoxian521/vue-pure-admin#228]
场景：我用权限做了一个动态路由，当涉及到多级路由时候，出现问题
还原场景：
发送路由如下：
![6BR~F~5F09I46WX%)QID8OH](https://user-images.githubusercontent.com/56783919/161382441-c5615f40-7080-4cad-91bf-40c64c4e79b3.png)
报错信息如下：
![$M43288DM0YLRV)A$SBQA{O](https://user-images.githubusercontent.com/56783919/161382465-89dd58bd-63b2-4277-b16f-38fff98412f3.png)
根据报错信息走发现：
![PKFE}0CUAR6{82RKG)I2)F](https://user-images.githubusercontent.com/56783919/161382483-39416a97-f960-4241-a668-6b7f56393e4d.png)
根据自己传来的字段进行分析发现，我的二级子路由children是null，导致菜单栏出现错误，当我把子路由的菜单栏都设置成空数组时候，发现好像解决问题了。
希望这里解决一下，防止后面人再次发生问题。

场景2：当做一级路由时候出现子组件里面渲染了layout组件
发送路由信息如下：
![image](https://user-images.githubusercontent.com/56783919/161382986-cc9a6f6a-f8ef-440a-a41e-b32aa466256f.png)

出现的情况如下：
![image](https://user-images.githubusercontent.com/56783919/161382825-1546ec19-c860-4008-873f-f773109e2344.png)

望大佬解决！
谢谢大佬的框架！！！

**Comment by xiaoxian521** [comment]
按照我的文档配置路由 其他配置不做兼容

**Comment by baici1** [comment]
> 按照我的文档配置路由 其他配置不做兼容

我主要是不太能理解第二种情况发生的原因，翻了源码没有找到确切的地方，大佬可以指明一些方向吗？，我去根据自己的路由信息做一些更改

**Comment by xiaoxian521** [comment]
按照我的文档啊 看看我的配置和你的区别 我看你多了这么多配置 估计改我源码的吧 这种我不会去看的

**Comment by xiaoxian521** [comment]
https://pure-admin-doc.vercel.app/pages/782b6e/#%E4%BA%8C-%E5%90%8E%E5%8F%B0%E8%BF%94%E5%9B%9E%E8%B7%AF%E7%94%B1%E7%94%9F%E6%88%90%E8%8F%9C%E5%8D%95%E7%9A%84%E5%90%84%E7%A7%8D%E6%A0%BC%E5%BC%8F%E9%85%8D%E7%BD%AE%E5%8F%82%E8%80%83-%E4%B8%8A%E9%9D%A2%E4%BB%A3%E7%A0%81-%E4%B8%8B%E9%9D%A2%E5%AF%B9%E5%BA%94%E6%95%88%E6%9E%9C%E6%88%AA%E5%9B%BE

**Comment by baici1** [comment]
我并没有改源码，只是将获取路由api换成自己的了。打扰了大佬，抱歉！，我再看看源码和文档。十分感谢大佬提供的框架！

**Comment by xiaoxian521** [comment]
提示一点 二开要保持原有结构不变的情况下去开发
