### ISSUE TITLE
侧边栏收缩卡顿

### ISSUE THREAD

**Issue by MaybeQHL** [xiaoxian521/vue-pure-admin#229]
侧边栏收缩卡顿

**Comment by MaybeQHL** [comment]
百度到一个解决方案 不知道可行否 ：https://www.cnblogs.com/xintao/p/12876282.html

**Comment by xiaoxian521** [comment]
same: https://github.com/xiaoxian521/vue-pure-admin/issues/219

**Comment by xiaoxian521** [comment]
我就想问问你那电脑是有多烂 还能卡 我都修复过了

**Comment by MaybeQHL** [comment]
对比几个框架就你的卡，还好不准备用。就这样，再见！

**Comment by xiaoxian521** [comment]
你也配用？你个白嫖怪
