### ISSUE TITLE
项目配置栏显示不全

### ISSUE THREAD

**Issue by xu-Aurora** [xiaoxian521/vue-pure-admin#231]
**Describe the bug**
点击配置栏，在小屏幕电脑（mac13寸）上底部显示不全

**To Reproduce**
![image](https://user-images.githubusercontent.com/35291465/162165078-b396bd0f-2691-41af-ad2d-d366cf0d7cfc.png)

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/pull/232
