### ISSUE TITLE
[Bug report][scroll-item] encounter double close button

### ISSUE THREAD

**Issue by Trojan0523** [xiaoxian521/vue-pure-admin#234]
**Describe the bug**
In prview page of tab-panel, there are double close button in tab 

**To Reproduce**
click any nav-item ,and go to many page

**Expected behavior**
just one close button

**Screenshots**
<img width="568" alt="image" src="https://user-images.githubusercontent.com/44562268/162375822-e8736b3a-11bd-4fc2-816d-bd1086f284a8.png">

<img width="2195" alt="image" src="https://user-images.githubusercontent.com/44562268/162375472-b5a85d95-a09b-47fa-b25c-b2da3b5dfc65.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version 100.0.4896.75） (x86_64)

**Comment by xiaoxian521** [comment]
无法复现
