### ISSUE TITLE
左侧菜单栏卡顿

### ISSUE THREAD

**Issue by zhangzy56** [xiaoxian521/vue-pure-admin#250]
我参考了此issues(导航菜单性能问题 #219)以后，注释了sidebar Icon 的代码，然后变流畅了。如下图所示，请问是为什么呢？
![x1](https://user-images.githubusercontent.com/53873516/164676174-713fb5a7-12cd-4139-8ae1-8f4581c922ba.png)
![menu-bug](https://user-images.githubusercontent.com/53873516/164676682-2312b0d5-f3ae-4959-972f-50fff4786a1e.png)

**Comment by xiaoxian521** [comment]
不要注释整段代码，只注释下图代码试试
<img width="206" alt="image" src="https://user-images.githubusercontent.com/44761321/164677347-b70dc9e4-9b0d-4d3d-9689-16a942a44454.png">

**Comment by zhangzy56** [comment]
> 不要注释整段代码，只注释下图代码试试 <img alt="image" width="206" src="https://user-images.githubusercontent.com/44761321/164677347-b70dc9e4-9b0d-4d3d-9689-16a942a44454.png">

:class="[]" 以后 虽然 图标和文字 样式错乱了，但确实变流畅了。为啥呢 ? 不懂 ...
![bug-change](https://user-images.githubusercontent.com/53873516/164679209-e214e479-42c2-4e6f-95db-072bac157257.png)

**Comment by zhangzy56** [comment]
所以要怎么修改呢，大佬

**Comment by xiaoxian521** [comment]
> 所以要怎么修改呢，大佬

进我们的qq群 路视频 我看看效果

**Comment by xiaoxian521** [comment]
![image](https://user-images.githubusercontent.com/44761321/164679684-1bd20c2c-250e-4322-98d6-8fa64abc9099.png)
