### ISSUE TITLE
使用upload组件打包后出现n.upload.addEventListener错误

### ISSUE THREAD

**Issue by freadman** [xiaoxian521/vue-pure-admin#258]
**Describe the bug**
项目中使用了el-upload组件，以前都正常，最近不懂哪个版本开始出现错误了，而且很奇怪的是pnpm dev调试是正常的，使用pnpm build后正常打包，但是使用upload组件的时候就报错了，错误信息：
<img width="766" alt="image" src="https://user-images.githubusercontent.com/104674917/166099848-3ed91caf-d1d9-494e-988d-8977c268185f.png">

**Comment by xiaoxian521** [comment]
删除项目的所有mock设置和相关库，因为会影响实际接口请求
