### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by waterkitten** [xiaoxian521/vue-pure-admin#26]
我在用siderbar组件时候 有个很麻烦的问题
显示process err
![image](https://user-images.githubusercontent.com/56429043/125589894-7a7d88b7-f627-480b-b2c5-942b9649ffd7.png)

**Comment by xiaoxian521** [comment]
在index.html全局声明即可
https://github.com/xiaoxian521/vue-pure-admin/blob/main/index.html
<script>
    window.process = {}
</script>
