### ISSUE TITLE
精简版热更新报错

### ISSUE THREAD

**Issue by lyh0371** [xiaoxian521/vue-pure-admin#262]
直接拉取代码，修改welcome如下
```js
<template>
  <div>
    <h1>Pure-Admin-Thin</h1>

    <input type="text" v-model="inp" />
  </div>
</template>

<script lang="ts" setup>
import { ref } from "vue";

const inp = ref("");
</script>

```
报错就报错
![Uploading image.png…]()
环境：mac

**Comment by xiaoxian521** [comment]
请提供正确截图

**Comment by xiaoxian521** [comment]
无法复现
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/44761321/167236644-0380d6c7-08a3-4682-b6c0-11f20341be0c.png">
