### ISSUE TITLE
safari浏览器验证码输入不了

### ISSUE THREAD

**Issue by RemberU** [xiaoxian521/vue-pure-admin#264]
<img width="1122" alt="image" src="https://user-images.githubusercontent.com/22299428/167325139-59518e92-6cd8-414b-9aa4-4eb2088bcfca.png">
可能是element-ui的bug？？

**Comment by xiaoxian521** [comment]
不考虑safari

**Comment by xiaoxian521** [comment]
刚刚试了下 估计是element-plus的问题
你可以用这个模版测试一下  https://github.com/element-plus/element-plus-vite-starter

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/commit/4f165b93918f923196b36750f06fac2d6f512a5d
