### ISSUE TITLE
关于图标选择器

### ISSUE THREAD

**Issue by lixinliA** [xiaoxian521/vue-pure-admin#265]
我发现菜单用的都是离线图标,而图标选择那都是在线.如果想用离线图标,只能引入一个添加一个吗？有批量导入下载的离线图标库的方法吗

**Comment by xiaoxian521** [comment]
可以 具体自己研究 https://docs.iconify.design/icon-components/vue/offline.html
提醒：把图标包下载，放到自己的服务器 自己维护一套图标内网环境即可
