### ISSUE TITLE
在苹果自带桌面浏览器safari 中无法输入验证码

### ISSUE THREAD

**Issue by ryiot** [xiaoxian521/vue-pure-admin#267]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - safari 中无法输入验证码
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/78907118/168467736-0ae188aa-a7b7-47ff-a9c8-799c36487272.png">

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xiaoxian521** [comment]
same https://github.com/xiaoxian521/vue-pure-admin/issues/264

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/commit/4f165b93918f923196b36750f06fac2d6f512a5d
@ryiot  thanks for fixing this bug❤️
