### ISSUE TITLE
关于标签页操作

### ISSUE THREAD

**Issue by shmilyranran** [xiaoxian521/vue-pure-admin#269]
正常流程: 点击打开详情页按钮, 调用handleTags方法新增一个tab页
假如不走正常操作:  直接在地址栏通过修改query的方式  会出现以下情况

// 原本tab栏已有详情页打开, 会出现标签页没有命中的情况,    期望结果:  更改当前详情页或者 新生成一个详情页, 前提肯定不超过 dynamicLevel 的值
![image](https://user-images.githubusercontent.com/46252189/168548046-e043925f-2360-41e7-abba-b4983f335afc.png)

// 原本tab栏没有详情页 , 会出现没有title的tab   期望结果: 新生成一个tab
![image](https://user-images.githubusercontent.com/46252189/168548249-437df240-8955-4bbc-bc06-50f47bb1b92a.png)

开发大大辛苦了!!!!

**Comment by xiaoxian521** [comment]
这个需求是合理的
但是需要传一个固定参数，例如tagTitle代表标签名，因为直接通过地址栏输入的话，我们是不知道tag的title是什么
<img width="1153" alt="image" src="https://user-images.githubusercontent.com/44761321/168630010-5544bb55-3bb7-4df9-8923-68c9e3d6284e.png">

**Comment by xiaoxian521** [comment]
当然这里的话，可以如下图代码解决该问题
![Uploading image.png…]()

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/commit/9ca764b2a60737fec87b2e12c4bcc59629e71ada

**Comment by shmilyranran** [comment]
> fix: [9ca764b](https://github.com/xiaoxian521/vue-pure-admin/commit/9ca764b2a60737fec87b2e12c4bcc59629e71ada)
辛苦开发大大了!!!
已拉取最新代码  尝试了下   发现会出现这么一种情况

假如我在首页(tag栏没有打开任何详情页的情况下)  直接地址栏输入  /tabs/detail?id=8,   会出现无title的tag和新tag并存的情况 ,  就像下图
![image](https://user-images.githubusercontent.com/49259581/168708123-6f4519e2-f127-4ed3-923a-947d6940095a.png)

这样的话 点击关闭  有title的tag   是有异常行为的,    关了之后 空白tag会变成有title的tag

![image](https://user-images.githubusercontent.com/49259581/168708718-5d6e078f-6f1b-4f77-87b0-ccd880ebe49f.png)

**Comment by xiaoxian521** [comment]
> > fix: [9ca764b](https://github.com/xiaoxian521/vue-pure-admin/commit/9ca764b2a60737fec87b2e12c4bcc59629e71ada)
> > 辛苦开发大大了!!!
> > 已拉取最新代码  尝试了下   发现会出现这么一种情况
> 
> 假如我在首页(tag栏没有打开任何详情页的情况下) 直接地址栏输入 /tabs/detail?id=8, 会出现无title的tag和新tag并存的情况 , 就像下图 ![image](https://user-images.githubusercontent.com/49259581/168708123-6f4519e2-f127-4ed3-923a-947d6940095a.png)
> 
> 这样的话 点击关闭 有title的tag 是有异常行为的, 关了之后 空白tag会变成有title的tag
> 
> ![image](https://user-images.githubusercontent.com/49259581/168708718-5d6e078f-6f1b-4f77-87b0-ccd880ebe49f.png)

的确有这个问题。
你可以暂时用路由的h5模式。h5模式下没有此问题

**Comment by shmilyranran** [comment]
> > > fix: [9ca764b](https://github.com/xiaoxian521/vue-pure-admin/commit/9ca764b2a60737fec87b2e12c4bcc59629e71ada)
> > > 辛苦开发大大了!!!
> > > 已拉取最新代码  尝试了下   发现会出现这么一种情况
> > 
> > 
> > 假如我在首页(tag栏没有打开任何详情页的情况下) 直接地址栏输入 /tabs/detail?id=8, 会出现无title的tag和新tag并存的情况 , 就像下图 ![image](https://user-images.githubusercontent.com/49259581/168708123-6f4519e2-f127-4ed3-923a-947d6940095a.png)
> > 这样的话 点击关闭 有title的tag 是有异常行为的, 关了之后 空白tag会变成有title的tag
> > ![image](https://user-images.githubusercontent.com/49259581/168708718-5d6e078f-6f1b-4f77-87b0-ccd880ebe49f.png)
> 
> 的确有这个问题。 你可以暂时用路由的h5模式。h5模式下没有此问题

好的  辛苦了!!

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/commit/b6ed8b40d145b4b6b960b97881b80a2aab2c89fe
