### ISSUE TITLE
建议图标选择器要设置回传

### ISSUE THREAD

**Issue by freadman** [xiaoxian521/vue-pure-admin#271]
图标选择器这种组件一般作为自组建，比如表单中的某个项需要选择图标，这时候需要把选中的图标值回传父组件，就像是select组件一样，需要获取选中的值，建议增加这种回传。

**Comment by xiaoxian521** [comment]
v-model即可，后面我有空写菜单管理时会去优化

**Comment by hb0730** [comment]
![image](https://user-images.githubusercontent.com/33956166/168930758-1d054488-2671-4251-9b54-b7a8f63ff3e3.png)
