### ISSUE TITLE
Title of ReTable issue

### ISSUE THREAD

**Issue by jyzbamboo** [xiaoxian521/vue-pure-admin#272]
**Describe the bug**
当从主页点击用户管理或者角色管理时，table的title显示的是默认值：“列表” 而非设置好的title。
但如果是在用户管理页面直接按F5刷新，又会正常显示table的title "用户管理"

**To Reproduce**
1. Go to 'Home page'
2. Click on '用户管理'
3. See the title

**Expected behavior**
希望无论是跳转或者直接F5都能正常显示Title

**Additional context**
[Code.](https://github.com/xiaoxian521/vue-pure-admin/blob/6627d4724e4ba01396e308832078f5e2d6a3ad58/src/components/ReTable/src/bar.tsx#L135)

谢谢

**Comment by xiaoxian521** [comment]
这个应该很容易修复，欢迎pr

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/commit/c65940f5efae7b85a11f12ff3d2d2b18936fd4f4

**Comment by jyzbamboo** [comment]
> fix: [c65940f](https://github.com/xiaoxian521/vue-pure-admin/commit/c65940f5efae7b85a11f12ff3d2d2b18936fd4f4)

哈哈，我不知道你判断width的目的是什么，不敢乱改 :D
