### ISSUE TITLE
#号模式下已修复，但是h5模式下未修复   ”直接通过浏览器地址栏打开演示环境标签详情页，tag未加载的情况“

### ISSUE THREAD

**Issue by ryiot** [xiaoxian521/vue-pure-admin#273]
<img width="427" alt="image" src="https://user-images.githubusercontent.com/78907118/168877327-e7df7706-6d59-4173-9db5-b9541ea9a590.png">

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xiaoxian521** [comment]
有空看

**Comment by xiaoxian521** [comment]
演示环境我没部署

**Comment by ryiot** [comment]
> 演示环境我没部署

我是用最新代码在本地跑的，昨天研究了3个小时也没有解决这个问题，麻烦老哥有空了辛苦修复一下

**Comment by xiaoxian521** [comment]
额 你开启标签页缓存啊
