### ISSUE TITLE
[vite] Internal server error: /__uno.css:2:40: Unknown word

### ISSUE THREAD

**Issue by Dalegac** [xiaoxian521/vue-pure-admin#277]
**Describe the bug**
使用过程中加入新页面，路由跳转之后出现报错（多次）

**To Reproduce**
1. 新加入页面
2. router.push
3. 跳转之后出现报错
4. 页面功能仍然正常

**Expected behavior**

![e0fa410d2ea9e74c90ae050e57c3429](https://user-images.githubusercontent.com/25010602/169324727-1b6172e7-c9fc-44c1-bc54-8dc1c7259463.jpg)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows10]
 - Browser [chrome]
 - Version [101.0.4951.67（正式版本） （64 位）]

**Additional context**
不知道报错原因，第一次接触vite和vue3，项目在内网请见谅

**Comment by xiaoxian521** [comment]
无法复现
