### ISSUE TITLE
页面状态码写错了

### ISSUE THREAD

**Issue by btea** [xiaoxian521/vue-pure-admin#278]
**Describe the bug**

**To Reproduce**
这里应该是500
https://github.com/xiaoxian521/vue-pure-admin/blob/dca722cb2998313d5f3b202b59ed6b13bd4fdbfb/src/views/error/500.vue#L24

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xiaoxian521** [comment]
thank
fix: https://github.com/xiaoxian521/vue-pure-admin/commit/747e2b9c1ce88f609c33a8e3675f6c41da3d93a0#diff-24456de58368461b11da6bef2c3c54628ab5cb251f168cbbd7a1fb86d3f508a3L24
