### ISSUE TITLE
这并不是一个bug 但是模板没有问题选项~~

### ISSUE THREAD

**Issue by TLovers** [xiaoxian521/vue-pure-admin#280]
**Describe the bug**
pre-commit 里面 vsconde 报错npx 不是命令想知道大神你是怎么解决的

**To Reproduce**
没有

**Expected behavior**
没有

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xiaoxian521** [comment]
你node版本的问题，安装下图版本就行
<img width="233" alt="image" src="https://user-images.githubusercontent.com/44761321/170193007-a111ba52-c328-4bc5-b5a0-22d9f9b55017.png">
