### ISSUE TITLE
切换角色时动态路由的问题

### ISSUE THREAD

**Issue by liwilljinx** [xiaoxian521/vue-pure-admin#284]
切换角色的时候上一个角色的路由还在，要刷新页面才可以更新，退出登录的时候怎么把添加的添加的动态路由删掉呢

**Comment by ethanxueyn** [comment]
我也有这个问题，解决了吗，logout了以后reset了router，但切换角色再登录还是会添加之前角色的路由

**Comment by xiaoxian521** [comment]
用最新版

**Comment by ethanxueyn** [comment]
logout的时候使用location.assign("/#/login")强制重载解决了

**Comment by xiaoxian521** [comment]
额 刷新页面体验不好 请用最新版 多关注升级日志

**Comment by ethanxueyn** [comment]
额 我一直用的thin的最新版呀，不知道为啥我这个router在异步加载之后会把动态的路由挂到path “/” 下面作为children，然后reset会忽略“/”，然后换角色再登录的时候initRouter中会把它再找出来作为flattenRouter添加回去，可能我哪里操作有问题吧，就先这样，谢谢作者回复
