### ISSUE TITLE
关于initRouter方法返回的promise  有一直pending的情况

### ISSUE THREAD

**Issue by kr-dog** [xiaoxian521/vue-pure-admin#287]
首次进入系统是不会出现的  因为router对象还没有添加异步路由,  然而退出登录以后, 第二次进入系统,  每次遍历都进入第一个分支, 
 一直return ,   导致resolve执行不到
所以调用resolve方法的时机  是否应该考虑换个位置   不应该在map方法里调用

![image](https://user-images.githubusercontent.com/46252189/171124047-505dfa17-0250-4cce-8550-de657b32cc3a.png)

**Comment by xiaoxian521** [comment]
无法复现
请不要提一些无法复现的issues，否则可能会被block

**Comment by kr-dog** [comment]
可以在登录页面  调用处查看回调   登录进入系统再退出, 然后二次进入
![image](https://user-images.githubusercontent.com/46252189/171127423-e50a36e5-3331-494e-8f63-7284f96d3921.png)
![image](https://user-images.githubusercontent.com/46252189/171127464-413eea7b-4b07-4af1-a380-101a05177207.png)
