### ISSUE TITLE
重复使用方法 buildHierarchyTree 处理 routes

### ISSUE THREAD

**Issue by mosu1314** [xiaoxian521/vue-pure-admin#289]
https://github.com/xiaoxian521/vue-pure-admin/blob/4af50acf883954926cbd07a535ef512438bf373f/src/router/index.ts#L65

formatFlatteningRoutes 方法调动处使用buildHierarchyTree 处理 routes，同时方法内部同样使用buildHierarchyTree处理routes，

**Comment by xiaoxian521** [comment]
请不要提这些无用的issues 我没时间讲解源码
