### ISSUE TITLE
登陆后，在浏览器再打开一个窗口，还需要再次登录，而且再次登录不能重定向到上次页面

### ISSUE THREAD

**Issue by PandaGoAdmin** [xiaoxian521/vue-pure-admin#292]
登陆后，在浏览器再打开一个窗口，还需要再次登录，而且再次登录不能重定向到上次页面
![image](https://user-images.githubusercontent.com/93296511/174214126-c11a7d6c-0716-4689-9667-b875cdd5acc5.png)

**Comment by xiaoxian521** [comment]
自行修改
