### ISSUE TITLE
表格设置

### ISSUE THREAD

**Issue by DaYang816** [xiaoxian521/vue-pure-admin#293]
### 表格设置，有2个勾选项（勾选列,序号列），我想默认将勾选列给勾上，也就是默认将勾选列给放出来，要怎么才能做到我看是根据checkList去控制的但是我没法去控制这个参数去默认显示，对于需要默认显示的不是很方便

**Comment by xiaoxian521** [comment]
不属于平台问题

**Comment by DaYang816** [comment]
我自己是改了，我只想平台更好罢了，没时间就算了，谢谢回复
