### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by xu-Aurora** [xiaoxian521/vue-pure-admin#295]
![企业微信截图_16563008753779](https://user-images.githubusercontent.com/35291465/175856276-dc1b3f91-6210-4754-8cf5-7edfc434e9af.png)

**Comment by xiaoxian521** [comment]
无法复现

**Comment by xu-Aurora** [comment]
![image](https://user-images.githubusercontent.com/35291465/175858219-1c75794f-fa5d-4dee-a5fc-31b6fc74337a.png)
那这问题怎么破？

**Comment by xu-Aurora** [comment]
> ![image](https://user-images.githubusercontent.com/35291465/175858219-1c75794f-fa5d-4dee-a5fc-31b6fc74337a.png) 那这问题怎么破？

clone下来的，执行pnpm就报错了

**Comment by xu-Aurora** [comment]
> 无法复现

![image](https://user-images.githubusercontent.com/35291465/175864472-6460ad22-a243-406c-9e84-dac7fc3a275d.png)
那这问题是怎么回事，clone下来的，执行pnpm就报错了

**Comment by xiaoxian521** [comment]
看情况我猜可能是node版本和pnpm的问题 请按照文档版本要求的安装就行

**Comment by xu-Aurora** [comment]
> 看情况我猜可能是node版本和pnpm的问题 请按照文档版本要求的安装就行

我就是安装官网来的，node最新版，pnpm最新版，都是最新安装的

**Comment by xiaoxian521** [comment]
截图你的文件夹路径 我比较忙 进qq群问就行
