### ISSUE TITLE
运行后卡在加载图

### ISSUE THREAD

**Issue by LanternTi** [xiaoxian521/vue-pure-admin#296]
### 这是控制台报错
`Uncaught (in promise) TypeError: can't convert undefined to object`
![1656409864373.png](https://i-s2.328888.xyz/2022/06/28/62bacf000f03f.png)

**Comment by xiaoxian521** [comment]
看文档 浏览器已经版本

**Comment by LanternTi** [comment]
我检查了我的火狐版本为最新，并且在谷歌上测试了一遍，仍然报相同的错误

**Comment by xiaoxian521** [comment]
进qq群问
