### ISSUE TITLE
[BUG]删掉lock文件重新install后运行报错

### ISSUE THREAD

**Issue by ALI1416** [xiaoxian521/vue-pure-admin#297]
两周前还没问题，今天重新克隆的项目就报错了，报错如下：

![1](https://user-images.githubusercontent.com/39152510/176344157-07b45087-1d66-495b-b468-46dcd12eb556.png)

问题可以复现，我看昨天也有人提出相同问题，但是QQ群问没人理

**Comment by xiaoxian521** [comment]
参考这个 https://github.com/xiaoxian521/vue-pure-admin/commit/007bb0124fd8e9886f5c5bd3bf11efacea8d2c96
把responsive-storage这个库升级到最新

**Comment by xiaoxian521** [comment]
如果不想升级的话 手动改package.json的"responsive-storage": "1.0.11" 将版本固定死
