### ISSUE TITLE
[建议]标签栏新增功能

### ISSUE THREAD

**Issue by ALI1416** [xiaoxian521/vue-pure-admin#298]
- 鼠标中键关闭标签
- 拖拽标签改变顺序

以上2点功能，在浏览器的标签栏中都是有的，希望在此项目中的标签栏中也能够添加

**Comment by xiaoxian521** [comment]
很忙 不接受任何新功能

**Comment by xiaoxian521** [comment]
可以 但必须备注作者链接

**Comment by ALI1416** [comment]
好的，谢谢了

**Comment by yigehaobb** [comment]
> 好的吧，那我可以重构该项目并二次开源吗？

大佬你的github没看到修改的啊

**Comment by ALI1416** [comment]
> > 好的吧，那我可以重构该项目并二次开源吗？
> 
> 大佬你的github没看到修改的啊
不好意思，不打算重构这个项目了。重构了一部分，发现还是自己写一个全新的比较好
