### ISSUE TITLE
公告🪧

### ISSUE THREAD

**Issue by xiaoxian521** [xiaoxian521/vue-pure-admin#299]
实际项目开发，请务必使用 [精简版](https://github.com/xiaoxian521/vue-pure-admin#%E7%B2%BE%E7%AE%80%E7%89%88%E5%AE%9E%E9%99%85%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%E8%AF%B7%E7%94%A8%E7%B2%BE%E7%AE%80%E7%89%88%E6%8F%90%E4%BE%9B-%E9%9D%9E%E5%9B%BD%E9%99%85%E5%8C%96-%E5%9B%BD%E9%99%85%E5%8C%96-%E4%B8%A4%E4%B8%AA%E7%89%88%E6%9C%AC%E9%80%89%E6%8B%A9) ，完整版为了丰富演示示例，我引入了大量模块，完整版并不适合实际项目开发哦，更适合学习

目前不接受任何新功能需求！！！此公告请不要评论或留言，有问题请新开 [issues](https://github.com/xiaoxian521/vue-pure-admin/issues/new/choose)
之后要做的事情：（打勾代表已完成，反之）
- [x] 将 `element-plus` 的 `Table` 二次封装到 [@pureadmin/table](https://github.com/xiaoxian521/pure-admin-table)，提供灵活的配置项并集成到平台里
- [x] 将 `element-plus` 的 `Descriptions` 二次封装到 [@pureadmin/descriptions](https://github.com/xiaoxian521/pure-admin-descriptions)，提供灵活的配置项并集成到平台里
- [x] 将平台的大部分工具以及hooks都集中到 [@pureadmin/utils](https://xiaoxian521.github.io/pure-admin-utils-docs/)，并删除集中到这个库里的代码，减少平台体积
- [x] 重构主题色，适配 `element-plus` 暗黑模式（同时也解决了 `3.3.0` 及更低版本中同样的元素 `css` 被多次覆盖，导致样式不好调试的问题）
- [x] 重构路由重置功能
- [x] 优化路由传参（`query`、`params` 方式刷新页面不需要再开启标签页缓存也能保留参数在`url`和`标签页`上）
- [x] 使用 [tailwindcss](https://github.com/tailwindlabs/tailwindcss) 替换 [unocss](https://github.com/unocss/unocss)，`tailwindcss`更稳定
- [x] 重构权限模块，采用目前最常用的 `RBAC` （Role Based Access Control）: 基于角色的访问控制（  `用户 -> 角色 -> 权限` ）（同时也解决了 `3.5.0` 及更低版本中`token`过期后调用刷新`token`接口会无限循环的问题，同时也简化了一些函数，剔除了无用函数，优化了页面加载速度，当然我们也带来了按钮权限支持三种操作模式（组件方式判断权限、函数方式判断权限、指令方式判断权限））
- [x] 菜单图标 `icon` 支持使用在线图标

有些问题，我文档备注的都有解决办法，所以请多看看文档，面对这些文档有的`issues`和一些我觉得进群问问就能解决的基本问题，原谅我会直接关闭。

作者提供了几个 `QQ群`，请择前添加！

| <img src="https://user-images.githubusercontent.com/44761321/176385180-a50a86d5-e009-4a57-9062-3a69bce4c8aa.jpg" width="220px" height="360px" /> | <img src="https://user-images.githubusercontent.com/44761321/176385246-a41a5d48-0a23-4142-b0c9-ebb9bc6fede3.jpg" width="220px" height="360px" /> | <img src="https://user-images.githubusercontent.com/44761321/176385262-fd502d85-b155-4806-8108-bcd7da568b02.jpg" width="220px" height="360px" /> |
| :----------------------------------------------------------: | ------------------------------------------------------------ | ------------------------------------------------------------ |

对于有些朋友想用本平台二次开源的，只需要在文档中备注原作者链接就行，如果没备注，可能有 `法律风险`

作者喜欢开发有用的小组件和插件，并录制视频到 `B站`，欢迎关注：[乐于分享的程序员小铭](https://space.bilibili.com/301103230)

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/44761321/176388293-8cd35134-e66c-403c-8375-a7cc128fa5e8.png">

当然，本平台代码完全开源，但是提供免费的服务对我来说有点累，一些基本问题，你都可以进 `qq` 群和群友询问得知或者多看文档（这很重要 ‼️）。

最后，有很多人问我学习的方法。其实没啥，就是喜欢在 `Github` 看看别人的源码，当然这些源码是比较小有名气的那种😄，刚开始你肯定不适应，后面看多了，会发现还有这种写法，还有这种操作，原来这么简单。加油吧！！！

**Comment by cnyyk** [comment]
很棒的项目，
虽然还没用上，
但刚刚还是捐赠了，
表示对作者的景仰。

**Comment by cnyyk** [comment]
另外，
提一个很细节的小问题，
我也许可以创建一个 PR 来修复：
左侧图标收缩与展开时的对齐，
见下面 gif 所示，
如果能够一开始就对齐，
应该不会有左右移动的情况。

![alignment](https://user-images.githubusercontent.com/275233/176739224-f81e1d52-d252-479e-a46b-8ab14641a8a5.gif)

**Comment by xiaoxian521** [comment]
他们本身就是对齐的，顺便说一句有问题可以另开一个issues哈
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/44761321/176803758-c9d18f99-2a09-4a9d-b662-35a974db33ba.png">

**Comment by webxiu** [comment]
就这玩意还向你询问价格

**Comment by xiaoxian521** [comment]
记录：`2020年11月16` 日开始pure-admin平台相关的开发
<img width="298" alt="image" src="https://user-images.githubusercontent.com/44761321/198580104-b7f88864-470f-4470-a3b7-ef8bd3c780c6.png">

**Comment by xiaoxian521** [comment]
平台打算在 `2023`年的某月接入 [乾坤](https://github.com/umijs/qiankun)，再让 `vite` 和 `vue3` 稳定稳定吧

当然对于感兴趣的朋友可以参考下面两个示例接入 `qiankun`，平台也非常欢迎朋友们为 `pure-admin` 提供 `qiankun`版 ❤️
 
- [qiankun-demo](https://github.com/MAXLZ1/micro-app-demos/tree/main/packages/qiankun-demo)
- [vue-qiankun](https://github.com/aehyok/vue-qiankun)
