### ISSUE TITLE
报错，如何解决？？？？

### ISSUE THREAD

**Issue by zhangdaba** [xiaoxian521/vue-pure-admin#30]
index.ts:89 Uncaught TypeError: Cannot read property 'use' of undefined，
直接下载的master分支，本地vuecli4.5.13

**Comment by xiaoxian521** [comment]
本项目用vite不用vue-cli

**Comment by zhangdaba** [comment]
方便加下您的微信么？

**Comment by zhangdaba** [comment]
我使用npm run serve 直接运行的。

**Comment by xiaoxian521** [comment]
先去了解下vue3 和vite

**Comment by zhangdaba** [comment]
hao. 我先看看

**Comment by zhangdaba** [comment]
项目运行成功了，但是还是刚次啊那个错，是因为环境问题么？


  vite v2.5.0 dev server running at:

  > Local: http://localhost:3002/
  > Network: use `--host` to expose

  ready in 725ms.
