### ISSUE TITLE
build项目，vite-plugin-remove-console插件会报iconfont.js中的console错误

### ISSUE THREAD

**Issue by huohuoit** [xiaoxian521/vue-pure-admin#302]
**Describe the bug**
build项目，vite-plugin-remove-console插件会报iconfont.js中的console错误

**To Reproduce**
1. pnpm build

**Expected behavior**
build success

**Screenshots**
![image](https://user-images.githubusercontent.com/60650531/176847135-792bae00-e5fe-4b73-922d-c7d1ffa2fc0e.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Version lastest

**Additional context**
vite-plugin-remove-console: "^1.0.3"

![image](https://user-images.githubusercontent.com/60650531/176847472-58080d75-7c28-4dca-9c74-4c4388828869.png)

**Comment by xiaoxian521** [comment]
无法复习 请拉取最新代码尝试

**Comment by huohuoit** [comment]
> 

多台电脑尝试依然报错。。。

**Comment by xiaoxian521** [comment]
那你就换0.0.7版本咯 不影响

**Comment by huohuoit** [comment]
0.0.7版本可行，{ external: ["src/assets/iconfont/iconfont.js"] }也参数去掉了。
