### ISSUE TITLE
build 打包报错 FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by cnvoa** [xiaoxian521/vue-pure-admin#306]
刚刚新建项目,拉取的最新源代码,  pnpm build 打包报错

- os macos 11.5.2
- node  16.14.2
- npm    8.5.0
- pnpm  6.11.0

报错信息如下

`
mac@macdeMac-mini vue-pure-admin % pnpm build

> vue-pure-admin@3.3.0 build /Users/mac/project/dev/vue3/vue-pure-admin
> rimraf dist && cross-env vite build

vite v2.9.13 building for production...
👏欢迎使用[vue-pure-admin]，如果您感觉不错，记得点击后面链接给个star哦💖 https://github.com/xiaoxian521/vue-pure-admin
transforming (5191) node_modules/.pnpm/color-name@1.1.3/node_modules/color-name/index.jsUse of eval is strongly discouraged, as it poses security risks and may cause issues with minification
Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
✓ 5192 modules transformed.

<--- Last few GCs --->

[11787:0x7f7fcae00000]   166108 ms: Mark-sweep 2031.2 (2093.2) -> 2015.7 (2093.9) MB, 3738.2 / 0.0 ms  (average mu = 0.174, current mu = 0.193) allocation failure scavenge might not succeed
[11787:0x7f7fcae00000]   170687 ms: Mark-sweep 2031.9 (2094.2) -> 2016.3 (2094.7) MB, 3858.8 / 0.0 ms  (average mu = 0.166, current mu = 0.157) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10a04ba25 node::Abort() (.cold.1) [/Users/mac/.nvm/versions/node/v16.14.2/bin/node]
 2: 0x108d410f9 node::Abort() [/Users/mac/.nvm/versions/node/v16.14.2/bin/node]
 3: 0x108d4126f node::OnFatalError(char const*, char const*) [/Users/mac/.nvm/versions/node/v16.14.2/bin/node]
 4: 0x108ec27e7 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [/Users/mac/.nvm/versions/node/v16.14.2/bin/node]
 5: 0x108ec2783 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/Users/mac/.nvm/versions/node/v16.14.2/bin/node]
 6: 0x109063e65 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/Users/mac/.nvm/versions/node/v16.14.2/bin/node]
 7: 0x109067ead v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [/Users/mac/.nvm/versions/node/v16.14.2/bin/node]
 8: 0x10906478d v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/Users/mac/.nvm/versions/node/v16.14.2/bin/node]
 9: 0x109061cad v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/Users/mac/.nvm/versions/node/v16.14.2/bin/node]
10: 0x10906f090 v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/mac/.nvm/versions/node/v16.14.2/bin/node]
11: 0x10906f111 v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [/Users/mac/.nvm/versions/node/v16.14.2/bin/node]
12: 0x10903c1a7 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [/Users/mac/.nvm/versions/node/v16.14.2/bin/node]
13: 0x1093f3dae v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [/Users/mac/.nvm/versions/node/v16.14.2/bin/node]
14: 0x10979d879 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [/Users/mac/.nvm/versions/node/v16.14.2/bin/node]
 ERROR  Command failed with exit code 1.
`

![WX20220711-173934](https://user-images.githubusercontent.com/61954852/178235994-c30ebabf-fe20-4522-a3c2-e612a4cf9cda.png)

**Comment by xiaoxian521** [comment]
你用的nvm管理工具啊
我觉得是node的问题，无法复现

**Comment by xiaoxian521** [comment]
并非项目问题，可以尝试这个 https://blog.csdn.net/qq_41944038/article/details/110819445

**Comment by cnvoa** [comment]
是用的nvm    试过node 14 也不行
这个电脑只有8G内存, 不确定是物理内存不够, 还是代码内存泄露. 
我回去用另外一台mac 试试.

**Comment by xiaoxian521** [comment]
你可以试试这两个命令
<img width="825" alt="image" src="https://user-images.githubusercontent.com/44761321/178240504-04a6c636-87cb-45f5-91e2-507cdaa6ad8f.png">

**Comment by cnvoa** [comment]
> 你可以试试这两个命令 <img alt="图片" width="825" src="https://user-images.githubusercontent.com/44761321/178240504-04a6c636-87cb-45f5-91e2-507cdaa6ad8f.png">

这个确实可以了

**Comment by xiaoxian521** [comment]
嗯嗯 好的 使用nvm估计有坑 可以了解一下
