### ISSUE TITLE
showlink为false的异步路由，刷新后不显示

### ISSUE THREAD

**Issue by icryrainix** [xiaoxian521/vue-pure-admin#307]
**Describe the bug**
从后台获取的异步路由，如果showlink为false的，刷新后显示空白。

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xiaoxian521** [comment]
无法复现 请安装文档正确配置路由
<img width="1168" alt="image" src="https://user-images.githubusercontent.com/44761321/179440897-8fdc2b00-a3ad-4415-b249-a8a093d2a909.png">

我猜你是下面这种情况
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/44761321/179441081-748d1b25-91dd-448a-a88f-4ae73a951cc9.png">

**Comment by icryrainix** [comment]
showLink为false得路由，左边菜单栏是不显示得，这个没问题。通过router.push跳转可以正常跳转并显示，但进入该页面后进行刷新，这个页面就显示不出来，会提示路由找不到。

**Comment by xiaoxian521** [comment]
无法复现
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/44761321/179441478-c34a130c-4a0c-485d-972b-a945fd1a8563.png">

**Comment by icryrainix** [comment]
<img width="453" alt="1658115345894" src="https://user-images.githubusercontent.com/5716088/179441663-8b8590dd-ba5e-4840-87ff-2ee68658fdb1.png">
<img width="846" alt="1658115401959" src="https://user-images.githubusercontent.com/5716088/179441728-7f71a454-2ad7-4912-bab4-fbec69d672be.png">
这个时候通过router.push可以正常进入该路由，但是在该界面刷新后，界面就不能正常显示了。
<img width="612" alt="1658115477712" src="https://user-images.githubusercontent.com/5716088/179441798-1e489ef2-8541-46db-a257-4485eeaf1076.png">

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/commit/4c6acc91abe38b7d908b9206b06a5d1b21bfc10d
