### ISSUE TITLE
pureTable 国际化未生效，是我用错了吗？

### ISSUE THREAD

**Issue by Gzbox** [xiaoxian521/vue-pure-admin#309]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/21010051/179346035-296970fb-97d3-43c7-a3a3-e848fef72ea1.png">

<img width="812" alt="image" src="https://user-images.githubusercontent.com/21010051/179346018-b9213f17-7392-45a3-9247-85d1684f02c4.png">

**Comment by xiaoxian521** [comment]
不能直接使用$t 看pure文档有写

**Comment by Gzbox** [comment]
> 不能直接使用$t看纯文档有

看到了  谢谢
