### ISSUE TITLE
运行项目报错

### ISSUE THREAD

**Issue by tiaotiaohua** [xiaoxian521/vue-pure-admin#313]
![image](https://user-images.githubusercontent.com/50447702/180905761-b5696faf-c90f-4f2b-94e7-c3471da73d73.png)
![image](https://user-images.githubusercontent.com/50447702/180905841-d307a90f-6b6d-40b6-83cb-cf0572884aa5.png)
你好，我用pnpm i 可以 安装node_modules，当我运行时报第一张图错误，请问有什么好的解决办法吗，不胜感激

**Comment by xiaoxian521** [comment]
node 
pnpm 按照文档要求
