### ISSUE TITLE
自定义图标无法加载

### ISSUE THREAD

**Issue by francisxie** [xiaoxian521/vue-pure-admin#315]
![image](https://user-images.githubusercontent.com/22124363/182013130-46103b5f-9e37-4ca1-80d3-73a5eea1119c.png)
![image](https://user-images.githubusercontent.com/22124363/182013146-75c2977b-0aac-4d8d-8c23-57bfce4f34d1.png)

在vue文件或者路由icon中都无法加载

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/commit/81e86a152ce5ca617b7653dc2ce3d9889beba55f
