### ISSUE TITLE
手机版的没有菜单

### ISSUE THREAD

**Issue by xiafei114** [xiaoxian521/vue-pure-admin#319]
手机版的没有菜单，找了半天没找到

**Comment by xiaoxian521** [comment]
这是因为前几天重构主题带来的影响 后面有时间修复

**Comment by luohailong** [comment]
宽度小于760之后就没有菜单了，顶部也没有显示折叠按钮，求大佬修复

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/commit/3879b99176d0064b75a65c08b6d12a03400ee204
