### ISSUE TITLE
在Tab右键菜单中增加“”关闭右侧标签页”和“关闭左侧标签页”

### ISSUE THREAD

**Issue by xjieinfo** [xiaoxian521/vue-pure-admin#32]
在Tab右键菜单中增加“”关闭右侧标签页”和“关闭左侧标签页”，这样更加方便。

**Comment by xiaoxian521** [comment]
feat: https://github.com/xiaoxian521/vue-pure-admin/commit/a2b200f5f23cf894ba9b77efb5d9df68da0c6420

**Comment by xjieinfo** [comment]
大佬效率就是高啊
