### ISSUE TITLE
生产模式下，顶部模式和混合模式布局的头部菜单在重复点击浏览器刷新按钮，只显示一个...菜单项

### ISSUE THREAD

**Issue by HgLight** [xiaoxian521/vue-pure-admin#320]
**Describe the bug**
生产模式下，顶部模式和混合模式布局的头部菜单在重复点击浏览器刷新按钮，只显示一个...菜单项

**To Reproduce**
1. 登录进入首页
2. 点击浏览器“刷新”按钮或按F5刷新页面
3. 混合模式和顶部模式布局的头部菜单显示异常

**Expected behavior**

**Screenshots**
![normal](https://user-images.githubusercontent.com/8352942/183554542-36fc4694-3980-4ac6-8d99-f4a38519c339.png)
登录进入首页，未刷新页面
![error](https://user-images.githubusercontent.com/8352942/183554577-460ce561-c255-4884-878f-05813c6b748f.png)
刷新页面后

**Desktop (please complete the following information):**
 - OS: [Windows11]
 - Browser [chrome]
 - Version [103.0.5060.114（正式版本） （64 位）

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xiaoxian521** [comment]
这个正在修复
目前没时间写
https://github.com/element-plus/element-plus/pull/9124

**Comment by xiaoxian521** [comment]
演示环境无法复现你的问题
https://vue-pure-admin.vercel.app/#/welcome
