### ISSUE TITLE
请求的下拉框数据无法回显

### ISSUE THREAD

**Issue by yh-mai** [xiaoxian521/vue-pure-admin#321]
**Describe the bug**
当下拉框的数据是由接口请求返回时，无法回显，点击选择同样无法回显、无法获取到当前值
今天之前还可以，但今天把 responsive-storage 依赖锁定在1.0.11后出现的

**To Reproduce**
当 responsive-storage 依赖为 ^1.0.11时，无法正常启动
当 responsive-storage 依赖锁定为 1.0.11 时，可以启动，但通过接口获取数据的下拉框无法正常使用
![image](https://user-images.githubusercontent.com/72854238/183915387-d06e8483-d2fd-4c50-8fcc-2a19fe31365c.png)

**Comment by xiaoxian521** [comment]
你当前的pure版本过低 不考虑处理之前版本问题
