### ISSUE TITLE
Click tag to jump twice

### ISSUE THREAD

**Issue by qq740781278** [xiaoxian521/vue-pure-admin#322]
**Describe the bug**
标签组件 点击tag 

**To Reproduce**
router-link 与 tagOnClick 都触发了路由跳转

**Expected behavior**
跳转一次

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xiaoxian521** [comment]
并无任何影响

**Comment by qq740781278** [comment]
setup会走两次 依赖query的操作会报错




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaoxian521/vue-pure-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月11日(星期四) 下午4:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaoxian521/vue-pure-admin] Click tag to jump twice (Issue #322)





 
并无任何影响
