### ISSUE TITLE
一直报 Preprocessor dependency "sass" not found. Did you install it?； 按照文档删除pnpm.yaml也不行

### ISSUE THREAD

**Issue by lou19891014** [xiaoxian521/vue-pure-admin#323]
➜  Network: http://192.168.1.240:8848/
Preprocessor dependency "sass" not found. Did you install it?
Preprocessor dependency "sass" not found. Did you install it? (x2)
Preprocessor dependency "sass" not found. Did you install it? (x3)
Preprocessor dependency "sass" not found. Did you install it? (x4)
Preprocessor dependency "sass" not found. Did you install it? (x5)
17:26:18 [vite] Internal server error: Preprocessor dependency "sass" not found. Did you install it?
  Plugin: vite:css
  File: E:/练习项目vue3/pure-test/src/style/index.scss

**Comment by xiaoxian521** [comment]
请好好看文档 最上方

**Comment by lou19891014** [comment]
好的

**Comment by jiameng15** [comment]
使用nvm管理node版本
切换的node版本为16.16.0
pnpm版本为6.32.3
npm源地址为[原版地址](https://registry.npmjs.org/)
遇到一样的问题

**Comment by xiaoxian521** [comment]
如果你那么喜欢不规范命名或者中文目录
你可以尝试这样做
https://github.com/xiaoxian521/vue-pure-admin/commit/271b953081e2190770998313089f55a43cbe4a4d

**Comment by jiameng15** [comment]
好的,谢谢
