### ISSUE TITLE
非菜单路由点击后能够单独显示

### ISSUE THREAD

**Issue by BugOS-ly** [xiaoxian521/vue-pure-admin#324]
![image](https://user-images.githubusercontent.com/85739810/184128318-03d75b38-4e99-43a4-8fea-64fbd37f1a65.png)
希望点击非菜单路由后, 能够在图片红框位置显示类似"首页", "个人中心" 这样的页面标题,  点击这个页面标题能进入页面

**Comment by xiaoxian521** [comment]
已经支持 参考
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/44761321/184129035-14651574-7fdb-4cac-aa76-7769017bd1d8.png">

**Comment by BugOS-ly** [comment]
谢谢大佬, 回复的这么快, 真心喜欢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xiaoxian521/vue-pure-admin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月11日(星期四) 晚上8:02
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xiaoxian521/vue-pure-admin] 非菜单路由点击后能够单独显示 (Issue #324)





 
已经支持 参考
