### ISSUE TITLE
精简版 左边导航栏为啥没内容

### ISSUE THREAD

**Issue by dashixiong-11** [xiaoxian521/vue-pure-admin#325]
<img width="547" alt="image" src="https://user-images.githubusercontent.com/39214393/184381718-b4f62c7c-0633-4328-9ddd-7fdcecc7eeb1.png">
不是应该有个首页的导航吗 是不是因为这个原因我自己添加路由也不会显示出导航

**Comment by dashixiong-11** [comment]
<img width="361" alt="image" src="https://user-images.githubusercontent.com/39214393/184382038-b51d5185-46d7-4a3d-b9fb-c8abbb1e8ec5.png">
完整版一进来就有这个

**Comment by xiaoxian521** [comment]
无法复现

**Comment by dashixiong-11** [comment]
> 无法复现
重新拉了下代码 正常了.. 估计是我不小心改错了哪儿
