### ISSUE TITLE
保留页面编辑内容

### ISSUE THREAD

**Issue by xjieinfo** [xiaoxian521/vue-pure-admin#33]
保留页面编辑内容，如在“编辑”页面编辑了一些内容，切换到其他页面，再切换回来，发现原来编辑的内容不见了，希望能够保留。

**Comment by xiaoxian521** [comment]
close: https://github.com/xiaoxian521/vue-pure-admin/commit/8187dbff0eb5431fbb7804d6f5136b9494defc19

**Comment by xjieinfo** [comment]
感谢
