### ISSUE TITLE
在使用两个全屏之后，第一个全屏被重置

### ISSUE THREAD

**Issue by yh-mai** [xiaoxian521/vue-pure-admin#330]
**Describe the bug**
点击头像边的全屏后点击标签栏的全屏
之后再次点击全屏按钮会取消全屏，但是头像边的全屏变成了关闭图标，并且此时已经是一个全屏状态，但点击后并不会退出全屏

**To Reproduce**
1.
点击头像边的全屏按钮
![image](https://user-images.githubusercontent.com/72854238/185747533-2ffbff4e-78fe-4343-b302-6ed342313648.png)

2.
点击标签栏的全屏按钮
![image](https://user-images.githubusercontent.com/72854238/185747583-418ef481-9ad7-4f86-8a4a-c47805f33728.png)

3.
点击标签栏的全屏按钮
![image](https://user-images.githubusercontent.com/72854238/185747751-cd52ad9e-fa71-4fdc-8746-0df886c34a0e.png)

4. 点击头像边的全屏按钮
![image](https://user-images.githubusercontent.com/72854238/185747821-3a506a4d-a626-4f6b-8021-f6bac02c4344.png)

**Expected behavior**
退出全屏

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/commit/c1193281760d84528045a49604f5359f6b390609
