### ISSUE TITLE
pnpm build 报错

### ISSUE THREAD

**Issue by figo361** [xiaoxian521/vue-pure-admin#334]
![image](https://user-images.githubusercontent.com/6834921/186061009-797c896b-d32f-4761-aec8-555ab5c8cdd1.png)
提示路径不对这个要怎么处理

**Comment by xiaoxian521** [comment]
参考：https://github.com/xiaoxian521/vue-pure-admin/commit/708ce43e003a422551e9f1c9c36bf35e5c3038fd

提醒一点 最好跟平台保持到最新版本，之前的问题可能都会在最新版本修复
