### ISSUE TITLE
顶部菜单问题

### ISSUE THREAD

**Issue by Kabuda-czh** [xiaoxian521/vue-pure-admin#339]
作者您好, 因需求菜单只能在顶部, 在顶部菜单有一定数量时, 窗口缩小会正常的缩短超出部分为省略号, 但直接最大化后无法恢复正常, 慢慢拖动放大可以恢复正常

![1](https://user-images.githubusercontent.com/62021214/187595467-f1dade97-7b0c-4b65-a9c6-60ada5af0675.png)
这是页面缩小的样子

![2](https://user-images.githubusercontent.com/62021214/187595518-3bb3d5b5-1ce9-4862-977e-b95859b3f3cc.png)
这是直接最大化的样子

**Comment by xiaoxian521** [comment]
升级最新版 `element-plus`，已经在 [这里](https://github.com/element-plus/element-plus/commit/b7fe5df6f9c97ccbb223aa54e21b877afdcb3d28)解决了，还有提醒一点，最好和我的代码版本保持同步。
