### ISSUE TITLE
legacy为true的情况下build报错

### ISSUE THREAD

**Issue by nanpangyou** [xiaoxian521/vue-pure-admin#340]
**Describe the bug**
打包时兼容传统浏览器，将legacy设置为true，打包过程报错

**To Reproduce**
打包时兼容传统浏览器，将legacy设置为true，打包过程报错

**Expected behavior**
打包正常

**Screenshots**
![image](https://user-images.githubusercontent.com/11482364/187858604-96e11ba8-792d-4889-a112-32d3bf90c897.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.6
 - Browser Chrome 104.0.5112.101

**Additional context**
![image](https://user-images.githubusercontent.com/11482364/187858794-accdd172-5334-4486-a0f9-ebdd98ea7b8c.png)
vite尝试过3.0.9的版本，报错相同
应该是引入unocss的原因，抽离unocss后（mian.ts不引入，vite plugin不引入）可打包成功

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/xiaoxian521/vue-pure-admin/commit/3683bd46a47698d04ef366d8cfb01c0bc2866460)
