### ISSUE TITLE
精简版测出两个bug

### ISSUE THREAD

**Issue by congLinx** [xiaoxian521/vue-pure-admin#341]
复现步骤：
第一个bug：在welcome页面，写上‘<p v-auth="'v-admin'" 只有admin可看</p>’，然后再点击浏览器的刷新(反复多次点击浏览器出刷新)，会偶现“只有admin可看”不显示。

第二个bug：菜单是后端接口返回的，不同角色登陆，第一个角色登陆完点击退出，然后第二个角色再登陆，左侧菜单还是第一个角色的菜单，要手动刷新下浏览器才显示第二个角色的菜单。

特别注意：
这两个bug本地是都正常的，要build之后发布到nginx才能复现

环境
pure-admin-thin：3.4.6
chrome：104.0.5112.101
node:  16.13.1
macOS: 12.0.1

**Comment by xiaoxian521** [comment]
提供复习链接 否则不会认为是bug 因为本地没问题 你说的这些bug是你打包后的问题

**Comment by congLinx** [comment]
> 提供复现链接 否则不会认为是bug 因为本地没问题 你说的这些bug是你打包后的问题

但我就是直接clone精简版代码下来，然后发布我本地的nginx上，然后用过链接访问，能复现我说的问题

**Comment by xiaoxian521** [comment]
> > 提供复现链接 否则不会认为是bug 因为本地没问题 你说的这些bug是你打包后的问题
> 
> 但我就是直接clone精简版代码下来，然后发布我本地的nginx上，然后用过链接访问，能复现我说的问题

提供复现链接

**Comment by congLinx** [comment]
> > > 提供复现链接 否则不会认为是bug 因为本地没问题 你说的这些bug是你打包后的问题
> > 
> > 
> > 但我就是直接clone精简版代码下来，然后发布我本地的nginx上，然后用过链接访问，能复现我说的问题
> 
> 提供复现链接

我没有办法提供外网的链接给你访问到，那就直接忽视第二问题吧。第一个问题你那里很好测吧，就是在welcome页面加个权限按钮就可以复现了。
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/112139220/188350615-e50d385f-502c-40da-83b6-657fbe519848.png">
