### ISSUE TITLE
打开了VITE_LEGACY=true 打包不成功

### ISSUE THREAD

**Issue by ezewu** [xiaoxian521/vue-pure-admin#343]
VITE_LEGACY = true

rendering chunks (29)...[unocss:global:build:generate] [unocss] does not found CSS placeholder in the generated chunks
This is likely an internal bug of unocss vite plugin
error during build:
Error: [unocss] does not found CSS placeholder in the generated chunks
This is likely an internal bug of unocss vite plugin

**Comment by xiaoxian521** [comment]
已经修复，等合并 https://github.com/xiaoxian521/vue-pure-admin/pull/342
