### ISSUE TITLE
左侧菜单展开收起卡顿

### ISSUE THREAD

**Issue by moka-erb** [xiaoxian521/vue-pure-admin#345]

**Comment by xiaoxian521** [comment]
http://yiming_chang.gitee.io/pure-admin-doc/pages/f8dc77/#%E5%8D%81%E4%B8%89-vertical-%E6%A8%A1%E5%BC%8F%E4%B8%8B%E5%B7%A6%E4%BE%A7%E8%8F%9C%E5%8D%95%E5%8D%A1%E9%A1%BF-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3-%E8%8F%9C%E5%8D%95%E5%88%87%E6%8D%A2%E5%8D%A1%E9%A1%BF

**Comment by moka-erb** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
