### ISSUE TITLE
按钮hover状态颜色问题

### ISSUE THREAD

**Issue by freadman** [xiaoxian521/vue-pure-admin#346]
如图，在按钮的hover状态时，字体颜色与背景色区分度太低
<img width="504" alt="image" src="https://user-images.githubusercontent.com/104674917/189084514-3137e507-6a92-41d0-a22b-bfe566e8b692.png">

**Comment by xiaoxian521** [comment]
无法复现，请使用最新代码
<img width="1611" alt="image" src="https://user-images.githubusercontent.com/44761321/189169879-caff11e2-a214-4969-87cb-426c82d8615c.png">

**Comment by freadman** [comment]
我在你们官方的预览站里面就存在这个问题，奇怪了，为什么你不会呢？

**Comment by freadman** [comment]
我用的是vxetable，我看了下是由这个插件的样式引起的，在IDE里面预览正常，只有打包后是有问题的。
<img width="460" alt="image" src="https://user-images.githubusercontent.com/104674917/189247282-aa2178f3-3567-4dd4-b51b-fa6a3dff2b5d.png">
