### ISSUE TITLE
页面使用vxe-table的工具栏(如导出，自定义列)出现的问题

### ISSUE THREAD

**Issue by jear83** [xiaoxian521/vue-pure-admin#348]
<script setup lang="ts">
import { ref, reactive, nextTick } from "vue";
import { VxeTableInstance, VxeToolbarInstance } from "vxe-table";

defineOptions({
  name: "dict"
});

const demo1 = reactive({
  tableData: [
    { name: "Test1", role: "前端", sex: "男" },
    { name: "Test2", role: "后端", sex: "男" },
    { name: "Test3", role: "测试", sex: "男" },
    { name: "Test4", role: "设计师", sex: "女" }
  ]
});
const xTable = ref({} as VxeTableInstance);
const xToolbar = ref({} as VxeToolbarInstance);

nextTick(() => {
  // 将表格和工具栏进行关联
  xTable.value.connect(xToolbar.value);
});
</script>

<template>
  <div class="welcome">
    sss
    <vxe-toolbar ref="xToolbar" custom export />
    <vxe-table ref="xTable" :export-config="{}" :data="demo1.tableData">
      <vxe-column field="name" title="Name" />
      <vxe-column field="role" title="Role" />
      <vxe-column field="sex" title="Sex" />
    </vxe-table>
  </div>
</template>

### 页面在第一次加载的时候导出和自定义列不能弹出功能框，整个浏览器刷新(使用框架里的刷新无用)后才能使用，使用的是最新的v3.5 ,还有同样的代码在精简版v3.5里无法显示table

**Comment by xiaoxian521** [comment]
跟平台无关
