### ISSUE TITLE
左边菜单没折叠

### ISSUE THREAD

**Issue by JakeWoki** [xiaoxian521/vue-pure-admin#35]
第一个是线上效果，第二个是本地运行的
![122](https://user-images.githubusercontent.com/6948411/131460296-2e2aebde-a4d5-4a31-a66f-0beb74288774.png)
![123](https://user-images.githubusercontent.com/6948411/131460304-c417e029-05a2-403d-a9c2-449b24be8dfd.png)

**Comment by xiaoxian521** [comment]
更换谷歌浏览器最新版

**Comment by JakeWoki** [comment]
新版也一样，之前是有折叠的，估计是最近element-plus的升级有关系吧
以前import "element-plus/packages/theme-chalk/src/base.scss";
现在import "element-plus/dist/index.css";
估计是样式的问题

**Comment by xiaoxian521** [comment]
我这边没问题

**Comment by xiaoxian521** [comment]
```import "element-plus/dist/index.css"```
这个是完全引入样式，你拉起代码不要动用npm install安装 清下本地缓存

**Comment by JakeWoki** [comment]
重新拉代码下来正常了

**Comment by xiaoxian521** [comment]
嗯嗯，近期会发布稳定版本，同时出套视频，你们就不会踩坑了
