### ISSUE TITLE
如何实现路由中的命名视图功能

### ISSUE THREAD

**Issue by sXy98713** [xiaoxian521/vue-pure-admin#350]
作者您好，我尝试扩展RouteConfigsTable和RouteChildrenConfigsTable，想在其中添加components元素来实现命名视图，但没有成功。对于一个包含多个<router-view>标签的vue只渲染默认项，请问您我的问题在哪。
![1663554938757](https://user-images.githubusercontent.com/24778276/190941476-04ffa459-1016-47f6-b9d9-9ed236bd54cc.png)

**Comment by xiaoxian521** [comment]
不提供扩展功能讲解，自行研究
