### ISSUE TITLE
精简版准备提供无国际化版本通知

### ISSUE THREAD

**Issue by xiaoxian521** [xiaoxian521/vue-pure-admin#351]
很多码友有这个需求，平台准备在 `3.6.2` 版本时给 [精简版](https://github.com/xiaoxian521/pure-admin-thin) 提供 `无国际化` 版本（也意味着又精简了一部分代码 😎）并且作为主分支，当然还会保留精简版 `有国际化` 的版本，并且两个版本会 `永久同步` 完整版代码。

**Comment by huohuoit** [comment]
我刚用精简版剔除完国际化，同时同步完完整版代码😎😎😎

**Comment by xiaoxian521** [comment]
🎉 [点击查看非国际化版本](https://github.com/xiaoxian521/pure-admin-thin) 
🎉 [点击查看国际化版本](https://github.com/xiaoxian521/pure-admin-thin/tree/i18n)
