### ISSUE TITLE
页面没有热更新，需要手动刷新

### ISSUE THREAD

**Issue by alaxury** [xiaoxian521/vue-pure-admin#352]
问题1： 路由后台返回，格式和Mock的一样。页面内容 即使修改文字，也需要手动刷新页面，请问怎么才能热更新。刚试了下静态路由的页面，也没热更新。得手刷。
问题2： 项目运行久后缓存严重也有点卡，手动刷新都不行了，得ctrl + f5,。
有在群里反馈，希望能解决，谢谢

**Comment by xiaoxian521** [comment]
无法复现

**Comment by xiaoxian521** [comment]
提供复现地址

**Comment by xiaoxian521** [comment]
你电脑性能不高吧 如果是这样 问题2你可以这么解决 关闭项目 停止vite 然后重新启动项目

**Comment by xiaoxian521** [comment]
> 你电脑性能不高吧 如果是这样 问题2你可以这么解决 关闭项目 停止vite 然后重新启动项目

还有 如果是浏览器卡 那说明你内存泄露呀 与平台没有关系 看看自己的业务代码

**Comment by xiaoxian521** [comment]
问题一造成的原因也有可能是你安装了devtools插件，这个插件目前还是有问题的

**Comment by alaxury** [comment]
没有安装devtools插件，运行其他vite项目，vue2项目没问题==
