### ISSUE TITLE
顶部菜单显示时 有时会出现覆盖顶部右侧菜单的情况

### ISSUE THREAD

**Issue by CMCHENSX** [xiaoxian521/vue-pure-admin#353]
顶部菜单显示时 有时会出现覆盖顶部右侧菜单的情况
![QRTR`C}M{Y83T_C8AGS2OVU](https://user-images.githubusercontent.com/29833779/195539004-cc3bc0d5-5dc8-4a80-82be-6b2947be72fe.jpg)

**Comment by xiaoxian521** [comment]
开发环境？

**Comment by xiaoxian521** [comment]
> 

谢谢反馈 我将跟踪此问题

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/commit/5bce4dfa6add8dabb3047a6419314c815de3a28d
