### ISSUE TITLE
utils-1.0.8.tgz: Not Found - 404

### ISSUE THREAD

**Issue by mochunshuang** [xiaoxian521/vue-pure-admin#354]
PS E:\online_project\github\vue-pure-admin> pnpm install
 WARN  GET https://registry.npmmirror.com/@pureadmin/utils/-/utils-1.0.8.tgz error (ERR_PNPM_FETCH_404). Will retry in 10 seconds. 2 retries left.
 WARN  GET https://registry.npmmirror.com/@pureadmin/utils/-/utils-1.0.8.tgz error (ERR_PNPM_FETCH_404). Will retry in 1 minute. 1 retries left.
 ERR_PNPM_FETCH_404  GET https://registry.npmmirror.com/@pureadmin/utils/-/utils-1.0.8.tgz: Not Found - 404

<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<RequestId>634C2A915C5E113634ADF01B</RequestId>
<HostId>npmmirror.oss-cn-shanghai.aliyuncs.com</HostId>
<Key>packages/@pureadmin/utils/1.0.8/utils-1.0.8.tgz</Key>
</Error>

**Comment by xiaoxian521** [comment]
你本地环境问题 不要用别的代理 切换到npm源
