### ISSUE TITLE
标签风格在“卡片”模式下，会导致样式错误

### ISSUE THREAD

**Issue by simple-ice** [xiaoxian521/vue-pure-admin#355]
![image](https://user-images.githubusercontent.com/38436206/196621717-48ddaee3-8c1f-4c35-b3fd-0fb8b9765b08.png)

![image](https://user-images.githubusercontent.com/38436206/196621851-edf0b9a8-a258-42c7-bc2f-eb57093fce77.png)

灵动风格没有此问题

**Comment by xiaoxian521** [comment]
感谢反馈 稍后修复 😊

**Comment by xiaoxian521** [comment]
升级项目中的 `@pureadmin/utils` 到最新版本，[参考](https://github.com/xiaoxian521/vue-pure-admin/commit/f9cf80462772229673a17a6c5bcf55e65f1a48a6)，即可解决
