### ISSUE TITLE
混合模式下，刷新页面时的菜单选中异常

### ISSUE THREAD

**Issue by mynetfan** [xiaoxian521/vue-pure-admin#358]
在混合模式下，刷新页面后左侧菜单有时候会丢失。
重现步骤：
1、切换为混合模式布局
2、点击顶部的“组件”菜单
3、按F5刷新页面
4、观察左侧菜单加载和选中情况。
5、不断重复步骤3和步骤4，即可观察到左侧菜单时有时无

**Comment by xiaoxian521** [comment]
开发模式吗

**Comment by xiaoxian521** [comment]
生产环境的确有这个问题  谢谢反馈

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/pull/357/commits/66f1be4006ba829a38f3c6f6068718504c8289db
待合并该分支后重新发布演示环境即可恢复
