### ISSUE TITLE
精简版使用淘宝镜像源下载依赖报错

### ISSUE THREAD

**Issue by Dalegac** [xiaoxian521/vue-pure-admin#359]
![issue](https://user-images.githubusercontent.com/25010602/197346530-0d60d54a-aabe-418a-b879-9680cd07864e.png)

**Comment by Dalegac** [comment]
![8R8G9EA2SCQB2VN0{KHY{)Q](https://user-images.githubusercontent.com/25010602/197346597-cd2c49b1-2604-44fa-b4bf-2f443be3608c.png)
引入的这些依赖有的下载不到。。

**Comment by xiaoxian521** [comment]
淘宝镜像不稳定 并不是实时同步拉取npm包
所有换成npm源最稳
多看文档

**Comment by xiaoxian521** [comment]
<img width="1414" alt="image" src="https://user-images.githubusercontent.com/44761321/197347173-053867bb-39f4-4f94-aed5-6f1fe3db2988.png">
