### ISSUE TITLE
折叠按钮位置不对？

### ISSUE THREAD

**Issue by imoyao** [xiaoxian521/vue-pure-admin#363]
**Describe the bug**
按照个人理解，侧边栏的展开关闭应该在首页旁边，这样比较方便一点吧，看之前的演示也是放在首页旁边的，但是目前看到的是在侧边栏最下方？不知是设计调整还是重构 #319 导致的问题？

**To Reproduce**

![image](https://user-images.githubusercontent.com/22978431/198835129-60b0a3a7-f8d1-444b-bba4-4954fed9c0b8.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/22978431/198834989-8be73e64-5ee3-4c20-9c1d-c8bbdcc3d7e4.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] windows10
 - Browser [e.g. chrome, safari] Microsoft Edge
 - Version [e.g. 22]  版本 106.0.1370.42 (正式版本) (64 位)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xiaoxian521** [comment]
这是新设计

**Comment by xiaoxian521** [comment]
不习惯可以自己修改

**Comment by xiaoxian521** [comment]
折叠是针对左侧的`menu`，所以两种放一起没有任务歧义。
`ant-design-pro`也是如此设计哦
https://preview.pro.ant.design/dashboard/analysis
