### ISSUE TITLE
接口token过期刷新机制优化

### ISSUE THREAD

**Issue by freadman** [xiaoxian521/vue-pure-admin#364]
**问题：**
一般情况下，后台的一个页面会同时请求多个接口，比如5个，当接口token过期时，也就是会同时发出5个刷新token的请求，这样问题就来了，一般情况下，服务端的刷新token后，用来刷Token的refreshToken会过期，也就是说5次刷新请求，第一次返回后，其余4次就会失败，因为refreshToken已经过期了。
**解决方案：**
设置一个变量isRereshing，默认false，在请求拦截中当第一个刷新接口的请求发出时，把isRereshing设为true。当isRefreshing==true时，其余的请求不发出，而是加入到一个等待的数组中（请求组），当A请求返回后，isRereshing设为false，把Token更新，然后，发出刚才暂存的请求组中的请求，这时用的是新的Token，就不会报错了。

**Comment by xiaoxian521** [comment]
欢迎pr

**Comment by freadman** [comment]
> 欢迎pr
水平不够，研究了一天，一直没搞定这个问题
<img width="740" alt="image" src="https://user-images.githubusercontent.com/104674917/199046077-bfd08fe5-d916-4035-8d6b-364b4855036f.png">
<img width="1296" alt="image" src="https://user-images.githubusercontent.com/104674917/199046140-581f6ea9-39a7-444a-aa38-c50296e12df5.png">

**Comment by xiaoxian521** [comment]
已修复：[commit](https://github.com/xiaoxian521/vue-pure-admin/commit/27bc135bd2b19553a4ddd2a9809fb4800ee7208c)
