### ISSUE TITLE
混合菜单栏模式下折叠菜单栏显示问题

### ISSUE THREAD

**Issue by huohuoit** [xiaoxian521/vue-pure-admin#370]
**Describe the bug**
在mixnav（混合菜单栏）模式下，点击菜单栏底部的折叠按钮，如果当前路由菜单没有icon选项，即没有菜单图标，显示会有问题

**To Reproduce**
1. 进入mixnav（混合菜单栏）模式
2. 点击菜单栏底部的折叠按钮
3. 如果当前路由菜单没有icon选项，即没有菜单图标，显示会有问题

**Expected behavior**
强制要求有图标，还是换一种方式进行显示

**Screenshots**
![image](https://user-images.githubusercontent.com/60650531/200764559-68f42b36-caa0-4f8e-ba1e-709c78eb8bcc.png)

**Desktop (please complete the following information):**
 - Windows 10
 - Chrome
 - Latest

**Comment by xiaoxian521** [comment]
这显示有啥问题？超出隐藏，鼠标覆盖会显示全部信息
