### ISSUE TITLE
`pure-admin` 下一步优化进度

### ISSUE THREAD

**Issue by xiaoxian521** [xiaoxian521/vue-pure-admin#372]
`文档方面`
- [x] 重构完 [项目配置](https://yiming_chang.gitee.io/pure-admin-doc/pages/config/) 文档
- [x] 重构完 [http请求](https://yiming_chang.gitee.io/pure-admin-doc/pages/request/) 文档
- [x] 添加 [git常用命令](https://yiming_chang.gitee.io/pure-admin-doc/pages/git/) 文档
- [x] 编写单点登录文档
- [x] 编写 `vite` 预构建文档
- [ ] 重构完 [路由和菜单](https://yiming_chang.gitee.io/pure-admin-doc/pages/routerMenu/) 文档
- [ ] 重构完 [项目规范](https://yiming_chang.gitee.io/pure-admin-doc/pages/standard/) 文档

`平台代码方面`
- [x] 优化接口使用方式，带来更规范、更便捷的使用方式（这也是我写文档时看到目前接口使用方式的不足，才产生的想法，所以在写上面的文档时不免会有代码改动，当上面文档提到的都重构写完后，平台代码改动就不会太大了）
- [x]  添加更多 [pure-admin-table](https://github.com/xiaoxian521/pure-admin-table) 代码示例到完整版演示地址
- [x]  添加简版单点登录，这里主要是处理前端的逻辑，实际开发主要逻辑在后端。测试地址：https://yiming_chang.gitee.io/vue-pure-admin/#/pure-table/index?username=sso&roles=admin&accessToken=eyJhbGciOiJIUzUxMiJ9.admin
- [x] 更完整的全局类型提示
- [x] 静态路由平台自动导入，无需手动引入
- [x] [优化 vite 依赖预构建在平台里的配置，页面切换速度显著加快](https://github.com/xiaoxian521/vue-pure-admin/commit/aedc10a6dca3249ceaaa0f1d6aadcfa185423410)
- [x] 添加 `message` 消息提示函数，兼容 `Element Plus` 和 `Ant Design` 两种 `Message` 样式风格，使用和打包大小成本极低并适配暗黑模式
- [x] 可配置在登录时是否缓存动态路由到本地 `sessionStorage` ，默认缓存，这样可以做到刷新页面不再调用 `getAsyncRoutes` 接口获取动态路由，而是走本地缓存，提升页面加载性能
- [x] 添加 `TooltipEffect` 全局配置，可配置平台主体所有 `el-tooltip` 的 `effect`，不影响业务代码
- [ ] 平台会有一个固定的 `home` ，显示在首页，有些码友不想要这个，其实可以通过在路由设置 `showLink: false` 解决这个问题，但是解决方式不是很完美，接下来我会重构掉它，提供可配置化显示首页
- [ ] https://github.com/xiaoxian521/vue-pure-admin/issues/390

`视频教程方面`
- [x] 因在 `B`站 [这个视频](https://www.bilibili.com/video/BV1Xv4y1U7UN/) 的评论下面，有码友提到需要个 `快速开发的教程`，好提议，接下来我会重构 [pure-admin 后端代码](https://github.com/xiaoxian521/pure-admin-backend) 直接用真实后台环境来出这个 `快速开发的教程`，喜欢的话可以一键三连 ❤️
视频教程地址：https://www.bilibili.com/video/BV1kg411v7QT/

`编写丰富高级的` [@pureadmin/table 使用示例](https://github.com/xiaoxian521/pure-admin-table)
- [x] 拖拽（行、列）
- [x] 右键菜单
- [x] 导出execl
- [x] 单元格编辑
- [x] 水印
- [x] 打印
- [x] 内嵌 `echarts` 图表
- [x] 添加表格选择器（单选、多选）

**Comment by miragelu-seekasia** [comment]
打开速度太慢了， 能明显的感受到延迟
