### ISSUE TITLE
页内菜单带参互相跳转 标签没有选中高亮

### ISSUE THREAD

**Issue by 18508409531** [xiaoxian521/vue-pure-admin#374]
有两个菜单
菜单A
菜单B

从菜单B使用router.push({ path: '/2222', query: { flowCode: 'ceshi'} })菜单A被打开但是没有高亮

![image](https://user-images.githubusercontent.com/35060559/200796060-bbdab6ba-1fc5-4143-84e5-fac70b64f35a.png)

猜测是地址发生变化引起的

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/commit/facb09d7794129a62c60d5a5a16354c5ffc8f01f
