### ISSUE TITLE
pure-table 多级表头

### ISSUE THREAD

**Issue by yuweiqi1995** [xiaoxian521/vue-pure-admin#377]
多级表头要如何编写？

**Comment by xiaoxian521** [comment]
参考element-plus的table

**Comment by yuweiqi1995** [comment]
但是element-plus的table columns是写在html里的，pure-table是在tsx里的，方便提供一下例子吗？

**Comment by xiaoxian521** [comment]
有计划使用pure-table编写各种demo，但是这重要程度很低，目前没时间，等有空吧

**Comment by xiaoxian521** [comment]
已加入进程：https://github.com/xiaoxian521/vue-pure-admin/pull/379
