### ISSUE TITLE
切换页签时画面呈现空白

### ISSUE THREAD

**Issue by dpes8693** [xiaoxian521/vue-pure-admin#381]
Bug 描述
在首页因为不明原因(推测是CSS问题)切换页签时画面呈现空白

错误重现步骤:
0. 起全新的专案，到`\src\views\welcome\index.vue`，将程式码全部删掉
1. 贴上下方有问题的程式码，执行`pnpm dev`
2. 切换路由到任意其他页签 =>发现空白页面问题，没有错误讯息
3. 回到首页(welcom.vue) =>也发现空白页面问题，没有错误讯息

有问题的 Code:
```ts
// \src\views\welcome\index.vue
<script setup lang="ts">
defineOptions({
  name: "Welcome"
});
</script>

<template>
  <!-- <h1>Pure-Admin-Thin</h1> -->
  <div class="myWrapper">
    <img src="https://fakeimg.pl/300/" />
  </div>
</template>

<style scoped>
.myWrapper {
  padding: 50px;
}
</style>
```

截图:
![](https://i.imgur.com/xkHBBTs.png)
![](https://i.imgur.com/QvpBgbI.png)

**Comment by xiaoxian521** [comment]
```
// \src\views\welcome\index.vue
<script setup lang="ts">
defineOptions({
  name: "Welcome"
});
</script>

<template>
  <div class="myWrapper">
    <img src="https://fakeimg.pl/300/" />
  </div>
</template>

<style scoped>
.myWrapper {
  padding: 50px;
}
</style>
```

https://yiming_chang.gitee.io/pure-admin-doc/pages/FAQ/#vue3-%E5%8D%95%E6%96%87%E4%BB%B6%E6%94%AF%E6%8C%81%E5%A4%9A%E4%B8%AA%E6%A0%B9%E6%A0%87%E7%AD%BE-%E4%BD%86%E6%98%AF%E5%B9%B3%E5%8F%B0%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%83%BD%E8%BF%99%E4%B9%88%E7%94%A8%E5%91%A2-%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3
