### ISSUE TITLE
侧边导航栏折叠无法查看所有二级导航菜单

### ISSUE THREAD

**Issue by AQiuDaDa** [xiaoxian521/vue-pure-admin#385]
![$M6A1GH4RV`V3LEK 1NEE9](https://user-images.githubusercontent.com/36756438/204119923-15f83b35-1b3a-4c37-8de0-944d0e0013c6.png)
将侧边导航栏折叠后，点击查看二级菜单较多的功能菜单，发现无法下滑查看所有二级菜单

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/pure-admin/vue-pure-admin/pull/858)
