### ISSUE TITLE
windows系统页面整体退出全屏出现抖动问题

### ISSUE THREAD

**Issue by ShenHuiGitHub** [xiaoxian521/vue-pure-admin#386]
页面整体全屏，然后再退出全屏的时候，页面右侧抖动特别明显，精简版更明显，按F11全屏、退出全屏没问题。

**Comment by xiaoxian521** [comment]
无法复现
![Kapture 2022-11-27 at 20 07 44](https://user-images.githubusercontent.com/44761321/204134458-ca45594a-906f-4415-86d4-52d3f804f6ae.gif)

**Comment by xiaoxian521** [comment]
如果你想问的是为什么全屏时浏览器自带的标签页还在，需要等一下才能消失的话，我认为不同浏览器表现不同，你自己写个最简单的全屏例子也会是如此，下面是火狐浏览器的表现，可能谷歌浏览器可以设置，但是我并没有了解

https://user-images.githubusercontent.com/44761321/204134959-a235b43b-455c-4298-be07-982b4dfc8468.mov

**Comment by ShenHuiGitHub** [comment]
https://user-images.githubusercontent.com/10651238/204170701-5884c6c2-761d-433a-8582-6f791b6beb08.mp4

windows 10 chrome浏览器和edge都是这样。

**Comment by xiaoxian521** [comment]
好的 谢谢反馈 已经在windows复现

**Comment by xiaoxian521** [comment]
加入 https://github.com/xiaoxian521/vue-pure-admin/issues/372#issue-1441672847 进度
