### ISSUE TITLE
utils/http/index.ts 中关于最下方get/post请求会被eslint检测语法错误

### ISSUE THREAD

**Issue by Canroc** [xiaoxian521/vue-pure-admin#387]
**Is your feature request related to a problem? Please describe.**
因为默认封装的request请求的param参数为AxiosRequestConfig，所以出现以下警告
![image](https://user-images.githubusercontent.com/84954229/204434836-880c2a27-aa7c-4f0d-bd53-4fc37d786103.png)

**Describe the solution you'd like**
可以将传入的参数params的类型设置为AxiosRequestConfig<T>
![image](https://user-images.githubusercontent.com/84954229/204435182-0634e7f5-1eba-4e5e-97e9-c95c0a1435a7.png)

**Comment by xiaoxian521** [comment]
我很赞同你的观点，欢迎 `pr` ❤️

**Comment by xiaoxian521** [comment]
fix: https://github.com/xiaoxian521/vue-pure-admin/commit/ee5d82c021e11e0948dd93d409f400b052a4ecc1#diff-5499a4e519b284bc83b7bc1f83c1bf771ee09225f43283be19a16cc8f8034352
