### ISSUE TITLE
TableProBar右上角的列设置按钮功能扩展

### ISSUE THREAD

**Issue by mynetfan** [xiaoxian521/vue-pure-admin#390]
目前表格工具栏里的列设置按钮只有序号列和勾选列：
![image](https://user-images.githubusercontent.com/17241274/204705902-1ba19372-c35c-4766-b02f-04bdc7abb0d2.png)
希望增加对整个表格的列进行控制，比如控制列的可见性、顺序、固定等等，相关变化可以抛出事件以便保存列状态。
类似这样的：
![image](https://user-images.githubusercontent.com/17241274/204706578-f666c13c-09c6-4411-a5de-a935875c98ac.png)

**Comment by xiaoxian521** [comment]
暂时没有时间哦，可能明年会完善这个。目前主要精力都集中在优化性能和完善文档上。

**Comment by xiaoxian521** [comment]
join https://github.com/xiaoxian521/vue-pure-admin/issues/372#issue-1441672847
