### ISSUE TITLE
⚠️注意：平台将在 `v3.9.4` 版本移除内置 `vxe-table` 支持

### ISSUE THREAD

**Issue by xiaoxian521** [xiaoxian521/vue-pure-admin#392]
平台将在 `v3.9.4` 版本完全移除内置 `vxe-table` 支持，并将如何安装支持 `vxe-table` 写入文档，可自行支持

移除原因：
1. `vxe-table` 除了表格性能和可配置度高以外，别的组件没必要引入，虽然官方提供了按需引入示例，但是经过测试，整体包的大小也没小多少 😅  
2. 平台基于 `element-plus` 的 `el-table` 封装了 [pure-admin-table](https://github.com/xiaoxian521/pure-admin-table) 同样拥有高可配置度
3. `vxe-table` 的样式与 `element-plus` 的表格样式有区别，尽管平台通过自定义样式尽力适配，但感觉还是有差异，我比较挑 😄
4. `vxe-table` 的所有 `icon` 不支持 `component` 模式，这也意味着要使用图标必须引入静态图标 `css` 资源库比如 `font-awesome/css/font-awesome.min.cs`，这也造成我最近对平台进行性能优化的时候很困扰
5. 平台首推实际项目开发请使用 [精简版](https://github.com/xiaoxian521/pure-admin-thin)，但是也免不得有些哥们就是喜欢使用完整版 😭，剔除 `vxe-table` 也是为了优化打包大小和首启动页面加载速度
6. 使用 `vxe-table` 还需要额外安装 `xe-utils`，又增加了包的大小，不算上 `font-awesome/css/font-awesome.min.cs` 和 `xe-utils`，使用`vxe-table` 需要加载 `1.5MB` 资源，而且还是首屏加载，就有点尴尬了

<img width="813" alt="image" src="https://user-images.githubusercontent.com/44761321/205436376-8ab525ea-95d3-4097-bb80-dac5a5027aac.png">

7. 因为平台集成了 `vxe-table` 的主题适配平台主题色，这也带来了打包时在每个主题中都会把 `vxe-table` 相关引入的组件样式打包进来，又增加了平台体积，可看下图

![19121670215101_ pic_hd](https://user-images.githubusercontent.com/44761321/205550802-ecb42f5b-3845-411b-b368-c59e891148b1.jpg)

8. 实际感受中，并没有很多人选择使用 `vxe-table` ，平台内置的话就显得有些多余了 😅

最后，我们还是要感谢 [vxe-table](https://github.com/x-extends/vxe-table)  的开源，祝好 ❤️

**Comment by xiaoxian521** [comment]
移除后，完整版整体打包大小减少 `1.82MB`  
首启动时长基本和精简版持平 🐮

**Comment by pei-zheng-yi** [comment]
👍

**Comment by Koiandrop** [comment]
🐮

**Comment by webylb** [comment]
nice
