### ISSUE TITLE
当使用动态路由，且动态路由的path和component不一致时，刷新页面出现空白

### ISSUE THREAD

**Issue by freadman** [xiaoxian521/vue-pure-admin#393]
当使用动态路由，且动态路由的path和component不一致时，刷新页面出现空白，console错误提示：`Record with path "/articles" is either missing a "component(s)" or "children" property.`

**Comment by xiaoxian521** [comment]
谢谢反馈，这是因为开启 `CachingAsyncRoutes` 后造成的问题，有时间会修复

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/xiaoxian521/vue-pure-admin/commit/b5839d639866329164d656696cd8e108d162293d)
