### ISSUE TITLE
平台内置`lodash` 和相关库将在 `v3.9.5` 移除通知

### ISSUE THREAD

**Issue by xiaoxian521** [xiaoxian521/vue-pure-admin#397]
移除原因：

- [x] 在 `vite` 环境下，直接使用 `lodash` 有兼容问题且不支持 `tree-shaking`，所以平台选用了 `lodash-unified`，`lodash-unified` 既兼容 `esm` 又兼容 `cjs`，但是这样需要安装 `lodash`、`lodash-es`、`lodash-unified` 这三包了，外加 `@types/lodash`、`@types/lodash-es` 类型库，整整 `5` 个库啊，这真的没必要 😄，而且平台用到 `lodash` 的地方不多，所以平台打算在 `v3.9.5` 版本完全移除这 `5` 个库，我会将用到 `lodash` 的这些 `api` 兼容到 [@pureadmin/utils](https://pure-admin-utils.netlify.app/) 或者用原生 `js` 替代，这里我也建议如果用到 `lodash` 相关 `api` 不多并且能手写的话，就无需使用 `lodash`，这无论对 `vite` 预构建还是页面加载、打包优化都起着作用哦

**Comment by xiaoxian521** [comment]
[点我查看完成详情](https://github.com/xiaoxian521/vue-pure-admin/commit/3bb6e7348973c782d1fd0bdc91c10f6269721820)

**Comment by xiaoxian521** [comment]
[点我查看完成详情](https://github.com/xiaoxian521/vue-pure-admin/commit/2338dcab1f3d5fd0ffceb9d290ff60a1ecdc3556)

**Comment by Koiandrop** [comment]
🐮

**Comment by zdx2473788063** [comment]
🐮

**Comment by yinlin-291210** [comment]
🐮
