### ISSUE TITLE
标签页携参跳转菜单bug

### ISSUE THREAD

**Issue by xkres-com** [xiaoxian521/vue-pure-admin#401]
**Describe the bug**
标签页携参跳转菜单bug

**To Reproduce**
复现链接：http://yiming_chang.gitee.io/vue-pure-admin/#/tabs/index
1、点击按钮： 携参跳转页内菜单（传name对象，优先推荐） 
2、切换顶部标签页
3、再切回去那个携参的标签页
4、携带的参数丢失

**Expected behavior**
携带的参数不丢失

**Comment by xiaoxian521** [comment]
这种情况更建议用下图这个路由模式
<img width="926" alt="image" src="https://user-images.githubusercontent.com/44761321/207517000-1d1065ec-88c8-4042-a538-581ed2951cf0.png">
