### ISSUE TITLE
使用 `./` 路径打包部署后切换主题样式文件找不到

### ISSUE THREAD

**Issue by Mr-xzq** [xiaoxian521/vue-pure-admin#402]
**描述**

`VITE_PUBLIC_PATH` 为 `./` 相对路径时且服务器（比如：`ngix`）部署目录不是根（`/`）目录时，通过 `toggleTheme` 请求 `layout-theme-xxx.css` 路径错误。

**复现步骤**

1. 设置 `vite.config.js` 中的 `base: './'`;
2. 在静态服务器服务端(比如：`ngix`)进行部署，部署路径设置为非根路径，比如设置为：`/xxx`， 然后部署的域名为：`123.123.123.123:8888`, 这样完整路径为：`123.123.123.123:8888/xxx`

**期望的行为**

总共会有两次对 `layout-theme-default.css`  资源的请求：
第一次：是由构建的资源 `index.html` 中的 `link` 标签发出的请求，请求为：`123.123.123.123:8888/xxx/assets/layout-theme-default.css`：
```html
<!DOCTYPE html>
<html lang="en" class="layout-theme-default">
  <head>
    <!---->

    <!-- look here -->
    <link rel="stylesheet" href="./assets/layout-theme-default.css" id="head"> 
  </head>

  <body>
    <div id="app">
      <!---->
    </div>
    
  </body>
</html>

```

第二次：[setting.vue 中的 toggleTheme](https://github.com/xiaoxian521/vue-pure-admin/blob/e032f9a6a75ec8a666c52d8d151c67a01fff751f/src/layout/components/setting/index.vue#L58) 会触发浏览器请求资源  `123.123.123.123:8888/xxx/assets/layout-theme-default.css`

**现在存在的问题**

第二次请求 css 的路径错误，`123.123.123.123:8888/assets/layout-theme-default.css`，还是请求到了根路径

**问题原因**

`pure-admin-theme --> src/browser-utils.js` 中 [toggleTheme](https://github.com/pure-admin/pure-admin-theme/blob/a02a9ad561177219e860d48ac454796a913ef061/src/browser-utils.js#L82)  对 [href](https://github.com/pure-admin/pure-admin-theme/blob/a02a9ad561177219e860d48ac454796a913ef061/src/browser-utils.js#L100) 的处理出现问题了：
```js

// 当 basePath 为 './' 时, `/./` 会被替换为 `/` 从而导致资源请求不到
 const href = options.customLinkHref(
    `/${basePath || ""}/${browerPreprocessorOptions.outputDir || assetsDir || ""
      }/${options.scopeName}.css`.replace(/\/+(?=\/)/g, "")
  )

```

**解决方案**

第一种：

将 `vite.config.js` 中的 `base` 硬编码改为部署的路径，比如这里的 `base: '/xxx'`
缺点：如果部署路径更改，这里也得改

第二种：

我们知道由于是调用 `toggleTheme` 的时候请求的 css 的资源路径出问题，那么直接传入 `customLinkHref` 参数：
具体可以参考 [toggleTheme](https://github.com/pure-admin/pure-admin-theme/blob/a02a9ad561177219e860d48ac454796a913ef061/src/browser-utils.js#L82)  的入参和实现

```js

  toggleTheme({
    scopeName: `layout-theme-${theme}`,
    customLinkHref: (href) => {
      // 避免将 /./ 替换成 / 导致资源请求不到
      if (href.startsWith('/./')) href = href.slice(1);
      return href;
    },
  });

```

第三种：

更改 `pure-admin-theme --> src/browser-utils.js`  的源码中的 `toggleTheme` 中对 `href` 的处理

**Comment by Mr-xzq** [comment]
对的，调用 `toggleTheme` 加载 css 出现的问题

**Comment by xiaoxian521** [comment]
好的 一会看看哈

**Comment by xiaoxian521** [comment]
用 `./` 打包没问题啊 第一次加载和切换路径有啥问题？ 我打包线上预览都没事

**Comment by Mr-xzq** [comment]
部署路径为：xxxmoitor, 第一次是带有路径的正常请求，第二次直接请求到根路径去了

![image](https://user-images.githubusercontent.com/53166933/207547032-a290bc72-0c9b-484d-83a4-212adb7061cb.png)

**Comment by xiaoxian521** [comment]
你不应该这么打包啊
这里将的很清楚了 https://yiming_chang.gitee.io/pure-admin-doc/pages/build/#%E6%89%93%E5%8C%85

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/xiaoxian521/vue-pure-admin/commit/66fdfebb5e9b0c681a33fa3861db0852931ea1cf)
