### ISSUE TITLE
icon报错

### ISSUE THREAD

**Issue by JiangNaa** [xiaoxian521/vue-pure-admin#403]
src/components/ReIcon/src/hooks.ts文件，第46行左右

const IconifyIcon =
          icon & icon.includes(':') ? IconifyIconOnline : IconifyIconOffline;
        return h(IconifyIcon, {
          icon: icon,
          ...attrs
        });

这个报错，icon.includes(':')  ，打印了一下icon，有部分传入过来的不是字符串格式，而是下图这种格式，导致includes报错。
{
body: "<path fill=\"currentColor\" d=\"M771.776 794.88A384 384 0 0 1 128 512h64a320 320 0 0 0 555.712 216.448H654.72a32 32 0 1 1 0-64h149.056a32 32 0 0 1 32 32v148.928a32 32 0 1 1-64 0v-50.56zM276.288 295.616h92.992a32 32 0 0 1 0 64H220.16a32 32 0 0 1-32-32V178.56a32 32 0 0 1 64 0v50.56A384 384 0 0 1 896.128 512h-64a320 320 0 0 0-555.776-216.384z\"/>"
height: 1024
width: 1024
}

但如果我加一个限制条件          icon & typeof icon === 'string' & icon.includes(':')  ，不会报错，正常运行，但图标无法显示

**Comment by xiaoxian521** [comment]
请按照文档用法使用，其余的自行扩展哈
