### ISSUE TITLE
左下角折叠菜单图标按钮点击后会有1s左右延迟，使用体验上卡顿的感觉

### ISSUE THREAD

**Issue by CoderFXJ** [xiaoxian521/vue-pure-admin#405]
**Describe the bug**
我发现左下角折叠图标按钮点击后会有1s左右延迟，使用体验上卡顿的感觉，看了源码没发现定时器之类，请问这是bug吗？
**To Reproduce**
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/68853957/209048527-c1a6f38e-4e02-4ef9-aaf7-d368640b185e.png">

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 12.5
 - Browser :chrome 
 - Version : 108.0.5359.124（正式版本） (arm64)

**Comment by xiaoxian521** [comment]
那是动画时长

**Comment by xiaoxian521** [comment]
菜单越多 时长就会越多
