### ISSUE TITLE
使用了Table 表格页面空白

### ISSUE THREAD

**Issue by JakeWoki** [xiaoxian521/vue-pure-admin#406]
页面有用到了Table 表格，第一次打开正常，再打开其它任意页面都是空白的，再点回有表格那个页面也是空白，F5刷新显示出来，点其它又是空白。如果一直不点那个表格页面，页面是可以正常显示出来的。请问这个是什么原因导致的

**Comment by xiaoxian521** [comment]
提供具体代码

**Comment by JakeWoki** [comment]
我知道了弹窗之类的我没放在div内，然后点其它页面就空白
