### ISSUE TITLE
菜单收缩起来echarts不会自适应显示

### ISSUE THREAD

**Issue by coderwyd** [xiaoxian521/vue-pure-admin#409]
**Describe the bug**
菜单收缩echarts不会自适应显示，会出现留白

**To Reproduce**
1. 登录网站
2. 点击菜单收缩按钮
3. 查看echarts表现

**Expected behavior**
自适应显示

**Screenshots**
![image](https://user-images.githubusercontent.com/53386850/209770680-d60bc9cc-911a-4534-a4a8-8b127d9f0eb4.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome
 - Version: 108.0.5359.125

**Smartphone (please complete the following information):**

**Additional context**

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/xiaoxian521/vue-pure-admin/commit/d0ed3be8275ba6174a644e594d61ca7f206c723d)
