### ISSUE TITLE
能否出一个4级菜单的布局格式？

### ISSUE THREAD

**Issue by CalvinP-Cai** [xiaoxian521/vue-pure-admin#410]
左边是一级菜单，二三四级菜单在第二栏。如图：
![image](https://user-images.githubusercontent.com/37281618/210025162-91c4574d-473b-47d2-a3ad-021de65adb74.png)

**Comment by xiaoxian521** [comment]
使用混合导航

**Comment by CalvinP-Cai** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
