### ISSUE TITLE
label 的样式错误

### ISSUE THREAD

**Issue by xieliuning** [xiaoxian521/vue-pure-admin#416]
**Describe the bug**
在 <el-form-item> 下使用 <el-date-picker type='daterange'>，label 的字体样式会有错误

![image](https://user-images.githubusercontent.com/49332876/210737174-d55ab710-26e9-4466-8203-cb6b824916da.png)

  "name": "vue-pure-admin",
  "version": "3.9.7",

**Comment by xiaoxian521** [comment]
这是业务代码 自定义 如果想保持一致安装我那里的业务代码编写
