### ISSUE TITLE
项目模板只能用于单应用场景，如果能支持多应用管理就更好

### ISSUE THREAD

**Issue by haoljp** [xiaoxian521/vue-pure-admin#417]
项目模板只能用于单应用场景，如果能支持多应用管理就更好，比如后台项目可能包含多个子业务系统。比如这个模板https://admin.zhontai.net/
![image](https://user-images.githubusercontent.com/5848067/211133017-43d1142e-abdb-43d5-87c4-6862fc3c7a27.png)

**Comment by xiaoxian521** [comment]
不限制场景 自行改造 明年可能接入qiankun

**Comment by haoljp** [comment]
我是一后端程序员正在学习中，作者辛苦了！
