### ISSUE TITLE
卡顿

### ISSUE THREAD

**Issue by weijianpeng18421** [xiaoxian521/vue-pure-admin#421]
**不知道是不是我电脑的原因，我本地启动的完整版项目，点击左边的标签切换时会很卡，延迟两秒左右才能切换过去**

**工具用的webstorm**
 - Device: [edge: 108.0.1462.76 (正式版本) (64 位)]
 - OS: [edge: 108.0.1462.76 (正式版本) (64 位)]
 - Browser [edge]
 - Version [108.0.1462.76 (正式版本) (64 位]

**Comment by xiaoxian521** [comment]
无法复现
