### ISSUE TITLE
[Component] [pagination] pagination组件的警告

### ISSUE THREAD

**Issue by xieliuning** [xiaoxian521/vue-pure-admin#422]
![image](https://user-images.githubusercontent.com/49332876/212677735-01dd67a8-2d3b-46f5-981c-b1b2b065f1bd.png)

[分页器](https://element-plus.gitee.io/zh-CN/component/pagination.html#%E4%BA%8B%E4%BB%B6)

el-官方说，在未来会废弃这些分页器的事件，咱们会跟进这个警告吗？

**Comment by xiaoxian521** [comment]
参考平台puretable用法 注意哪些必传 等他们废弃会跟进
