### ISSUE TITLE
问题：怎样可靠的实现参数化无layout布局

### ISSUE THREAD

**Issue by haelue** [xiaoxian521/vue-pure-admin#423]
我希望在路由后面加入一个查询参数，比如 http://localhost:8848/#/welcome?layout=no
通过 layout=no 实现任意 view 去除 layout（没有左侧菜单和上部菜单）
请问怎样实现比较好，不容易出bug？（初次接触 pure 不熟悉，怕跟哪些机制冲突了）

**Comment by xiaoxian521** [comment]
通读文档 你会找到答案
