### ISSUE TITLE
子级菜单（路由）只有一个时，使用菜单搜索会搜索不到

### ISSUE THREAD

**Issue by simple-ice** [xiaoxian521/vue-pure-admin#424]
### 问题
在预览demo中使用菜单搜索，输入`列表页`会出现`列表页`候选项目录，此时正常。
如果输入`列表页`里的`卡片列表页`菜单，则显示`暂无数据`。

### 原因

文件：`src\layout\components\search\components\SearchModal.vue`
```
/** 菜单树形结构 */
const menusData = computed(() => {
  return deleteChildren(cloneDeep(usePermissionStoreHook().wholeMenus));
});

```
deleteChildren方法会将父级中children长度为1的数据删除，导致搜索不到子级。

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/xiaoxian521/vue-pure-admin/commit/4a032426a8f63730034011b2a36d48522e0d1230)
