### ISSUE TITLE
PureDescriptions组件的配置项用法教程在哪可以看到

### ISSUE THREAD

**Issue by carpONE** [xiaoxian521/vue-pure-admin#425]
PureDescriptions组件的配置项用法教程在哪可以看到

**Comment by xiaoxian521** [comment]
参考 https://github.com/xiaoxian521/vue-pure-admin/tree/main/src/views/about

**Comment by xiaoxian521** [comment]
这个也行 https://github.com/xiaoxian521/pure-admin-descriptions/tree/main/src
