### ISSUE TITLE
Adapt it for nuxt3

### ISSUE THREAD

**Issue by lluc2397** [xiaoxian521/vue-pure-admin#426]
The project is awesome. 

Just a little request as I'm not that familiar with nuxt nor vue. But could it be adapted to nuxt3?

**Comment by xiaoxian521** [comment]
The plan to support the nuxt version has been planned for a long time, but due to time and energy issues, I can only continue to postpone it, because there are other things that need to be done 🤗️

**Comment by xiaoxian521** [comment]
It can be seen that you are very interested, or you can transform this project https://github.com/xiaoxian521/pure-admin-thin into nuxt3

**Comment by lluc2397** [comment]
Thanks, I'll give it a look
