### ISSUE TITLE
动态路由刷新时Vue-router有警告

### ISSUE THREAD

**Issue by yymjku18** [xiaoxian521/vue-pure-admin#427]
**问题描述**
当动态路由页面刷新或是热重载后，浏览器控制台就会警告
vue-router.mjs:35 [Vue Router warn]: No match found for location with path "/XXX/XXX"
虽然不影响使用，但排查错误的时候控制台总是多这么一行也很难受。

**原因简析**
应该是由于vue-router4以后，用addRoute动态追加404导致的，当然不是很想回退老版本vue-router

**解决方案**
似乎现在更加建议使用
``` {
      path: "/:catchAll(.*)",
      name: "404",
      component: () => import("@/views/error/404.vue"),
      meta: {
        title: $t("menus.hsfourZeroFour")
      }
    },
```
的写法，Pure项目里尝试过警告确实消失

**问题点**
但不知道这么改会不会对现有的路由相关逻辑和项目的整体设计有影响。

**Comment by xiaoxian521** [comment]
多看文档
https://yiming_chang.gitee.io/pure-admin-doc/pages/FAQ/#%E5%8A%A8%E6%80%81%E8%B7%AF%E7%94%B1%E5%88%B7%E6%96%B0%E5%87%BA%E7%8E%B0%E8%AD%A6%E5%91%8A-%E2%9A%A0%EF%B8%8F

**Comment by yymjku18** [comment]
@xiaoxian521 啊抱歉，是我粗心了

**Comment by xiaoxian521** [comment]
`vue-router`作者认为该警告是有必要的 咱也没办法 😂
