### ISSUE TITLE
配置Theme为light，清空缓存重新登录主题配置不生效

### ISSUE THREAD

**Issue by superliu0** [xiaoxian521/vue-pure-admin#429]
serverConfig.json中配置Theme为light，退出系统刷新重进首页主体色还是黑色，在页面主体配置中点light主体才回生效

**Comment by xiaoxian521** [comment]
请手动清空本地缓存

**Comment by xiaoxian521** [comment]
[fixed](https://github.com/xiaoxian521/vue-pure-admin/commit/eeea7bf718f1098d0ad4e1ce63731613f3b94248)
