### ISSUE TITLE
Docker运行该项目的一些问题

### ISSUE THREAD

**Issue by Guanrui1** [xiaoxian521/vue-pure-admin#430]
**问题描述**
> 问题一：映射好的项目外部无法访问

将此项目在docker搭建的环境中可以正常运行

![image](https://user-images.githubusercontent.com/36908524/216208548-52285666-a0a4-4da1-b0e6-06222c6ca2c8.png)

但是此项目不能和普通的vue-cli搭建的vite项目一样，通过映射端口的方式让外部访问

![image](https://user-images.githubusercontent.com/36908524/216208991-52a5b006-47a8-4193-ba2f-1d66e3a98c63.png)

> 问题二：docker里运行的项目无法通过快捷键`ctrl` + `c`关闭项目，只有强制关闭终端或者重启容器才可以关闭项目

期待解决...

**Comment by Guanrui1** [comment]
补充：这两个问题都是普通的vue-cli搭建的`vite4.0`，`vue3`项目没有的问题，怀疑是该框架做了某些特殊处理导致的。

**Comment by xiaoxian521** [comment]
首先 `vue-cli` 和 `vite` 是两个东西
平台并没有设置任何东西，而且 `docker` 部署与项目本身并无关联，非平台问题
