### ISSUE TITLE
echarts貌似只支持light和dark主题，如何使用自定义主题？

### ISSUE THREAD

**Issue by PopezLotado** [xiaoxian521/vue-pure-admin#431]
![image](https://user-images.githubusercontent.com/9564883/216506667-01623669-5963-4da6-b68f-7585144cd54b.png)
如图，代码在pure-admin-util中，这个模块能否开源？

**Comment by xiaoxian521** [comment]
https://github.com/xiaoxian521/vue-pure-admin/blob/main/src/plugins/echarts/index.ts#L36
