### ISSUE TITLE
使用jsx热更新后路由渲染空白

### ISSUE THREAD

**Issue by congLinx** [xiaoxian521/vue-pure-admin#432]
问题描述：使用jsx语法后，热更新后路由空白

复现流程：
1.git clone下来pure-admin-thin
2.在welcome文件上写上jsx，并使用
3.反复修改jsx写的组件里面的值
4.热更新后，点击左侧不同的菜单路由会空白

<img width="557" alt="image" src="https://user-images.githubusercontent.com/112139220/216509488-fa0c5559-adfc-4ff1-bc64-54487fe89123.png">

**Comment by xiaoxian521** [comment]
反复修改干啥？ 如果反复修改造成空白 可能是 `vite` 或 `vue` 的问题

**Comment by congLinx** [comment]
> 反复修改干啥？ 如果反复修改造成空白 可能是 `vite` 或 `vue` 的问题 还有你这里 `lang` 为什么用 `tsx` 完全没必要

1.就是热更新一次jsx就会出现路由空白？修改其他的不会出现路由空白
2.lang使用tsx是为了在vue文件里面写jsx
