### ISSUE TITLE
导航栏左侧模式，如果二级菜单过长，点击下面的菜单的时候跳转位置不对

### ISSUE THREAD

**Issue by ldw4033** [xiaoxian521/vue-pure-admin#433]
<img width="208" alt="image" src="https://user-images.githubusercontent.com/5718303/216537762-885a7fc3-6483-4ed9-8c3b-1fecdb6b941b.png">
如果我下滑点击 “功能”，并不能准确跳转到合适位置
<img width="211" alt="image" src="https://user-images.githubusercontent.com/5718303/216537949-cb7c1877-83f1-4381-8812-af128fe3b4a6.png">

**Comment by xiaoxian521** [comment]
非平台问题 观察 `element-plus` 的 `menu`
