### ISSUE TITLE
更改环境PORT，貌似并未生效

### ISSUE THREAD

**Issue by hb0730** [xiaoxian521/vue-pure-admin#44]
![image](https://user-images.githubusercontent.com/33956166/134601014-345e48d3-d45f-4d20-8c6e-9fb2e1596b03.png)
![image](https://user-images.githubusercontent.com/33956166/134601037-1dd9005e-8add-448c-8954-19810f9c0c40.png)
![image](https://user-images.githubusercontent.com/33956166/134601128-4af226c3-c170-4b0f-a13e-c0db17c26ab9.png)
![image](https://user-images.githubusercontent.com/33956166/134601148-8be8bd26-8b6f-479e-86af-7bb2197da254.png)

**Comment by hb0730** [comment]
当使用vite的LoadEnv时是可行的
![image](https://user-images.githubusercontent.com/33956166/134601482-da468ef6-07ac-4a35-a4b1-1be5c29e0b10.png)
![image](https://user-images.githubusercontent.com/33956166/134601501-05cc0f69-166a-416e-bcc1-f9f9e5023ec9.png)

**Comment by xiaoxian521** [comment]
你修改这个文件就行了
![image](https://user-images.githubusercontent.com/44761321/134604260-2663d484-a6a7-4b7d-9414-6e3103cd7e51.png)

**Comment by hb0730** [comment]
还有单独调用loadEnv方法，好像process.cwd()报错了
![image](https://user-images.githubusercontent.com/33956166/134610315-a5d3e699-518b-4e5b-a200-999916914316.png)

**Comment by xiaoxian521** [comment]
并没有呢
![image](https://user-images.githubusercontent.com/44761321/134610479-a77b7d02-6e3a-4c1d-8645-8438052de454.png)

**Comment by hb0730** [comment]
我是在router index.ts中单独调用，发现process.cwd报错，但是在vite.config.ts中调用process.cwd是没有问题的

![image](https://user-images.githubusercontent.com/33956166/134610990-99354414-cbec-43b1-98e5-45771599ea9d.png)
![image](https://user-images.githubusercontent.com/33956166/134611033-637a9ad2-aec4-4d1d-b44f-9e77f7cb3c33.png)
![image](https://user-images.githubusercontent.com/33956166/134611040-529ba00e-74bc-4ca8-b52d-68c11a8aacd2.png)

难道无法再别的地方调用么~~

**Comment by xiaoxian521** [comment]
比如你可以这样用：process.env.NODE_ENV

**Comment by xiaoxian521** [comment]
别忘了设置这个
![image](https://user-images.githubusercontent.com/44761321/134612246-1aabaa5a-cc16-4f0e-b6e0-2d462e7249bc.png)

**Comment by hb0730** [comment]
![image](https://user-images.githubusercontent.com/33956166/134639211-a03281c9-6ae9-4c5a-a09b-6e6c2f3f3c6e.png)
![image](https://user-images.githubusercontent.com/33956166/134639235-eaff823b-c7d7-4a1b-ae36-b4ee218b9079.png)

这样可以保证loadEnv在任何地方不会抛出process.cwd is not a function

**Comment by xiaoxian521** [comment]
是的，这样是可以的，但是当引入某些第三包时，会出现打包错误

**Comment by hb0730** [comment]
[3817](https://github.com/vitejs/vite/issues/3817) 有类似案例，仓库地址: [vite_vue3_web3](https://github.com/EvinqWang/vite_vue3_web3)

**Comment by hb0730** [comment]
好像最终只需要
![image](https://user-images.githubusercontent.com/33956166/134802653-701d1a7c-83bb-4c78-a76d-b3b07e875b82.png)
就行了，不需要其他插件

**Comment by xiaoxian521** [comment]
> 好像最终只需要
> ![image](https://user-images.githubusercontent.com/33956166/134802653-701d1a7c-83bb-4c78-a76d-b3b07e875b82.png)
> 就行了，不需要其他插件

这样打包部署会找不到process 我已经删除了此代码 请检查对你有没有影响

**Comment by hb0730** [comment]
好的，在更改之后，我在本地build 部署之后是可以正常运行的，之前这么做是因为dotenv 读取环境变量用到了node相关内置函数，现在应该没有什么影响

**Comment by AdminQQZ** [comment]
![image](https://github.com/pure-admin/vue-pure-admin/assets/12959954/31454ed3-2fb7-40ae-92bd-03695bd5565f)
你们是怎么解决的来着，我没看懂
