### ISSUE TITLE
运行项目后一直停留在加载页

### ISSUE THREAD

**Issue by huedcode** [xiaoxian521/vue-pure-admin#5]
控制台提示 Uncaught SyntaxError: Unexpected token .

**Comment by xiaoxian521** [comment]
清空一下浏览器缓存 点击免密登陆

**Comment by xiaoxian521** [comment]
请检查是否安装vite
如未安装请执行：npm i create-vite-app -g
注意Vite 需要 Node.js 版本 >= 12.0.0

**Comment by nile52** [comment]
浏览器版本过低。代码使用到 `?.`，低版本浏览器可能不支持。浏览器支持说明如下：https://caniuse.com/?search=%3F.
