### ISSUE TITLE
生产打包指定base资源访问地址，主题样式文件layout-theme-default.css加载地址错误

### ISSUE THREAD

**Issue by Judy2013** [xiaoxian521/vue-pure-admin#522]
需要配置微应用的部署打包文件，需要指定资源访问地址，设置了base，结果访问地址ip重复了。

![image](https://user-images.githubusercontent.com/5804301/233438481-75e043da-e3d7-4708-8af7-59f0c70e6dcf.png)

**Comment by xiaoxian521** [comment]
看文档
