### ISSUE TITLE
ElementPlus 分页组件问题

### ISSUE THREAD

**Issue by hb0730** [xiaoxian521/vue-pure-admin#56]
![image](https://user-images.githubusercontent.com/33956166/137273245-95d1389e-9fd8-4b35-b888-ebd6de2dcdd3.png)
![image](https://user-images.githubusercontent.com/33956166/137273278-11aa826d-b8b3-4560-a70d-0e31261cdc8c.png)

---------------------
![image](https://user-images.githubusercontent.com/33956166/137273362-022a6364-9947-465e-8b11-3750ad35cb4b.png)
![image](https://user-images.githubusercontent.com/33956166/137273422-a27bc2ae-cdc9-4f10-8e57-d3f0b21e3fd1.png)

个人vue-pure-admin版本与当前版本一致
    "element-plus": "1.1.0-beta.20",

**Comment by xiaoxian521** [comment]
try 
`'sizes, prev, pager, next, jumper, ->, total'`
