### ISSUE TITLE
ElInfiniteScroll 错误

### ISSUE THREAD

**Issue by hb0730** [xiaoxian521/vue-pure-admin#58]
![image](https://user-images.githubusercontent.com/33956166/137680998-f99f082c-6353-4826-9b30-b505769ca35f.png)

**Comment by xiaoxian521** [comment]
将ElInfiniteScroll放入plugins
![image](https://user-images.githubusercontent.com/44761321/137681568-11262c9d-2d7c-40b4-a7d7-a700fc92dc56.png)
