### ISSUE TITLE
keep-alive缓存会造成子路由重复渲染

### ISSUE THREAD

**Issue by RanMaoting** [xiaoxian521/vue-pure-admin#67]
你好，请教一下，最新版使用了keep-alive的页面生命周期会加载多次，导致页面重复请求，这种怎么解决呢

**Comment by xiaoxian521** [comment]
> 你好，请教一下，最新版使用了keep-alive的页面生命周期会加载多次，导致页面重复请求，这种怎么解决呢
能提供个例子吗

**Comment by xiaoxian521** [comment]
> 你好，请教一下，最新版使用了keep-alive的页面生命周期会加载多次，导致页面重复请求，这种怎么解决呢

提供个例子吧

**Comment by RanMaoting** [comment]
就现在的线上demo多级路由那一块，menu1-2-2路由keepAlive改为false，页面加上生命周期就可以发现他们被执行了多次

**Comment by xiaoxian521** [comment]
https://github.com/xiaoxian521/vue-pure-admin/commit/d57e0e379e5c56f97a9efc14e1f84b9e06454cba

**Comment by anyshift** [comment]
一级 router-view 设置成 `<component :is="Component" :key="undefined"/>` 后临时解决了困恼好多天的问题，不过还是期待 vue-router 官方能给出更好的解决办法

**Comment by init-center** [comment]
> 一级 router-view 设置成 `<component :is="Component" :key="undefined"/>` 后临时解决了困恼好多天的问题，不过还是期待 vue-router 官方能给出更好的解决办法

这个确实能解决问题，但是不知道原理是什么😂
