### ISSUE TITLE
动态切换i18n，element-plus国际化不完整

### ISSUE THREAD

**Issue by zy94xhn** [xiaoxian521/vue-pure-admin#7]
中文
![image](https://user-images.githubusercontent.com/51955207/117396923-939f1e80-af2d-11eb-8ea2-e55cbaaf4d55.png)

英文
![image](https://user-images.githubusercontent.com/51955207/117396953-9c8ff000-af2d-11eb-9e3a-ccfcae954e00.png)

**Comment by xiaoxian521** [comment]
是否拉取的是最新代码

**Comment by xiaoxian521** [comment]
@zy94xhn 如未解决，请打开issues

**Comment by zy94xhn** [comment]
@xiaoxian521 我是照着你的写的i18n,打包之后国际化还会报错，很奇怪的错误，什么a 未定义

**Comment by xiaoxian521** [comment]
提供下代码仓库 我帮你调试下 
我这边的项目在线预览地址是最新的代码，线上环境也没问题http://yiming_chang.gitee.io/manages/#/welcome

**Comment by zy94xhn** [comment]
![image](https://user-images.githubusercontent.com/51955207/117425234-31f2aa80-af55-11eb-932d-584d1f01329a.png)
不管是element的还是vxe的都会报错，只要用到国际化的部分都会报错

**Comment by xiaoxian521** [comment]
提供下代码仓库地址吧

**Comment by zy94xhn** [comment]
稍等 我提交一下代码https://github.com/zy94xhn/vite2-template

**Comment by xiaoxian521** [comment]
你代码仓库地址的项目比不是我的项目哦

**Comment by zy94xhn** [comment]
我照着你的i18n写的，没写过这个 Orz。。
开发环境没问题，打包就崩了，哭了，我b站关注你的，如果你是那个作者的话，哈哈哈

**Comment by xiaoxian521** [comment]
哈哈 可以的 原来是b站老友啊

**Comment by zy94xhn** [comment]
是的，我就是照着你那个视频搞的，哈哈哈，我下班了，可以那啥，b站聊吗

**Comment by xiaoxian521** [comment]
都行

**Comment by xiaoxian521** [comment]
那我先关闭这个issues
