### ISSUE TITLE
期望增加js版本

### ISSUE THREAD

**Issue by chenning111** [xiaoxian521/vue-pure-admin#8]

**Comment by xiaoxian521** [comment]
可以考虑的，需等TS版本全部开发完毕。

**Comment by GitHubElena** [comment]
期望开发多环境的不含ts版本的

**Comment by xiangshu233** [comment]
TS 逃不掉的 学吧，毕竟vue3 都是 ts 重构 的

**Comment by jichangxiu** [comment]
可以看看我魔改的：
https://gitee.com/jichangxiu/vue-pure-admin.git
https://gitee.com/jichangxiu/vue-pure-admin-thin.git
https://gitee.com/jichangxiu/vue-pure-admin-thin-i18n.git
我只是提供了一个js版本，没在生产环境用过。不对任何代码负责，有问题也不要找我。不提供解决方案，尊重原作。
