### ISSUE TITLE
在完整版本中也出现useECharts报错

### ISSUE THREAD

**Issue by 6ivan** [xiaoxian521/vue-pure-admin#804]
### 描述问题 (Describe the problem)

![image](https://github.com/pure-admin/vue-pure-admin/assets/48577458/29577324-1bfa-418b-9f5b-c528f0d93f49)
![image](https://github.com/pure-admin/vue-pure-admin/assets/48577458/5f1a15b2-67b8-4a54-8851-f7da344a27d1)
在完整版本中异步请求就会报错

### 如何复现该问题 (How to reproduce the problem)

使用完整版用mock接口做请求然后使用useECharts

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
额 明天有空我会更新demo 然后给个链接给你参考

**Comment by 6ivan** [comment]
> 额 明天有空我会更新demo 然后给个链接给你参考

好的谢谢

**Comment by xiaoxian521** [comment]
https://pure-admin-utils.netlify.app/hooks/useEcharts/useEcharts

<img width="1399" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/2aa9ef80-89c2-42d6-978e-fbce436cc5a6">
