### ISSUE TITLE
国际化切换之后需要刷新下页面才生效？

### ISSUE THREAD

**Issue by hogger0** [xiaoxian521/vue-pure-admin#822]
### 描述问题 (Describe the problem)

<img width="585" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/6472032/1095831c-f99a-431f-9a7a-133b6d654c56">
表头上使用国际化，用法是对的吗？现在是切换之后需要刷新下页面才生效，我看菜单栏和分页都是点击切换就变了

### 如何复现该问题 (How to reproduce the problem)

无

### 操作系统和浏览器信息 (Operating system and browser information)

无

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
https://github.com/pure-admin/pure-admin-table/issues/53

**Comment by xiaoxian521** [comment]
对应问题在对应地方去找 也要在对应地方提问
