### ISSUE TITLE
更改代码自动编译刷新时出现错误

### ISSUE THREAD

**Issue by hb0730** [xiaoxian521/vue-pure-admin#88]
![image](https://user-images.githubusercontent.com/33956166/139562921-f3999a34-edbc-45c2-91ce-96366920f9e5.png)

**Comment by xiaoxian521** [comment]
目前我们团队好像没出现过此问题，能复现吗

**Comment by xiaoxian521** [comment]
这个问题是没引入组件就注册页面组件造成的，element-plus会判断为错误

**Comment by hb0730** [comment]
好像是渲染时机问题，
现有默认的： 
![image](https://user-images.githubusercontent.com/33956166/139583065-7d811da7-e2e9-49f2-9ae7-9a718bf3012c.png)
自定义页面(有问题的):
![image](https://user-images.githubusercontent.com/33956166/139583103-28e1b60d-ecad-45f3-a031-97b2eb72c6c5.png)

**Comment by xiaoxian521** [comment]
你出这个问题element-plus报这个错误之前肯定还有别的报错 把前端的报错解决就行了

**Comment by hb0730** [comment]
原因：在`onBeforeMount()`期间request请求，使用了ElLoading 组件
![image](https://user-images.githubusercontent.com/33956166/139585234-84531014-c300-4519-bb5d-dcca8c345a02.png)
导致的，
demo:  https://github.com/hb0730/vue-pure-admin/blob/backtop/src/api/test_request_callback.ts

**Comment by xiaoxian521** [comment]
嗯嗯 最小版本的element-plus更换了原来的icon采用svg方式 等我升级到v2.6.0版本后在去element-plus里做处理吧

**Comment by hb0730** [comment]
@xiaoxian521  `onMounted`周期中去调用请求好像没有什么问题

**Comment by xiaoxian521** [comment]
是的
