### ISSUE TITLE
pnpm install 安装架包时报错

### ISSUE THREAD

**Issue by xuyangjiahe** [xiaoxian521/vue-pure-admin#93]
*****架包 安装时  报  GET https://registry.npm.taobao.org/@intlify/core-base/-/core-base-9.2.0-beta.17.tgz: Not Found - 404

**Comment by xiaoxian521** [comment]
请参考https://github.com/xiaoxian521/vue-pure-admin/issues/92

**Comment by xiaoxian521** [comment]
请还原npm源
npm config set registry https://registry.npmjs.org
