### ISSUE TITLE
🙏目前vite打包的问题

### ISSUE THREAD

**Issue by xiaoxian521** [xiaoxian521/vue-pure-admin#94]
可能你会遇到如下图警告，警告过多，导致打包时间过长，让我们耐心一点，等待官方解决🙏
目前解决方案：build: { minify: false } ，不采用Esbuild打包最小化混淆
![image](https://user-images.githubusercontent.com/44761321/140042237-1fce2720-fb76-4251-acf6-f4dace172e1c.png)
![image](https://user-images.githubusercontent.com/44761321/140258719-d3f8b248-1c6d-475e-b765-7f3710818da6.png)

**Comment by sxzz** [comment]
Fixed in https://github.com/element-plus/element-plus/pull/4189 , you can also refer to 
- https://github.com/element-plus/element-plus/issues/3219#issuecomment-958849544
- https://github.com/element-plus/element-plus/issues/3219#issuecomment-960374776

**Comment by xiaoxian521** [comment]
fix: https://github.com/vitejs/vite/issues/5833
