### ISSUE TITLE
vite启动服务成功，但是修改vite.config.js就报错

### ISSUE THREAD

**Issue by wujun1994** [xiaoxian521/vue-pure-admin#947]
### 描述问题 (Describe the problem)

项目环境：1.node版本：20.11.1
                   2.nvm版本：1.1.11
                   3.pnpm版本：8.15.4
                   4.编辑器：webstorm2022.2.2
问题说明： 
1.npm install -g pnpm
2.https://github.com/pure-admin/vue-pure-admin.git 拉取代码后
 3. pnpm install
4.项目正常启动
5.修改vite.config.ts文件后或者修改其他文件保存
6.项目自动执行后报错：
                      error when starting dev server:
Error: EPERM: operation not permitted, copyfile 'E:\Works\GYTL\vue-pure-admin\node_modules\.pnpm\@pureadmin+theme@3.2.0\node_modules\@pureadmin\theme\dist\substitute\sass\sass.dart.js' -
> 'E:\Works\GYTL\vue-pure-admin\node_modules\.pnpm\sass@1.71.1\node_modules\sass\sass.dart.js'
7.无论做了什么操作,node_modules\.pnpm\sass@1.71.1\node_modules\sass\sass.dart.js这个目录下的sass.dart.js会自动删除掉，导致项目再次执行时，检索不到sass.dart.js的存在，导致项目无法使用
 8.sass.dart.js只要再次执行都会自动删除，然后一直报上面的错误；无法继续使用；
9.所有的环境都重装过，也是一样无法解决该问题，想看看各位大佬有办法解决吗？很想使用该项目啊

### 如何复现该问题 (How to reproduce the problem)

![微信图片_20240229190213](https://github.com/pure-admin/vue-pure-admin/assets/73600061/723d2620-8782-4e56-a08d-30ecaec9c9fc)

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by huankong233** [comment]
> ### 描述问题 (Describe the problem)
> 项目环境：1.node版本：20.11.1                    2.nvm版本：1.1.11                    3.pnpm版本：8.15.4                    4.编辑器：webstorm2022.2.2 问题说明： 1.npm install -g pnpm 2.https://github.com/pure-admin/vue-pure-admin.git 拉取代码后  3. pnpm install 4.项目正常启动 5.修改vite.config.ts文件后或者修改其他文件保存 6.项目自动执行后报错：                       error when starting dev server: Error: EPERM: operation not permitted, copyfile 'E:\Works\GYTL\vue-pure-admin\node_modules.pnpm@pureadmin+theme@3.2.0\node_modules@pureadmin\theme\dist\substitute\sass\sass.dart.js' -
> 
> > 'E:\Works\GYTL\vue-pure-admin\node_modules.pnpm\sass@1.71.1\node_modules\sass\sass.dart.js'
> > 7.无论做了什么操作,node_modules.pnpm\sass@1.71.1\node_modules\sass\sass.dart.js这个目录下的sass.dart.js会自动删除掉，导致项目再次执行时，检索不到sass.dart.js的存在，导致项目无法使用
> > 8.sass.dart.js只要再次执行都会自动删除，然后一直报上面的错误；无法继续使用；
> > 9.所有的环境都重装过，也是一样无法解决该问题，想看看各位大佬有办法解决吗？很想使用该项目啊
> 
> ### 如何复现该问题 (How to reproduce the problem)
> ![微信图片_20240229190213](https://private-user-images.githubusercontent.com/73600061/308898149-723d2620-8782-4e56-a08d-30ecaec9c9fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4MDc0MzgsIm5iZiI6MTczMTgwNzEzOCwicGF0aCI6Ii83MzYwMDA2MS8zMDg4OTgxNDktNzIzZDI2MjAtODc4Mi00ZTU2LWEwOGQtMzBlY2FlYzljOWZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE3VDAxMzIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmMzYwODVlODE4NjdiZjcyZGQ5ZWQ1OGVlMGQ5ZWIxOTliZDRlYzMyOGRjYjM1NjE5ZTBiNzkzZDljNzFhZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dKMhzfDML40t1Tt8NCZxII9kQiEPrZkFsnCeXNEF6Vw)
> 
> ### 操作系统和浏览器信息 (Operating system and browser information)
> _No response_
> 
> ### 验证 (Verify)
> * [x]  是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
> * [x]  检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

请问解决问题了吗，我遇到了类似的问题

```
Error: EPERM: operation not permitted, copyfile 'C:\Users\huan_kong\Desktop\code\HkList-frontend\node_modules\.pnpm\@pureadmin+theme@3.3.0\node_modules\@pureadmin\theme\dist\substitute\sass\types\compile.d.ts' -> 'C:\Users\huan_kong\Desktop\code\HkList-frontend\node_modules\.pnpm\sass@1.77.8\node_modules\sass\types\compile.d.ts'
```

![image](https://github.com/user-attachments/assets/897bd25c-14cc-47d9-b90c-fa817d152ccc)

**Comment by Ymonkey11** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已收到您的来信，查看后将尽快恢复，谢谢。
