### ISSUE TITLE
同级多个外链跳转会出现404

### ISSUE THREAD

**Issue by ivanberry** [xiaoxian521/vue-pure-admin#971]
### 描述问题 (Describe the problem)

当前配置已成功配置了一个外链路由，跳转符合预期，但是同级同时存在多个外链路由时，只有最后一个可以正常跳转，其他外链路由会出现404.

### 如何复现该问题 (How to reproduce the problem)

多增加一个外链路由

### 验证 (Verify)

- [X] 是否仔细阅读过 [文档](https://yiming_chang.gitee.io/pure-admin-doc/) (Have you read [documentation](https://yiming_chang.gitee.io/pure-admin-doc/) carefully)
- [X] 检查是否存在相同或类似的问题 [issues](https://github.com/pure-admin/vue-pure-admin/issues) (Check for the same or similar [issues](https://github.com/pure-admin/vue-pure-admin/issues))

**Comment by xiaoxian521** [comment]
咱文档很清楚哈 https://yiming_chang.gitee.io/pure-admin-doc/pages/routerMenu/#%E5%86%85%E5%B5%8C-iframe-%E5%92%8C%E5%A4%96%E9%93%BE
<img width="561" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/bdc75d30-7a8d-4679-9c8f-c0f3b746d026">

**Comment by xiaoxian521** [comment]
`thin`肯定支持的呀 `thin`版本大多数是把业务代码删了，所有核心功能都跟完整版保持一致哈

**Comment by ivanberry** [comment]
您文档很清楚，再次感谢。

我的外链路由是这么配置的

```javascript
export default {
  path: '/demo',
  meta: {
    title: 'xx'
  },
  children: [
    {
      path: '/demo/a1',
      meta: {
        title: 'a1'
      },
      children: [
        {
          path: "/anything1",
          name: "https://www.baidu.com",
          meta: {
            title: 'b1'
          }
        },
        { // 注释下面的路由，上面可以正常newtab打开，不注释，上面的路由
          // 不能外链打开，会去404路由，下面这个可以
          path: "/anything2",
          name: "https://www.baidu.com",
          meta: {
            title: 'b2'
          }
        },
      ]
    }
  ]
}
```

**Comment by xiaoxian521** [comment]
参考这个文件哈 目前我非常忙 没时间解决这种不确定性问题哈
<img width="843" alt="image" src="https://github.com/pure-admin/vue-pure-admin/assets/44761321/f0f21b54-6478-43fa-8379-e359559391a3">
