### ISSUE TITLE
Login页面user,password和组件不能双向绑定

### ISSUE THREAD

**Issue by habaoyf** [xiaoxian521/vue-pure-admin#99]
1.页面改变以后，变量不变，请问一下大佬，这是什么问题
![image](https://user-images.githubusercontent.com/45748106/140637936-d63f0d4e-163e-45aa-bc45-070637053e31.png)

2.页面的写法里面没有export default{
} 这些是新的写法吗？
![image](https://user-images.githubusercontent.com/45748106/140637999-8f639bd2-c69c-41df-be65-11c79b78d999.png)

**Comment by xiaoxian521** [comment]
这是vue3哈 不是vue2
目前写法都是单文件组件setup
可以自己去了解一下
https://v3.cn.vuejs.org/api/sfc-script-setup.html
